### ISSUE TITLE
Unable to block or delete users when IP address blocking is enabled

### ISSUE THREAD

**Issue by weaverba137** [q2a/question2answer#1008]
**Describe the bug**
Blocking IP addresses causes unexpected changes to User controls.

**To Reproduce**
1. Add one or more IP addresses to "Blocked IP addresses" in the Spam admin panel.
2. Go to the list of users, click on any user.
3. All the User control buttons are missing. No Block, no Delete.
4. Remove all IP addresses from "Blocked IP addresses".
5. Go to the list of users, click on any user.
6. The User control buttons reappear.

**Expected behavior**
I would *not* expect the blocking of IP addresses to have anything to do with User controls.

**System information:**
 - Server/OS: Unknown
 - PHP version: 8.0.30
 - MySQL version: 10.5.22-MariaDB
 - Q2A version: 1.8.6 (based on the change log, it is not obvious that this was fixed in 1.8.8)
 - Browser: Safari

**Comment by pupi1985** [comment]
I've tested this in PHP 8.3 and Q2A 1.8.8 and it is working fine. Maybe the theme or a plugin might be interfering in your setup.

**Comment by weaverba137** [comment]
Thank you, I will pass this on to the admin.

**Comment by weaverba137** [comment]
Thank you for your help with this. Here's what really happened:

1. Our service operates "behind" Cloudflare.
2. We were blocking Cloudflare IP addresses instead of the real IP address.
3. Once we started passing the real IP address to q2a, everything started working again.
