### ISSUE TITLE
Make the category widget a real widget

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#106]
This issue is hopefully solved for v1.7: 

"If you activate categories, you will find something like this in your sidepanel: 

![image](http://www.question2answer.org/qa/?qa=blob&qa_blobid=1234636163748799622)

This looks like a widget, right. But if you check admin/layout under widgets, it is not listed (!)

So you cannot remove it, or put it to another position.

This is why I recommend to create a "real" widget for the categories instead. This has been done already with qa-widget-activity-count.php, qa-widget-ask-box.php and qa-widget-related-qs.php in the qa-include folder (the core folder)."

From: http://www.question2answer.org/qa/39105/recommendation-to-core-make-the-category-widget-real-widget

Also mentioned in Nov 2013: http://www.question2answer.org/qa/29155/categories-widget-is-not-a-widget

**Comment by svivian** [comment]
This has been completed in the 1.8 branch. (Surprisingly complicated, since it's currently stored in the navigation array and varies per page...)

**Comment by q2apro** [comment]
Good work.

**Comment by amint** [comment]
Thank you Scott
