### ISSUE TITLE
Make it possible to give the follow button a value

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#116]
function favorite_button($tags, $class)
		{
			if (isset($tags))
				$this->output('<input '.$tags.' type="submit" value="" class="'.$class.'-button" /> ');
		}

Should also pass a value field. 

I ran into this issue when writing a plugin and needed to assign a text to the favorite button.

PS: As I see this is in qa-theme-base.php - but nevertheless, it would be nice to have it core :)

**Comment by svivian** [comment]
Sorry for the super late reply. I think the only real solution is to override the appropriate function(s) in your custom theme. It's not appropriate as a language setting as it depends on your theme and its CSS. Same goes for an admin option.

You don't have to even change it to a `<button>`, you can just copy the `favorite_button` function to your theme and change `value=""` to your desired value. You may even be able to do this using CSS along with the `::after` selector.
