### ISSUE TITLE
Adding a date field to qa_uservotes

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#134]
This is of quite high importance so I dare to post it here again in the hope, Scott can add it to v1.7.
http://www.question2answer.org/qa/35295/adding-a-date-field-to-qa_uservotes

---

PS: @svivian Just came to my mind as well: Please finally link the headline of each question in core, this is standard on all sites now that I know :) ... remember, we talked about this once. 

https://github.com/q2a/question2answer/blob/dev/qa-include/app/format.php#L298

Change from: 

```
$fields['title']='<span class="entry-title">'.$fields['title'].'</span>';
```

To: 

```
$fields['title'] = '<a href="'.$fields['url'].'" class="entry-title">'.$fields['title'].'</a>';
```

**Comment by svivian** [comment]
This was completed a little while ago: 5fe3f760db4dae2293ba60e5f92eaa90a59b1d0d

Two fields were added, `votecreated` and `voteupdated` so you can track when a vote was first made and if/when it changed.
