### ISSUE TITLE
Messages from deleted users show username as blank

### ISSUE THREAD

**Issue by svivian** [q2a/question2answer#161]
Opening this as a separate issue from #128.

When a user is deleted, their public/private messages remain in the database, and the username shows up blank (instead of "Aug 2 by Username" it shows " Aug 2 by ").

Probably need to set the userid to NULL, and for PMs make sure that when the recipient deletes the message, it is actually removed from the database.

**Comment by ericscotts** [comment]
I had some issues with the titles of my papers. The same. When I delete a title (as it was similar to the username), it appears that the page is blank and nothing else is shown. The database of the students titles was full and I had to learn how to create a cool title for my essay with [essay writing service](http://essaydune.com/) writer's help.
Now, everything is fixed, as I reinstalled the plugin. Perhaps, there was a bug.
