### ISSUE TITLE
Extending qa-blob.php to display uploaded PDFs

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#174]
An old issue that I solved when adding PDF parsing / embedding to NoahY's embed plugin. 

Please add to file **qa-include/qa-blob.php** after line: 

	$filename=preg_replace('/[^A-Za-z0-9 \\._-]/', '-', $blob['filename']); // for compatibility with HTTP headers and all browsers

The lines: 

	// q2apro hack for embed pdf
	if($blob['format']=='pdf') {
		header('Content-Type: application/pdf');
		header('Content-Disposition: inline; filename="'.$filename.'"');					
		break;
	}

This allows clicking a PDF - and instead the download dialog you get the PDF display within the browser (standard nowadays). Thanks.

**Comment by svivian** [comment]
Finally got around to fixing this (deffa19).

pupi1985 is correct that this could be more extensible. But I'm not sure how much demand there is for that - PDF is a very common scenario, but downloads probably work fine for everything else.
