### ISSUE TITLE
Tiny restructuring of the admin panel: spam/users to /users

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#178]
Again I could not find some options related to "users", finally I found them under "spam": 

- Request confirmation of user emails: 	
- New users must complete confirmation: 	
- Enable moderation (approval) of users: 	add registration fields
- Email me when a new user registers: 	
- Temporarily suspend new user registrations: 	

I am sure, this should to be found under "users" not "spam". What is your opinion?

Thanks,
Kai

PS: I was searching the option "Email me when a new user registers"

**Comment by svivian** [comment]
Finally looked at this. I think the first 3 of those options are definitely spam-related so I won't move those. The other two may be used to combat spam but are not exclusively used for spam, so I have moved those.
