### ISSUE TITLE
migration from phpmyfaq to q2a

### ISSUE THREAD

**Issue by vedhavyas** [q2a/question2answer#185]
hi,

Im planning on migrating from phpmyfaq to q2a and at the same time i do not want to lose my mysql data dump from phmyfaq. is there a way i could migrate my db from phpmyfaq to q2a.

Hoping for a quick and positive reponse

**Comment by svivian** [comment]
Hi vedhavyas, the Github repo is for reporting bugs not support requests. I suggest you ask on the [Q2A Q&A site](http://www.question2answer.org/qa/) and hopefully some users can help you. Thanks.
