### ISSUE TITLE
qa-lang-profile.php , minor typo

### ISSUE THREAD

**Issue by MaxjTechno** [q2a/question2answer#186]
when you disallow posting on a user's wall.

Login --> User profile page --> Edit profile ---> Wall posts ---> deselect the checkbox : "Allow users to post on your wall (you will also be emailed)" ---> save profile ---> logout

When you access that user's profile page, the message is :
"This user has disallowed new posts on **their** wall"
that is, a plural possessive adjective is used referring to a single user.

edit :
on master branch

ps
but I'm not an English native speaker , so you're free to contradict me :-)

**Comment by svivian** [comment]
No that is correct - "their" can refer to a single person too, specifically when the person's gender is not known (otherwise you would use his or her). See http://dictionary.reference.com/browse/their
