### ISSUE TITLE
reCAPTCHA error. Invalid domain for site key. q2a version 1.7

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#187]
reCAPTCHA error. Invalid domain for site key. q2a version 1.7

i delete 1.7 version reCAPTCHA and install old version. Old version normal work.

![default](https://cloud.githubusercontent.com/assets/993795/5690989/8c2d4a48-98da-11e4-8b3e-0b16b2e5799a.png)

**Comment by svivian** [comment]
Strange, it worked fine for me with no problem whatsoever.

Can you go to https://www.google.com/recaptcha/admin and check your domain is there and you have the correct keys?

**Comment by dmvieira** [comment]
Here same error

**Comment by svivian** [comment]
@dmvieira Please provide more information. Have you checked your domain is there as described above?

**Comment by dmvieira** [comment]
It's not working in localhost, but v1.0 works with the same key

**Comment by svivian** [comment]
Are you using `http://localhost/` or a different local hostname (e.g. `http://yoursite/`)? I found that the new reCAPTCHA sometimes doesn't work on the latter. As long as it works on your real site that's all that matters, we can't really do anything about it not working on localhost.

**Comment by dmvieira** [comment]
I'm using localhost.

2015-02-11 15:37 GMT-02:00 Scott <notifications@github.com>:

**Comment by svivian** [comment]
Does it work if you create a standalone page on localhost? i.e. a plain HTML document with

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <div id="qa_captcha_div_1">
	<div class="g-recaptcha" data-sitekey="YOUR KEY"></div>
    </div>

**Comment by dmvieira** [comment]
Yes, it is a flask wtform implementation that can be broken

2015-02-12 14:29 GMT-02:00 Scott <notifications@github.com>:

**Comment by svivian** [comment]
Sorry, I don't understand what you're saying.

**Comment by dmvieira** [comment]
Please see here:
https://flask-wtf.readthedocs.org/en/latest/form.html#recaptcha

This framework implements recaptcha, but I'm getting error with its

2015-02-13 12:35 GMT-02:00 Scott <notifications@github.com>:

**Comment by svivian** [comment]
Sorry I think you're confused. This isn't the repo for reCAPTCHA, this is for Question2Answer, a Q&A platform that has a reCAPTCHA plugin. I think you'll be better off contacting Flask if you're having problems with that.

**Comment by Puvipavan** [comment]
Delete it and register new key. It's worked for me.

**Comment by lneninger** [comment]
Delete it and register new key. It's worked for me, too.

**Comment by tinthenet** [comment]
Delete it and register new key. It's worked for me, too.

**Comment by Hypenate** [comment]
Delete it and register new key. It's worked for me, too.
