### ISSUE TITLE
Too tiny narrow sidebar in FlatSnow Desktop

### ISSUE THREAD

**Issue by amint** [q2a/question2answer#189]
using Official release of qa1.7)

This issue might have already been mentioned by some other means or persons, but just thought to make sure will be addressed.

Open your qa1.7 in a desktop browser and narrow the screen which switched the FlatSnow to mobile view. You will see the side bar gets too squeezed!

PS. to see the side bar scroll all the dawn to the bottom of the page
![temp555](https://cloud.githubusercontent.com/assets/8526622/5711666/0cbb4f34-9a61-11e4-9f59-d7ecb61071e4.PNG)

**Comment by svivian** [comment]
Thanks. You don't need to report bugs here if they were already reported on the Q2A site. I check both sites regularly.
