### ISSUE TITLE
Some fixes for login boxes in RTL mode and the need to address an inconsistency in FlatSnow

### ISSUE THREAD

**Issue by amint** [q2a/question2answer#190]
When you are in RTL mode you still enter your emails and passwords in English, so the input boxes for these two guys has to be LTR.

One solution might be to add the lines below to qa-style-rtl.css
```javascript
.qam-account-items input[type="text"], .qam-account-items input[type="password"] {
    direction:ltr;
}
```
however this would only solve the problem seen in image 1:
![11](https://cloud.githubusercontent.com/assets/8526622/5711706/5da9abfc-9a61-11e4-8c76-288af8c31ff8.PNG)

 For login page however  different class is assigned to the two text boxes with exactly same purpose!
```javascript
input id="emailhandle" class="qa-form-tall-text" type="text" value="" name="emailhandle">
```
![22](https://cloud.githubusercontent.com/assets/8526622/5711748/b3cfafc2-9a61-11e4-8eab-4c0b1fe07528.PNG)

 which my guess is that class could be used in many other places which switchign it back to ltr might create subsequesnt issues.

 
IMHO the clean solution would be to ** assing same ** class to the input text boxes of image 2

**Comment by svivian** [comment]
Just looking into this now. It seems like the best fix is to set input elements to have a direction of "auto". Can you try adding the `dir="auto"` attribute to the input element and let me know if it fixes the issue?

**Comment by amint** [comment]
Thank you, it actually worked !
