### ISSUE TITLE
Feature request: add an URL-scheme that uses only the post ID's

### ISSUE THREAD

**Issue by patricksavalle** [q2a/question2answer#191]
![screen shot 2015-01-15 at 14 08 49](https://cloud.githubusercontent.com/assets/701331/5757886/1ff55318-9cc0-11e4-9adb-c15f0801754f.png)

When post titles are changed, the URL's are changed too. This can be a problem when working with external tools that rely on the URL, like delicious, diigo, Mobbr, browser bookmarks.

It should be possible for administrator to choose a scheme with only the id of the post. The URL's already work with the last segment:

http://www.question2answer.org/qa/42961/why-question2answer-only-supports-20000-issues
http://www.question2answer.org/qa/42961

But some things, like the "canonical" metatag still reflect (of course) the lang URL.

**Comment by pupi1985** [comment]
For feature requests you should start discussions in the QA site. Having said that, the core already supports that feature by setting the question title length to 0. That setting is in **admin/viewing**. Only thing it adds an extra slash at the end but it shouldn't be a problem.

**Comment by patricksavalle** [comment]
Cool. It works :)

**Comment by patricksavalle** [comment]
Personally I think it is a bug to allow URL's to change after the initial posting.

**Comment by svivian** [comment]
What exactly is the problem you have encountered with external tools? The ID number never changes so a link to `/qa/1234/old-title` still works when it's change to `/qa/1234/new-title`.

(Also, the rel=canonical is set to the new one so search engines pick up the correct URL; potentially external tools could do this too.)

**Comment by patricksavalle** [comment]
Is that true? I will test that. I just assumed... which is the mother of all f*ck ups :)
