### ISSUE TITLE
Error theme SnowFlat - mobile preview

### ISSUE THREAD

**Issue by viicen** [q2a/question2answer#199]
Problem errors preview mobile,  

PHP Notice:  Trying to get property of non-object in /home/user/public_html/qa-theme/SnowFlat/qa-theme.php on line 357
PHP Notice:  Trying to get property of non-object in /home/user/public_html/qa-theme/SnowFlat/qa-theme.php on line 120
PHP Notice:  Trying to get property of non-object in /home/user/public_html/qa-theme/SnowFlat/qa-theme.php on line 295
PHP Notice:  Trying to get property of non-object in /home/user/public_html/qa-theme/SnowFlat/qa-theme.php on line 309

**Comment by eboye** [comment]
I'm having these same errors. gam_snow variable should be array, but it seams that it's string in this cases.

**Comment by pupi1985** [comment]
Exactly the code of which commit are you using? Can you try using the latest **dev** branch and check if the error is there too?

**Comment by viicen** [comment]
I have the latest version that I came those errors.

Versión Question2Answer:	1.7.0
Fecha de construcción:	2014-12-28
Última versión Q2A:	 1.7

**Comment by svivian** [comment]
This should have been fixed by #194. If you're still seeing this issue in the latest Github version (dev branch) then let me know and I'll re open the issue.
