### ISSUE TITLE
Create 1.7.0 and 1.7.1 tags

### ISSUE THREAD

**Issue by pupi1985** [q2a/question2answer#200]
Those releases are missing tags. Also note it should correspond to the code people downloaded from the Q2A site as the "latest version". I mean, for example, the 1.7.0 release does not have the JSON polyfill properly placed.

The releases themselves are actually missing too.

**Comment by svivian** [comment]
Thanks, I've tagged 1.7.0.

v1.7.1 is not done yet so I'll leave this open to remind me when it is.

**Comment by svivian** [comment]
Now tagged.
