### ISSUE TITLE
Email Address Confirmation Fatal error

### ISSUE THREAD

**Issue by Laceratus** [q2a/question2answer#201]
I tried using SMTP and without SMTP, error is same: 

Question2Answer fatal error:
Could not send email confirmation

Stack trace:

require() in index.php:27
require() in qa-index.php:183
qa_get_request_content() in qa-page.php:819
require() in qa-page.php:203
qa_send_new_confirm() in confirm.php:50

**Comment by svivian** [comment]
Hi @Laceratus did you ever fix this issue? I think it's probably due to email being set up incorrectly on your server. Check with your host in case they need particular settings for email.
