### ISSUE TITLE
Plugin Compatibility issue with protected properties in theme object

### ISSUE THREAD

**Issue by Towhidn** [q2a/question2answer#207]
on commit 00c12dfc1606dade44fcb1c89056f53478093f75 this code had been changed from
```php
	var	$indent=0;
	var $lines=0;
	var $context=array();
	var $rooturl;
	var $template;
	var $content;
	var $request;
```
to
```php
	protected $indent = 0;
	protected $lines = 0;
	protected $context = array();

	protected $template;
	protected $content;
	protected $rooturl;
	protected $request;
	protected $isRTL; // (boolean) whether text direction is Right-To-Left
```

this will basically make theme object's main properties like $content inaccessible from outside. for example in [widgets](http://http://question2answer.org/modules.php?module=widget), plugin won't be able to access $qa_content and access page content.
changing ```protected``` back to ```var``` will solve this issue.

**Comment by pupi1985** [comment]
How exactly were you referencing the `content` member before changing their visibility to `protected`? Can you provide an example?

Note in widgets you are passed the `qa_content` parameter in the `output_widget` function.

**Comment by Towhidn** [comment]
yes, it seems that using ```$qa_content``` instead of ```$themeobject->content``` can solve this issue. however I still feel safer if this variable were globally accessible through the object. for example while using "$qa_layers" variable.

**Comment by svivian** [comment]
Thanks for bringing this up. I've fixed this to allow access to the `$template`, `$content`, `$rooturl` and `$request` properties. The others remain protected since they shouldn't be accessed outside the class. FYI I used `public` since `var` is the ancient PHP4 way.
