### ISSUE TITLE
Change the js and css versions from relying on QA_VERSION to another option field

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#212]
JS and CSS get the version of q2a assigned. This is however not practical. 

	<link rel="stylesheet" href="./qa-theme/Snow/qa-styles.css?1.7.0">
	<script src="./qa-content/qa-page.js?1.7.0"></script>

I am caching all my JS and CSS files, so every time I am changing some scripts/styles I need to open `qa-include/qa-base.php` find this line and edit the version number:

	define('QA_VERSION', '2.1.120'); // suffix - version for .js and .css requests

Only this way the new files get fetched by the browser. 

I suggest we should have a version number field via `qa_opt()` in `admin/general` which could be easily changed.

<br />

PS: I know that gidgreen uses the js=version to determine the version numbers in the top q2a websites list, http://question2answer.org/sites.php But well, then we have to print this somewhere else, if needed.

**Comment by svivian** [comment]
If you are updating the CSS, you are using your own theme, right? So you can override the `css_name()` function and return something different e.g. `return 'qa-styles.css?'.QA_VERSION.'.120';`

**Comment by q2apro** [comment]
Cool, have not seen this one. What about the `.js` version number?

**Comment by svivian** [comment]
The Javascript is part of core Q2A and not the theme, so it should only be changing when Q2A changes. If you have your own JS files you can add numbers in your theme as you see fit. For example set a class variable in the plugin/theme e.g. `private $theme_version = 120;` then something like `return 'qa-styles.css?'.QA_VERSION.$this->theme_version;`

**Comment by q2apro** [comment]
True, good argument. With my first q2a installation (when I had no idea how the theming works and the plugins) I shifted all JS code into `page.js`. This first site has some tough core hacks and I had not have the time to "transfer" the hacks to my `qa-theme.php`.
