### ISSUE TITLE
Suggestion - Keep page initiation code and it's function library separated

### ISSUE THREAD

**Issue by Towhidn** [q2a/question2answer#213]
in "qa-include/qa-page.php" we have functions that might be needed in other plugins, but having page initiation code at the end of code will cause trouble when programmer wishes to include this file to use it's functions.
I had same problem when developing [Ajax Page Load plugin](https://github.com/Towhidn/Ajax-Page-Loader). I had to create my own clone of this file, only with it's functions which. Now keeping it compatible with all Q2A versions is hard.

I suggest having 2 separate files, 1 for functions and one for initializing page.

**Comment by svivian** [comment]
Which functions in particular do you want? I think all the stuff in there is specific only to loading a page, so should only be called by Q2A when loading a page.

There is an issue with your plugin though: when doing an AJAX request you are skipping some potentially vital initialisation. You only output the `main()` and `sidepanel()` theme functions but there could be extra Javascript, CSS or other content specific to other pages that you are not loading. I don't think there is really any way around that.

**Comment by Towhidn** [comment]
In an ajax plugin(like my example) or another platform integrating with Q2A(by trying to run Q2A through their own platform), being able to call these functions will be necessary. of course developer can just copy the necessary functions but for sake of compatibility, it's better to keep functions and initiation code separately.

about the output function, I'm planning to upgrade plugin to capture page title, static files & inline codes(js,css) and page source("main()" and "sidepanel()") function and load page by parsing each one and replacing them in page. hopefully I'll be able to put some time into add these features in a week or two.

**Comment by Towhidn** [comment]
My suggestion is to put everything after [line 803 in "qa-page.php"](https://github.com/q2a/question2answer/blob/master/qa-include/qa-page.php#L803) in a function. and in [line 183 on qa-index.php](https://github.com/q2a/question2answer/blob/master/qa-include/qa-index.php#L183) after including "qa-page.php" just call that specific function.

**Comment by svivian** [comment]
I've moved the functions from `qa-page.php` into `app/page.php`. So you can include `app/page.php` to get just the functions, or `qa-page.php` to get the initialization too.
