### ISSUE TITLE
When landscape avatar is uploaded then profile shifts to left side.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#216]
There is some issue with snowflat theme that, if a user uploads a landscape avatar instead of a square one then the profile tends to shift towards left side. Have a look at the image. 

![profile](https://cloud.githubusercontent.com/assets/6462850/7216988/cd688bfe-e631-11e4-8a6f-d48ee9348a0f.png)

It would also be good if the uploaded avatar could be cropped and made perfect square in site only so that these issues never happen.

**Comment by svivian** [comment]
I can't reproduce this. The table below the image doesn't change no matter how wide or tall the avatar is.

In your screenshot it looks like there there are two cells in that row of the table with the image in the second one. Whereas for me the top row has one cell spanning both columns.

**Comment by gurjyot** [comment]
Hello scott, here is a live example of this issue. Maybe this can help you.
yoalfaaz.com/user/Pranav

**Comment by svivian** [comment]
Figured it out, it was due to the text in the About field, not the image.

**Comment by gurjyot** [comment]
Thanks for your fix scott... I'll update my site with this soon... :)

**Comment by gurjyot** [comment]
Thanks scott... I finally updated my website and the issue is fixed... :)
