### ISSUE TITLE
qa_get('state') not working for custom plugins and pages

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#219]
I was wondering why my plugin page could not read the URL parameter state: 

	$postpaystate = qa_get('state'); // will return null

As soon as I changed the name to something else, it worked. 

Guess the `state` is used by the core. Not convenient to run into this...

**Comment by pupi1985** [comment]
That's right. This is the line you should blame:
https://github.com/q2a/question2answer/blob/775bd465d6a5a7d76622853aa78f7524dcbbed60/qa-include/qa-page.php#L89

Anyway, I don't think this should be an issue. It is just another undocumented behaviour.

**Comment by svivian** [comment]
You can use the function `qa_get_state()` to get the state. Unless you're doing something funky like Towhidn in #213 the function will be available.

**Comment by q2apro** [comment]
In qa-page.php see function qa_load_state(): 

		$qa_state=qa_get('state');
		unset($_GET['state']); // to prevent being passed through on forms
