### ISSUE TITLE
Styling issue with category widget

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#220]
The questions count is shifting to next category if the category name is too big.

![cate](https://cloud.githubusercontent.com/assets/6462850/7334743/704985d0-ebb9-11e4-935d-26f58ac6f05d.png)

**Comment by svivian** [comment]
I can't reproduce this. Which theme are you using, and which browser are you viewing in?

**Comment by gurjyot** [comment]
I am using snowflat theme and I am using latest version of Google Chrome on Windows 8.1

**Comment by svivian** [comment]
Which version of Q2A are you using? This is what I get:

![category](https://cloud.githubusercontent.com/assets/207887/7442631/bab1d594-f110-11e4-9664-fc7c093d92b1.jpg)

**Comment by gurjyot** [comment]
I am using Q2A v 1.7.1 (which was last updated on FEB 19 in github).

**Comment by svivian** [comment]
Are you able to test the latest version from the dev branch and see if you still have the problem?

**Comment by svivian** [comment]
Still cannot reproduce this. If you can provide a demo page where the problem happens I will reopen the ticket.
