### ISSUE TITLE
Issue related to button displacement when small size pic is uploaded.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#225]
When I upload a small size pic in an answer then the buttons beneath the answer show at an unusual place. Please fix this because this looks very awkward.
 
![bug](https://cloud.githubusercontent.com/assets/6462850/7441008/90769a5e-f0f1-11e4-8a68-423bdb73a7c2.png)

**Comment by svivian** [comment]
Do you have a live example URL?

**Comment by gurjyot** [comment]
Hello scott, thanks for your quick reply. I don't have a live example of it. As we are working on the site and it is in "down for maintenance" status right now.

**Comment by svivian** [comment]
I managed to reproduce the issue and have now fixed it.

**Comment by gurjyot** [comment]
Thanks a lot Scott for such quick response... :)
