### ISSUE TITLE
Can't SnowFlat theme be stretched to take full space on big screens

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#226]
Currently, only menu and footer of SnowFlat theme covers the complete space, but the main area is 1024px wide. But shouldn't it be made to adjust with big screens also.
As my screen width is 1366px, so a lot of space left on both the sides which look awkward and on the other hand most website are now customised to make use of maximum space available.

**Comment by svivian** [comment]
The problem is that the wider you make it, the longer lines of text in people's answers become. Long lines are a known usability issue. The user pages could be a bit wider I guess, since they are two columns.

**Comment by gurjyot** [comment]
Well I have an example, where the answer's lines will remain the same and still the more space can be equipped. 
http://demo.qa-themes.com/cleanstrap/
http://www.voprosof.net/
I think they have increased the size of sidebar which is helping to take on more space.

Secondly, for user pages there are some very decent example which can turn Q2A to a whole new level.
Users Page - No need of sidebar as it is taking a lot of space, and when a visitor visits users page then he has nothing to do with sidebar. So sensible act would be to remove side bar from users page and from all other pages related to users.
Some good examples of users page would be 
http://wp3.in/questions/users/
http://demo.qa-themes.com/cleanstrap/users

Last but not the least. From the start, user's profile structure has not been changed. But now users don't want that old looking simple profile. There is high need for a decent profile which can attract and interact with user. I know third party themes are there for this but we need to know that all developers make their stuff compatible only to their own themes and to Q2A stock themes. So it would be good to make improvement in Q2A snowflat only. And I am focusing more on this because all the other forum softwares have made their profile structure to meet the need for today's user, whether it is BBpress, buddypress, or other. Some decent examples.
https://meta.discourse.org/users/codinghorror
http://wp3.in/questions/user/rahularyan/

I know it is not a feature requesting place, but it is just to club everything and make it noticeable to you. Rest your work is going great and if some changes are possible then these sites can be seen for examples.
