### ISSUE TITLE
Styling issue for "custom message on ask form"

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#227]
I think, the custom message on ask form has not been styled properly. Can this be taken care of. Currently the text looks very small and with no layout at all.
I have not checked other custom messages but it would be good to have a look at those too.

**Comment by svivian** [comment]
That's intentional. The custom message on the ask form is currently styled as a "form note" as it's meant to be a small piece of additional information. It's like the bit in Admin>General where it says "Options with the OK label..."

Same goes for the answer/comment custom messages.

**Comment by gurjyot** [comment]
Yes you are right, it is exactly same to what we have in admin>general section. If its made that way then no issues, on the first look it was not appealing, but now when I see it. I really think its good the way it is there. 
Thanks for your time... :)

**Comment by svivian** [comment]
By the way you can add your own styling to that note with a CSS selector like `.qa-template-ask .qa-form-tall-note { }`
