### ISSUE TITLE
Shouldn't the heading for sidebar widgets be styled same.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#228]
In wordpress, most themes are made such that we use any widget but the heading for all the widgets look the same so that every widget looks the part of the theme only.
But in SnowFlat, every widget is having differently styled heading. Can't this be fixed for every widget (either widgets are from core or from plugins). 
Currently I am using different plugin widget but all their heading are styled differently. 
Even the "All Categories" and "Most Popular Tags" widget headings are styled differently and it looks very awkward.

**Comment by svivian** [comment]
Assuming you're talking about the SnowFlat theme. Do you have an example of different stylings? I see the "All categories" one is different, I think that's because it's a link. All the rest have the same headings.

**Comment by gurjyot** [comment]
Ok I can understand or all categories widget. But all plugin widget show different size and differently styled heading. Can that be fixed? You can see the example below.
![rsz_heading](https://cloud.githubusercontent.com/assets/6462850/7452981/0263bb4c-f282-11e4-9bbf-f886f0d3eb4a.png)

**Comment by svivian** [comment]
Those are all external plugins outside our control. What is the HTML for those sections? They should be using `<h2>` tags.
