### ISSUE TITLE
When i clicked Admin Panel Server Gets Down For a while

### ISSUE THREAD

**Issue by mohamedmusthafac** [q2a/question2answer#230]
Here is the error i got in console

Here mydomain is my website name

Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/index.php/url/test/%24%26-_~%23%25%5C%40%5E%…%5B%60%27%3B%3A%7C%22.%7B%7D%2C%3C%3E%3F%23+%CF%80%C2%A7%C2%BD%D0%96%D7%A9 Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/?qa=url/test/%24%26-_%7E%23%25%5C%40%5E%2A%2…%5B%60%27%3B%3A%7C%22.%7B%7D%2C%3C%3E%3F%23+%CF%80%C2%A7%C2%BD%D0%96%D7%A9 Failed to load resource: the server responded with a status of 403 (Forbidden)
http://www.mydomain.com/index.php?qa=url&qa_1=test&qa_2=%24%26-_%7E%…%5B%60%27%3B%3A%7C%22.%7B%7D%2C%3C%3E%3F%23+%CF%80%C2%A7%C2%BD%D0%96%D7%A9 Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/url/test/qa-theme/Snow/qa-styles.css?1.7.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/url/test/qa-content/jquery-1.11.2.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/index.php/url/test/qa-theme/Snow/qa-styles.css?1.7.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/?qa=url&qa_1=test&qa_2=%24%26-_%7E%23%25%5C%…%5B%60%27%3B%3A%7C%22.%7B%7D%2C%3C%3E%3F%23+%CF%80%C2%A7%C2%BD%D0%96%D7%A9 Failed to load resource: the server responded with a status of 403 (Forbidden)
http://www.mydomain.com/url/test/qa-content/qa-page.js?1.7.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mydomain.com/index.php/url/test/qa-content/qa-page.js?1.7.1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
http://www.mydomain.com/index.php/url/test/qa-content/jquery-1.11.2.min.js Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by svivian** [comment]
I answered your question on the [Q2A site here](http://www.question2answer.org/qa/45185/server-gets-down-when-i-enter-the-admin-panel). Can't you configure your server to not ban you?
