### ISSUE TITLE
Menu of SnowFlat is not enough to accommodate all the links

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#231]
With just the normal links of Q2A, the menu fits well. But as we start increasing some links like, 4 pages of blog plugin, rules page, events page, announcements page, faq, then the top menu is not enough to accommodate all links there.
The footer menu is not good to showcase important pages that we want our users to see. 

To solve this first I thought to suggest for a secondary menu where we can list some pages. But then, a better solution would be to shift menu to left side of the website. That way we can add as many links and that too without even tempering the looks of the website.
If this is done, then it would be much easy to place search bar at the top and even the notification icon on the top bar (which would be implemented in future). 
It would be much like Facebook style where menu is in side and all the other thing are on top bar.

This would also solve the issue of space going vacant on large screens (issue #266). 

It can look much like this. http://postimg.org/image/687arbw2n/

**Comment by svivian** [comment]
The links are "accommodated", but they drop to the next line. If you want more at the top you could add your own set of links to "Custom HTML at top of every page" in Admin > Layout.

But putting the navigation on the left like your screenshot would be turning it into a different theme. And I don't think there is enough room for the menu to fit well at the side there.

**Comment by gurjyot** [comment]
Yes that's the issue, I'd links are mor then menu drops and a bit blue band of menu starts to show. This completely ruins the style of website. 

And still we need some more space to showcase more links...
