### ISSUE TITLE
Gif images uploads but do not show the effect in user avatar 

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#233]
I tried to upload a gif user avatar and it did uploaded. But it uploaded as a normal image and not showing any movements. 
Is Q2A still not ready for gif type images? 
This is just a normal query as this is the first time I tried for gif images.

**Comment by svivian** [comment]
The problem is that all images are resized in Q2A, and resizing animated GIFs is not supported by the GD image library. I don't see any way around that for Q2A, unfortunately.

**Comment by gurjyot** [comment]
That's all I needed to know Scott... Thanks for your answer... :-)
