### ISSUE TITLE
not ipv6 ready

### ISSUE THREAD

**Issue by toby78** [q2a/question2answer#238]
The script / database is not ipv6 ready. If a user comes along with an ipv6 address, it won't work.

Todos:

- change loginip and writeip to BINARY(16) instead of int(10)
- if ipv4 convert to ipv6 
- change all places in the code that might be changed as well.

**Comment by svivian** [comment]
Hi @toby78 I've closed your related pull request due to no response. If you're able to send a new PR with just the IPv6 changes it would be appreciated, thanks.
