### ISSUE TITLE
Bug: Whenever someone registers to my website then Database query failed is showing

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#241]
Previously everything was working fine but from some days this problem is coming on my website that whenever someone registers then a warning starts to show.

A Question2Answer database query failed when generating this page.

A full description of the failure is available in the web server's error log file.

How to fix this??

Updated
Ok now I have tried to undo everything that I have applied on my website and came to know that, when ever I apply an extra field on users page (like Full Name) then this error starts to show. Can this be fixed?

**Comment by pupi1985** [comment]
Firstly, as the error itself says, add the full description of the error from the error log file.
Secondly, same as always: are you receiving this error in a clean (without plugins) installation using the classic theme?

**Comment by gurjyot** [comment]
I have checked description in error log file. The error log file says this.

[23-May-2015 12:55:13 America/Chicago] PHP Question2Answer MySQL query error 1048: Column 'userid' cannot be null - Query: REPLACE qa_userprofile (title, content, userid) VALUES ('full-name', 'liana samuel', NULL)

But this error is only displaying when I set an "Extra field on users page (like Full Name). 

Secondly if I remove this extra field then the error doesn't show but the user is redirected to homepage without even showing the message to confirm his/her email. #242

**Comment by svivian** [comment]
To clarify, does the error occur when they register, or when they edit their profile? Or both?

Are you using the standard users in Q2A or are you using single sign-on?

**Comment by gurjyot** [comment]
It is happening only when a user registers. But there is a catch, it happens when I have enabled "Extra field on users page" (like Full Name).
If this field is not enabled then the user is just redirected to homepage and he registers successfully.

**Comment by pupi1985** [comment]
I would remove all plugins and retest. It is likely that a filter module is messing with the data before it is saved.

**Comment by gurjyot** [comment]
I did removed all the plugins one by one to see which plugin is doing this shit. q2a-registeration-blocker is the plugin to blame. Even if I deactivate that then also this keeps on showing that message but if I completely remove it from my hosting then my website works perfect.

**Comment by pupi1985** [comment]
I guess that hit the nail. Any reason for this to stay open?

**Comment by gurjyot** [comment]
Well I really don't know, the feature of this plugin is good but the reason because of which it is showing that error is unknown to me.

**Comment by amiyasahu** [comment]
this bug has been fixed in the plugin
