### ISSUE TITLE
error with guest posts & external database integration

### ISSUE THREAD

**Issue by toby78** [q2a/question2answer#244]
The following happens with you are using an external user database, allow guest questions and ask a question with the same name as an existing users:

[Sun May 24 20:18:09 2015] [error] [client 149.126.78.65] PHP Question2Answer MySQL query error 1452: Cannot add or update a child row: a foreign key constraint fails (`qanda`.`qa_posts`, CONSTRAINT `qa_posts_ibfk_1` FOREIGN KEY (`userid`) REFERENCES `qa_users` (`userid`) ON DELETE SET NULL) - Query: INSERT INTO qa_posts (categoryid, type, parentid, userid, cookieid, createip, title, content, format, tags, notify, name, created) VALUES (8, 'Q', NULL, '508815', NULL, INET_ATON('\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0]\x86\xf3U'), 'This ijust a qeustion from real me', 'what happens if someone else asks in my name?', '', 'question', '@', NULL, NOW()),

**Comment by pupi1985** [comment]
When using external users, you can't violate a constraint that is only created when using internal users... unless you've created the tables using internal users and then switched to external. If you could start from scratch that would be probably the best way to go. If it is already too late you can take a look at this [function](https://github.com/q2a/question2answer/blob/02f8514d88d886f878e7eb3ceedde2d56dbdfdd2/qa-include/db/install.php#L60) to see what are the operations you'll need to undo.

**Comment by toby78** [comment]
I think for external users on donut theme, the following is required in qa-donut-utils.php

if (!defined('donut_get_user_data')) {
	function donut_get_user_data($handle){
		$userid = qa_get_logged_in_userid();
		$user = array();

					$u_rank = qa_db_select_with_pending(qa_db_user_rank_selectspec($userid,true));
			$u_points = qa_db_select_with_pending(qa_db_user_points_selectspec($userid,true));
			
			$userinfo = array();
			$user_info = get_userdata( $userid );
			$userinfo['userid'] = $userid;
			$userinfo['handle'] = $handle;
			$userinfo['email'] = $user_info->user_email;
			
			$user[0] = $userinfo;
			$user[1]['rank'] = $u_rank;
			$user[2] = $u_points;
			$user = ($user[0]+ $user[1]+ $user[2]);

        $user['account'] = qa_db_select_with_pending( qa_db_user_account_selectspec($userid, true) );
        $user['rank'] = qa_db_select_with_pending( qa_db_user_rank_selectspec($userid) );
        $user['points'] = qa_db_select_with_pending( qa_db_user_points_selectspec($userid) );

        $user['followers'] = qa_db_read_one_value( qa_db_query_sub('SELECT count(*) FROM ^userfavorites WHERE ^userfavorites.entityid = # and ^userfavorites.entitytype = "U" ', $userid), true );


        $user['following'] = qa_db_read_one_value( qa_db_query_sub('SELECT count(*) FROM ^userfavorites WHERE ^userfavorites.userid = # and ^userfavorites.entitytype = "U" ', $userid), true );

**Comment by svivian** [comment]
Sounds like this is a problem with an external theme, so you should suggest your fix to the author of that theme.

**Comment by nightrider77** [comment]
I use latest stock version without any modifications, but external auth enabled.
No one can post any question, query results in error

`#1452 - Cannot add or update a child row: a foreign key constraint fails (`qa_db`.`qa_posts`, CONSTRAINT `qa_posts_ibfk_1` FOREIGN KEY (`userid`) REFERENCES `qa_users` (`userid`) ON DELETE SET NULL)`

Because qa_users table is empty.

It seems to me, qa_get_logged_in_user() needs some additional code to add a local Q&A user when checking its external authentication.
