### ISSUE TITLE
PHP log file show error. eval()'d code on line 87

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#245]
My error log file i show this line error code.
This error coe show after : Partially hide comments if more than: 
Notice: Undefined index: raw in /var/www/szh/data/www/szh.kz/qa-include/qa-base.php(591) : eval()'d code on line 87
![3](https://cloud.githubusercontent.com/assets/993795/7837704/8dab16e8-04aa-11e5-89e6-dd63bf9ba987.png)
![45](https://cloud.githubusercontent.com/assets/993795/7837705/8dcc539e-04aa-11e5-9ce8-9d14cad796f7.png)

and this error.
[Wed May 27 19:56:02 2015] [error] [client 66.249.75.80] PHP Notice:  Undefined index: content in /var/www/szh/data/www/szh.kz/qa-include/qa-base.php(591) : eval()'d code on line 15

**Comment by svivian** [comment]
If that's in eval'd code it sounds like an issue with a plugin or theme. Could you try changing the theme and seeing if the error still occurs? And then try removing each plugin in turn.

**Comment by svivian** [comment]
@yerbol89 any luck with this issue?

**Comment by yerbol89** [comment]
@svivian i found this plugin create error log.
I use my site block editing plugin. This plugin create error. How i fix this code. Please help.

 class qa_html_theme_layer extends qa_html_theme_base {

    function q_view_buttons($q_view)
    {
        $created = $q_view['raw']['created'];
        $delay_time = qa_opt('q2am_block_editing_minutes');

        if (!empty($q_view['form'])) {
            $this->output('<div class="qa-q-view-buttons">');

            $exclude_ids = str_replace(' ', '', qa_opt('q2am_block_editing_userids'));
            $useids = explode(',', $exclude_ids);

            $user_level_permission = qa_opt('q2am_block_editing_moderators') ? qa_get_logged_in_level() < QA_USER_LEVEL_MODERATOR : qa_get_logged_in_level() < QA_USER_LEVEL_ADMIN;

            if (qa_opt('q2am_block_editing_enable') && $user_level_permission && !in_array(qa_get_logged_in_userid(), $useids)) {
                if ($created <= strtotime('-' . $delay_time . ' minutes')) {
                    if (qa_opt('q2am_block_editing_edit')) unset($q_view['form']['buttons']['edit']);

                    if (qa_opt('q2am_block_editing_hide')) {
                        unset($q_view['form']['buttons']['hide']);
                        unset($q_view['form']['buttons']['close']);
                    }
                }
            }

            $this->form($q_view['form']);
            $this->output('</div>');
        }
    }

    function a_item_buttons($a_item)
    {
        $created = $a_item['raw']['created'];
        $delay_time = qa_opt('q2am_block_editing_minutes');

        if (!empty($a_item['form'])) {
            $this->output('<div class="qa-a-item-buttons">');

            $exclude_ids = str_replace(' ', '', qa_opt('q2am_block_editing_userids'));
            $useids = explode(',', $exclude_ids);

            $user_level_permission = qa_opt('q2am_block_editing_moderators') ? qa_get_logged_in_level() < QA_USER_LEVEL_MODERATOR : qa_get_logged_in_level() < QA_USER_LEVEL_ADMIN;

            if (qa_opt('q2am_block_editing_enable') && $user_level_permission && !in_array(qa_get_logged_in_userid(), $useids)) {
                if ($created <= strtotime('-' . $delay_time . ' minutes')) {
                    if (qa_opt('q2am_block_editing_edit')) unset($a_item['form']['buttons']['edit']);

                    if (qa_opt('q2am_block_editing_hide')) unset($a_item['form']['buttons']['hide']);
                }
            }

            $this->form($a_item['form']);
            $this->output('</div>');
        }
    }

    function c_item_buttons($c_item)
    {
        $created = $c_item['raw']['created'];
        $delay_time = qa_opt('q2am_block_editing_minutes');
        
        
        if (!empty($c_item['form'])) {
            $this->output('<div class="qa-c-item-buttons">');
            
            $exclude_ids = str_replace(' ', '', qa_opt('q2am_block_editing_userids'));
            $useids = explode(',', $exclude_ids);

            $user_level_permission = qa_opt('q2am_block_editing_moderators') ? qa_get_logged_in_level() < QA_USER_LEVEL_MODERATOR : qa_get_logged_in_level() < QA_USER_LEVEL_ADMIN;

            if (qa_opt('q2am_block_editing_enable') && $user_level_permission && !in_array(qa_get_logged_in_userid(), $useids)) {
                if ($created <= strtotime('-' . $delay_time . ' minutes')) {
                    if (qa_opt('q2am_block_editing_edit')) unset($c_item['form']['buttons']['edit']);

                    if (qa_opt('q2am_block_editing_hide')) unset($c_item['form']['buttons']['hide']);
                }
            }
            
            $this->form($c_item['form']);
            $this->output('</div>');
        }
    }


}

**Comment by svivian** [comment]
I see you have a commented line to print out the `$q_view['raw']` variable. What happens when you uncomment that? What about printing `$q_view` and the same for the answer/comment functions.

**Comment by yerbol89** [comment]
@svivian i'm not expert for PHP coding. If you know the code can change the prompt. Thanks!

**Comment by svivian** [comment]
Since this is an issue with a plugin it's probably best you ask on the Q2A site, you should get better answers there. Thanks.
