### ISSUE TITLE
Great idea that will turn this into a 2 in 1 system

### ISSUE THREAD

**Issue by artur99** [q2a/question2answer#249]
A few weeks ago i searched for a very simple version of forum with no categories, with a great design.
I found Discourse, but it required Ruby on rails and lots of other things that I couldn't afford. After a few days of research I found this system: question2answer, but it was not what i was looking for... I was looking for something exactly like this, but kind of subject2answer. I downloaded and saw that I can edit the language file, and I started replacing the "question" word into "subject".

So my idea is this: What if you would provide 2 version of translations? One as it is right now(questions and answers), and another one that will be a simple forum system(subjects/topics and answers)

Well I did a half of the translation into Romanian for my version - the one with "subject/topic2answer"  :smile:

**Comment by q2apro** [comment]
Please post suggestions here: http://www.question2answer.org/qa/

This repo is mainly for bugs or important updates / urgent ideas. 

https://github.com/q2a/question2answer/blob/master/CONTRIBUTING.md

**Comment by svivian** [comment]
Funny enough I've looked into this myself. However, it's unlikely we'll ever provide "official" translations/plugins for this. But feel free to discuss on the Q2A site.
