### ISSUE TITLE
Redirect URL if slug is incorrect

### ISSUE THREAD

**Issue by patricksavalle** [q2a/question2answer#253]
While debugging an encoding issue, I noticed the software does not notice when invalid url's are entered:

This page:
http://mathsgenius.co.za/qa/961/solve-%24x-2-2x-1-0%24

Can also be reached on:
http://mathsgenius.co.za/qa/961/solve-?x-2-2x-1-0?

And: 
http://mathsgenius.co.za/qa/961/solve-&%24x-2-2x-1-0%24

Probably because the 3rd segment of the URL is ignored. Might want to do some checking.

**Comment by q2apro** [comment]
q2a focuses on the post id, in your example `961`. Everything behind can be arbitrary.

q2a uses the canonical tag to tell search engines the correct URL.

Click the title of the post to see the correct URL.

**Comment by svivian** [comment]
q2apro is correct, the 'slug' is ignored - it's mainly there for SEO and UX purposes. However, I guess it would be useful to redirect the user if the slug is incorrect.
