### ISSUE TITLE
Admin option instead of hacking qa-page-question-view.php - $rules for questions

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#256]
In function qa_page_q_post_rules() I still need to do a huge essential core hack. It began with: [How to disable option to edit question after certain time span?](http://www.question2answer.org/qa/13137/disable-option-question-after-certain-hacking-page-question) in March 2012. Now I got even more rules. 

[Gidgreen proposed](http://www.question2answer.org/qa/12375/how-to-forbid-user-to-edit-his-own-question): 

> plugin which overrides the function qa_page_q_post_rules(...) - first it should call the base function to get the default result for $rules, and then set $rules['editable']=false in the cases it wants, before returning $rules.

In my point of view, this is absolutely a must-have option for all q2a forums.

Here is my full hack that starts after line `$rules['followable']=($post['type']=='A') ? qa_opt('follow_on_as') : false;`: 

	/* START q2apro hack */
		// users are never allowed to hide posts
		$rules['hideable'] = false;
		
		// users are not allowed to edit posts after x min
		$timestamp = time();
		// edit time frame: 5 min (300s) for questions/comments + 20 min (1200s) for answers
		if($post['type']=='A') {
			$rules['editable'] = $rules['editbutton'] = $rules['isbyuser'] && ($timestamp - $post['created'] < 1200);
		}
		else {
			$rules['editable'] = $rules['editbutton'] = $rules['isbyuser'] && ($timestamp - $post['created'] < 300);
		}

		// admin has all rights
		$level=qa_get_logged_in_level();
		if ($level>=QA_USER_LEVEL_ADMIN) {
			$rules['editable'] = $rules['editbutton'] = $rules['hideable'] = true;
		}
		else if ($level>=QA_USER_LEVEL_EXPERT) {  
			// are allowed to edit own answers and all questions
			// time frame: allow edit after 5 min and up to 7 days (604800 sec), can edit his own answer immediately
			$rules['editable'] = $rules['editbutton'] = 
				($rules['isbyuser'] || $post['type']=='Q') // can edit his own post and all questions
					&& ( ($timestamp - $post['created'] > 300) || $rules['isbyuser'] ) // can edit question just after 5 min OR his own answer immediately
						&& ($timestamp - $post['created'] < 604800 || $level>=QA_USER_LEVEL_EDITOR) // do not allow edit of posts older than 7 days, editor can
							&& (!isset($post['closedbyid']) || isset($post['closedbyid']) && ($rules['isbyuser'] || $level>=QA_USER_LEVEL_EDITOR)) // post is not closed, if closed it must be of user to let him edit or editor level
								&& ($post['userid']!=1); // never allow question-posts by admin to be edited
			// not allowed to reopen questions
			$rules['reopenable'] = false; 
		}
		
		// experts can close questions
		$rules['closeable'] = $level>=QA_USER_LEVEL_EXPERT && !$rules['closed']; // && ($timestamp - $post['created'] < 1209600) ); // within 7 days

		// special rights for certain handpicked users
		if($userid==637 || $userid==134) {
			$rules['editable'] = $rules['editbutton'] = $rules['hideable'] = true;
			$rules['clearflaggable'] = ($post['flagcount']>=(@$post['userflag'] ? 2 : 1));
		}

		// do not show retag button as it does the same as edit button
		$rules['retagcatbutton'] = false;
	
	/* END core hack */

Would be cool if this logic can go into the core (of course, the times set above should be variables).

**Comment by svivian** [comment]
Why can't you do as Gideon suggests and make an override instead of core hack?

**Comment by q2apro** [comment]
This function is a core function, so when I override it and new stuff is added, it will not be up-to-date anymore.

**Comment by svivian** [comment]
It should be fine. What Gideon suggested is to entend the function and add your stuff afterwards, not completely replace the function. Check out the [docs for overrides](http://www.question2answer.org/overrides.php) especially the part about calling to the base function.

So you can do something like

    function function qa_page_q_post_rules($post, $parentpost=null, $siblingposts=null, $childposts=null)
    {
    	// get base rules
        $rules = qa_page_q_post_rules_base($post, $parentpost, $siblingposts, $childposts);

        // do your logic here
        $rules['editable'] = false;

        return $rules;
    }

**Comment by q2apro** [comment]
Finally, it worked. This for the hint that I do not need to *override* the entire function!

For all: 
https://github.com/q2apro/q2apro-userrules

**Comment by drorp** [comment]
Is there anything that could work today?
