### ISSUE TITLE
Hidden inputs should be more customizable

### ISSUE THREAD

**Issue by pupi1985** [q2a/question2answer#26]
Currently hidden fields are displayed this way by default:
```php
function form_hidden_elements($hidden) {
  if (!empty($hidden))
    foreach ($hidden as $name => $value)
      $this->output('<input type="hidden" name="'.$name.'" value="'.$value.'"/>');
}
```
However, this disallows customization as well as proper JavaScript access by ID. The `$hidden` array is just a key-value array where value is the input value itself. Adding a `tags` key is not straightforward and would require to change some other functions and will be backwards incompatible.

Having said that, I think it is the way to.

**Comment by svivian** [comment]
Looked into this (finally). We can't add hidden fields to the usual 'fields' array in forms because they would get output in a (blank) table row.

But I've made a change to the `qa_html_theme_base::form_hidden_elements` method so that if `$value` is an array it treats it like the other standard forms. Like this:

	'hidden' => array(
		'code' => array(
			'tags' => 'name="code"',
			'value' => qa_get_form_security_code('account'),
		),
	),

Makes more sense I think. See the two examples in `pages/account.php` at e9de47f.

**Comment by svivian** [comment]
Incidentally, there are a LOT of instances of `'tags' => 'name="fieldname"'` in the code, those could probably be replaced with a `'name' => 'fieldname'` syntax for simplicity.

**Comment by pupi1985** [comment]
I see what you mean about them being output in a table row. However, I didn't mean to add it to the `switch` statement that outputs each type of field but rather output them in the same order as they're today. This would mean not letting them to reach the `switch` statement earlier and then output them after the table. For example:

You could create the array like this:
```php
'fields' => array(
	'age' => array(
		'tags' => 'name="age_field" id="age_id"',
		'type' => 'hidden',
		'value' => 30,
	),
```

The `foreach` in `form_fields` function would look like this in order to omit the hidden fields:
```php
foreach ($form['fields'] as $key => $field) {
	if (!isset($field['type']))
		break;
	if ($field['type'] === 'hidden')
		break;
	$this->set_context('field_key', $key);
	if ($field['type'] === 'blank')
		$this->form_spacer($form, $columns);
	else
		$this->form_field_rows($form, $columns, $field);
}
```
Then it's a matter of playing a bit with `form_hidden` and `form_hidden_elements` and all the places they're called. Does it make sense?

**Comment by svivian** [comment]
Yes, I understand what you are saying. I think overall it makes more sense to keep the hidden fields separate, as they are a special input type. Adding the check in the foreach makes the code a little convoluted IMO. (Also theme developers are more likely to have overridden the `form_fields` method than the `form_hidden` method, which could mess up output.)
