### ISSUE TITLE
Correct pages/user-answers.php to display answer links and answer votes.

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#260]
From http://www.question2answer.org/qa/45916/each-question-link-username-answers-should-point-the-answer

A user sees his answer list and clicks the title, instead of coming to the answer the question opens "on top". If there are 100 answers it is hard to find your own answer.

The question titles in the /answers/ list should definitely be linked to the answer, i.e. adding the show parameter in the end.

Furthermore, the [votes displayed are not for the answer](http://www.question2answer.org/qa/23243/count-answers-certain-should-display-votes-answer-question) but for the question. If I open an answer list and I see "3 upvotes" I immediately think that those upvotes are for the answer given, because I am on the answers list of user x. (Even @svivian voted for this.)

I checked `user-answers.php` and saw that `qa_other_to_q_html_fields()` is used for the questions list. There it seems that we cannot specify an anchor for the answer link. Also the votes for the answers cannot be fetched. → Do we need a new function here?

**Comment by svivian** [comment]
Answer votes are currently displayed, don't remember exactly when that was fixed but it was a while back. I don't think updating the question link is possible. The only way would be updating it for *every* question that has "answered" as the last activity, but that would add inconsistency to the other question lists (e.g. the home page).
