### ISSUE TITLE
In qa-lang-main.php file there is two strings doesn't fit in PHP_ARRAY format. 

### ISSUE THREAD

**Issue by markosu** [q2a/question2answer#261]
There are two strings qa-lang-main.php that isn't in PHP_ARRAY format. Transifex service gives error about wrong format.
Strings:
		'date_day_min_digits' => 1, // 1 or 2
		'date_year_digits' => 4, // 2 or 4

Example about right format:
'date_format_other_years' => '^day ^month, ^year',

**Comment by svivian** [comment]
What do you mean by "isn't in PHP_ARRAY format"? Those elements are valid array syntax, they are not translation strings per se but variables for date formatting. And Q2A isn't using Transifex.

**Comment by markosu** [comment]
I was thinking that file isnt PHP_ARRAY format if there is strings without quotation marks. Sorry about that.
Ok, I didn't get error in Transifex after adding quotation marks for strings '1' and '4'.
Thanks for advice.
