### ISSUE TITLE
If we add an extra field for registration page then that should show before privacy policy check.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#263]
I have added an extra field for user and also for registration page (Full Name) but that shows after privacy policy check. Normally when a user registers on a website then privacy policy check is served at the end of all the input fields. 
It would be way better to shift the privacy policy field at the last or just above the recaptcha.

**Comment by pupi1985** [comment]
Makes sense to me. To achieve that result you can modify the core this way: https://github.com/q2a/question2answer/pull/264

**Comment by sama55** [comment]
+1 gurjyot. I think so too. Further more, since this feature is not scalable, it is not suitable as a feature of the core. Generic features such as check-box, radio-button and select-box may be provided.
Example by my plugin:
http://askive.cmsbox.jp/register
