### ISSUE TITLE
reCAPTCHA problem ''Please complete the anti-spam verification''

### ISSUE THREAD

**Issue by hypermax** [q2a/question2answer#265]
Hello all  

I have a problem with reCAPTCHA  

All my settings are correct but when i enable the reCAPTCHA verification , the registration, anonymous posts ... can't works 

when i write a anonymous post ( or new registration ... ) primary i get green badge anti spam verification like this :  

![recap3-4bcacf9](https://cloud.githubusercontent.com/assets/7949941/8391801/b7b33f76-1cc7-11e5-8eaa-51ae4aefacfa.png)

but when i click Add answer  the post can't published and i get this error  ''Please complete the anti-spam verification'' 

![recap4-4bcad50](https://cloud.githubusercontent.com/assets/7949941/8391805/da791cc4-1cc7-11e5-9bd3-92e6b3e1e74b.png)

I have configurate my web site correctly 

![recap1-4bcad66](https://cloud.githubusercontent.com/assets/7949941/8391806/0134f4e6-1cc8-11e5-8bc4-372975163c12.png)

![recap2-4bcad75](https://cloud.githubusercontent.com/assets/7949941/8391807/06062f94-1cc8-11e5-93da-e42fe48dfc71.png)

Q2A version: 1.7.1 Latest with snow flat theme   live web site

Please help me to fix this

**Comment by svivian** [comment]
I answered on your Q2A question. Is reCAPTCHA set up properly for your domain?
