### ISSUE TITLE
Remove brackets from new "closed" notice in question title on question page

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#268]
See http://www.question2answer.org/qa/45978/how-to-remove-new-closed-notice-question-title-question-page

Those lines are problematic, public [function title()](https://github.com/q2a/question2answer/blob/master/qa-include/qa-theme-base.php#L734):

		// add closed note in title
		if (!empty($q_view['closed']))
			$this->output(' ['.$q_view['closed']['state'].']');

Even if I unset `$q_view['closed']['state'])` from my qa-theme.php, the `[]` are still showing up.

Needs another way of handling, e.g. just check: 

		if (!empty($q_view['closed']['state']))

Then the $q_view['closed']['label'] survives for function q_view_closed().

**Comment by svivian** [comment]
Fixed by checking for `$q_view['closed']['state']`. Thanks.
