### ISSUE TITLE
Please add Source Editing Area and delete text format forcePasteAsPlainText

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#269]
@svivian Please add https://github.com/q2a/question2answer/tree/master/qa-plugin/wysiwyg-editor 
config.extraPlugins = 'sourcearea'; and auto delete text format forcePasteAsPlainText plugins config.forcePasteAsPlainText = true;
I'm add code but sourcearea and forcePasteAsPlainText dont work.
Thanks.

**Comment by svivian** [comment]
To customise CKeditor please use the `build-config.js` file as described in CUSTOMIZE.md. I don't think those options are suitable for the core plugin. Thanks.

**Comment by yerbol89** [comment]
@svivian Is it possible to add these functions.
http://www.question2answer.org/qa/42919/how-i-add-source-editing-area-for-wysiwyg-editor?show=42922#a42922
and
http://www.question2answer.org/qa/42812/editor-ckeditor-wysiwyg-delete-format-forcepasteasplaintext?show=42818#a42818
