### ISSUE TITLE
Error in sending email confirmaton. Any one Please help.

### ISSUE THREAD

**Issue by ranjanchris** [q2a/question2answer#270]
Question2Answer fatal error:
Could not send email confirmation

Stack trace:

require() in index.php:27
require() in qa-index.php:183
qa_get_request_content() in qa-page.php:819
require() in qa-page.php:203
qa_send_new_confirm() in confirm.php:50

**Comment by svivian** [comment]
This error is usually due to incorrect email settings for your provider. Do you have all the required details set in the admin options?
