### ISSUE TITLE
Shouldn't character limit be increased from 8000 to 16000 in Q2A 1.8

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#277]
It is high time that character limit should be increased or just doubled in Q2A 1.8
Many of my users have complained that their answers not even consist of 8000 characters. Its even demanded man times before but never implemented so maybe this is the time is should be done.

**Comment by svivian** [comment]
Thanks for the suggestion, but the GitHub issues are for reporting bugs, not feature requests.

**Comment by gurjyot** [comment]
Okh, I got it, but if I ask this feature request on Q2A will you answer? 
Because if not then there is no use to ask it Q2A as only one person can implement this and that is you. You are on Github and we should ask feature requests on Q2A where you rarely show up.

We should seriously discuss that for what purpose should Q2A be used now? Only for feature requests!!  Because everything else is going without involving Q2A community at all.

**Comment by svivian** [comment]
I'm on the Q2A site nearly every day. I don't post as much as I used to because there are a lot of other people in the community who can answer people's questions well.

The problem with having feature requests here is that the issue tracker will get clogged up with tons of posts and it will be difficult to sort through them. I suppose I haven't replied to many FRs recently but look at [my  answers](http://www.question2answer.org/qa/user/Scott/answers) and I've replied to a lot.

**Comment by gurjyot** [comment]
Maybe what you are saying is right, but not completely right. First of all you said "there are a lot of people to answer questions". Well those lot of people are not seen on Q2A for more than 5 months and only 2 or 3 people are left in communitu which are answering anything. 
Secondly, we ask for feature request so that core team can implement those but if you miss them to read then whats the point of even asking them anymore.

The point is very simple but I don't know why core development people are not understanding. Q2A is losing its reputation in the market. Complete Q2A QA website community is empty except 3 or 4 people on board.
Old users have left it and new ones are not sticking on it and still you think everything is going good. 
Only advice from my side would be, start participating in Q2A QA site more and more otherwise Q2A will be history before we could even say it good bye.
I hope you understand what I meant.

**Comment by svivian** [comment]
> only 2 or 3 people are left in communitu which are answering anything.

Honestly it's always been like that. First it was just Gideon, then it was me and NoahY, now there is me and pupi1985 and several others.

> but if you miss them to read then whats the point of even asking them anymore.

I understand what you're saying, but if FRs are posted here instead then we have the exact same problem, too many posts and I can't handle them all.

> Q2A is losing its reputation in the market.

What market? And what makes you say this? Where are you seeing this reputation loss?

**Comment by gurjyot** [comment]
Scott I'll answer each and every question or point that I raised previously. But before that, I just need to say thank you for being so patient from that election thing till now.
Now, market is the people who are using that. The time when I joined Q2A, lot of users used to be on community and you also used to visit is regularly (pupi1985 hasn't started answering at that time). But slowly all went away or shifted to different software. Some of them used to visit my site so I asked them that what happened and why they are not coming to Q2A, that time they said that they are loosing interest in Q2A. Q2A is interesting but not organised and users are still leaving it. This were their reactions, than's why I said that it is loosing reputation.

Now what I really want to say is, if you don't want a team for Q2A then that's ok. But then you will have to do much more then what you are doing now. Development is just one part, you'll need to be active in community regularly (which you just started), you would need to promote Q2A both socially and through word of mouth, you also have to go through all the testing work alone (which I think you are doing very well). So basically, you are doing two things but leaving the two things straight up the alley.
Activity in community and promotion is what needs to be taken care of if you want Q2A to really grow.
Since you have started Q2A dev on github, you stopped visiting Q2A and that's what made Q2A community so much offensive as they felt that they were ignored. You never came to answer or to tell the development work you have done or to ask communities opinion on something.
I can give you many examples, where devs kept development work second but community first. That way the community always grew and even if they got late in development work, they are not forced to be quick.
So what I can suggest is, please change your working style. Keep Q2A community first and its development second. This way the community will always grow and that will bring new users and devs who can actually help you in development work. If this continued for sometime, there maybe a chance that you won't have to write a single line of code but other devs will contribute everything, but this can only be done by you giving priority to community.

Now how you can give priority to community?
There are some ways which can really help.
1. Answer to questions (everyday)
2. Make a separate roadmap page on Q2A
3. Update the community with development work every 15 days
4. Take the help of community on various opinion based questions
5. Motivate them to help in development
6. Change Q2A QA theme to SnowFlat

For opinion based question I think I should be more clear. As I always demand a Contact Us page and you say that Send Feedback page is there. Now there is no end that I will stop asking this again and again, but you can ask this in community that what users actually want, a Feedback page or Contact Us page. Same can be done for "User avatar dropdown in SnowFlat", whether there should be both avatar and username or just an avatar will look good. I remember that, when Jatin was building that theme you came to check that and all of a sudden you made the decision of changing user dropdown without actually asking or consulting the community (after all we have to use that on our websites, so our opinion should matter).

I know these things are little too much to be done just by you, but you are the leader now. We all can help you but only you can lead the community. If you leave the community at one place and keep on the development work at github without telling the community anything, then after sometime again something like this will happen. 

Please start giving community more importance and development pace can go the way it is going now. Q2A has potential but even after 5 years it is not even close to any top QA softwares. The only reason is that our community is weak. Make that strong and rest of the things will again start coming back. 
Q2A QA - First
Q2A Github Repo - Second

**Comment by yerbol89** [comment]
Sorry @svivian but @gurjyot he is right. I have a website q2a. But lately, the project is progressing very slowly.

**Comment by svivian** [comment]
Thanks for the response. To answer a few points:

> Now what I really want to say is, if you don't want a team for Q2A then that's ok.

I've never said this. I want people to contribute, but not many are contributing.

> Development is just one part, you'll need to be active in community regularly (which you just started), you would need to promote Q2A both socially and through word of mouth

When did Gideon ever do this? He answered questions, sure, but I don't remember him promoting Q2A all that much (for example, there is no Q2A Twitter or Facebook page). Also he rarely responded to feature requests.

I am answering questions when I can. But the problem many people do not seem to understand is that spending time answering questions takes away from my development time. I am relying on the community to answer as much as they can. If there are things that I think no one else will be able to answer, then I will answer.

Regarding roadmaps, I already posted the roadmap several months ago. Due to the slower progress of development, very little has changed since.

>  As I always demand a Contact Us page and you say that Send Feedback page is there. Now there is no end to that, as I will not stop asking this again and again, but you can ask this in community that what users actually want, a Feedback page or Contact Us page.

You'll have to explain the difference to me then. What would a "contact us" page have that the feedback page doesn't have already?

> Same can be done for "User avatar dropdown in SnowFlat", whether there should be both avatar and username or just an avatar will look good. I remember that, when Jatin was building that theme you came to check that and all of a sudden you made the decision of changing user dropdown without actually asking or consulting the community (after all we have to use that on our websites, so our opinion should matter).

I didn't realise this would be controversial. I made several changes to the SnowFlat theme for UX reasons, which to me were clear cut improvements. Differentiating between the answer and comment icons was important. The key icon on its own was unclear so I added the "Login" text. The main reason the username is there is to handle the case where there is no avatar. The default Gravatar is not clear and sites may not use avatars at all.

Of course your opinion matters, but in the end there were several edge cases that people hadn't thought of.

**Comment by gurjyot** [comment]
Thanks for listening and even replying to me @svivian 

>I've never said this. I want people to contribute, but not many are contributing.

If not many are contributing then team up with those who are contributing. I am not saying to get anyone into team, but pupi1985 has proved every bit worthy to be in the team. Moreover after you, he is the only one taking care of Q2A community. Getting him in the team will increase the confidence level of community members in Q2A (which is very important).

>When did Gideon ever do this? He answered questions, sure, but I don't remember him promoting Q2A all that much (for example, there is no Q2A Twitter or Facebook page). Also he rarely responded to feature requests.

Well Gideon left because he thought Q2A is mature enough to be continued by community and become better. But I don't think Q2A is going anywhere since there is no promotion for this. Secondly, since you are the leader now so you have to set every rule again regarding the development, community activity, promotion, testing (Gideon is out of picture).
Thirdly, Gideon never responded to feature requests, then I think that its one of the main reason why Q2A is still so much confined. Responding to feature requests make the community more active and demanding and this brings new devs in the community. Now you have to decide over this.

For a better picture I can give you an example of Discourse. Every member of its dev team interacts with users so that they always maintain the level of trust among the users. This helps community become strong.

>You'll have to explain the difference to me then. What would a "contact us" page have that the feedback page doesn't have already?

The simple answer is, feedback page is used to give feedback over a certain thing (for example the looks of the website). But contact us page is used to contact admins of website in regarding to more professional talks (even to ask to admins if they are interested in selling their website). Now no one can ask to sell a website using a feedback page. That's why contact us page is so important. Now you can say to change the name of that using lang files, but when 90% of people need contact us page then why to have Feedback page? The remaining 10% can change the name using lang files.
Or you can just ask this in community to get even clear picture that what users want and this will also increase your influence on community that the main developer is asking community about their choice.

>I didn't realise this would be controversial. I made several changes to the SnowFlat theme for UX reasons, which to me were clear cut improvements.

You very well know that Q2A is community software, so why to develop it with only your own mind. This way we are using a software which is made as per your wish. We need a software which is made on communities needs. Every change should be discussed in community. You never know that some wonderful minds are just waiting to get a chance blow your mind with their thinking. After all your mind also came out of Q2A community ;)

 >The main reason the username is there is to handle the case where there is no avatar. The default Gravatar is not clear and sites may not use avatars at all.

Then you would have done something like, to use only avatar for websites which use avatar. But if there is no avatar then only username will be shown. Now that would have been much clear. Currently the combination just destroy the look of the website.
There are even more controversial issues like to change Favorite system to Follow system. I can bet you that more than 80% of users in Q2A would like Follow system more than favorite system. But the problem is, you never asked them about this, so they are stuck with this.

>Of course your opinion matters, but in the end there were several edge cases that people hadn't thought of.

Yes I completely agree with your thinking about this. But when was the last time you tried to put forward all those cases in front of community. I think never. In the last 1.8 years of your development you have only asked 7 questions and none of those was to get opinion through community or to share some problem with them (except 1.7 feature requests). Those were just to tell them something. 

>Regarding roadmaps, I already posted the roadmap several months ago. Due to the slower progress of development, very little has changed since.

I am not saying about roadmap in a question. I am saying roadmap on a separate page and that should have a link either in footer or main menu. Secondly, if you haven't even changed then also an update about those small changes after every 15 days will build up the confidence of community members in Q2A.
Half of the members are leaving Q2A thinking that Q2A is about to get close or its development is already closed. But these steps will definitely improve the image of Q2A among its members.

**Comment by svivian** [comment]
> If not many are contributing then team up with those who are contributing. I am not saying to get anyone into team, but pupi1985 has proved every bit worthy to be in the team.

I'm confused as to what you are talking about. pupi1985 is already a significant contributor to Q2A.

> The simple answer is, feedback page is used to give feedback over a certain thing (for example the looks of the website). But contact us page is used to contact admins of website in regarding to more professional talks

If your request is to just change the *name* of the feature, you should make that more clear. Same thing happened with favorite/follow. I'll consider changing the feedback name. But please don't throw around wild statistics like "90% of people want this" as it's not very helpful. Just because there is a vocal minority talking about something does not mean it's what the majority wants.

> You very well know that Q2A is community software, so why to develop it with only your own mind.

What I meant there is that the changes I made were clear solutions to well-known problems (for example "mystery meat navigation"). These things have been proven to be bad for usability so I fixed them. I thought I explained this (on the SnowFlat demo) when I made the changes but apologies if that wasn't made clear enough.

Finally, an important part of being a "leader" is to make decisions on the direction of the project. Of course I value the community's input with new features and so on, but if I ask for input on every single change development will go even slower than it is now.

**Comment by gurjyot** [comment]
>Finally, an important part of being a "leader" is to make decisions on the direction of the project. Of course I value the community's input with new features and so on, but if I ask for input on every single change development will go even slower than it is now.

Asking a question today and taking action in next few hours (maybe 6 hours) or next day won't slow the development even a bit. Instead it will bring very nice ideas or scripts around the community which can help Q2A become twice better.

>If your request is to just change the name of the feature, you should make that more clear. Same thing happened with favorite/follow. I'll consider changing the feedback name. But please don't throw around wild statistics like "90% of people want this" as it's not very helpful. Just because there is a vocal minority talking about something does not mean it's what the majority wants.

I apologise if I hadn't made this clear or made it confusing for you. But changing the favorite to follow is meant the same only. What difference is there between the two? Well I do not actually need an answer, my work was just to make my point clear to you or to take all these things to your ears.

>I'm confused as to what you are talking about. pupi1985 is already a significant contributor to Q2A.

I am saying about adding pupi1985 to be part of Q2A official dev team. Right now you are alone there and by adding one more member there won't do any bad to Q2A. Instead it'll only improve that. Now you can say about giving another look to their pull requests, that can also be done after they are merged because those changes would have been in dev branch on Github. So it won't do any bad to core code as well. But the decision is upto you, as there is no forcing since you say that you can take care of core alone.

>What I meant there is that the changes I made were clear solutions to well-known problems (for example "mystery meat navigation").

Making bug fixes is good to be done without discussing to community. But any enhancement or feature should always be discussed first in community, this way you minimise the risk of "users demanding different implementation of the same thing". And when new theme was building then that was a big enhancement for us all.
