### ISSUE TITLE
Notification cross button is misplaced.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#280]
Notification cross button problem was fixed before but in Q2A 1.7.1 it is still appearing. Please fix this.

![q2a](https://cloud.githubusercontent.com/assets/6462850/9221058/d1bda260-4104-11e5-8fab-268ec3ff83cd.png)

**Comment by q2amarket** [comment]
@gurjyot please provide browser details too. This will helps to check browser specific issues.

**Comment by gurjyot** [comment]
Hello @q2amarket, I am using Google Chrome Version 44.0.2403.155  on windows 8.1

**Comment by q2amarket** [comment]
@gurjyot okay will check later today once I log on to windows..

**Comment by svivian** [comment]
I'm not seeing this issue either. Do you have some custom HTML in the message in the red bar? Are you able to find the issue in Chrome Dev Tools?

**Comment by gurjyot** [comment]
I have written a line and a link in the last, nothing else is there in the notification bar. I am not able to get any error in chrome dev tool as well.

**Comment by q2amarket** [comment]
@gurjyot Just to cross confirm..any html tags in the message? like `H2` etc.. or any plugin css overriding.. or give your site url to check.

**Comment by gurjyot** [comment]
Hello @q2amarket as per your reply I checked the html tag used. I haven't used any tag other than link tag (<a href>) but I am using "editor for admin plugin". Now when I disabled this plugin then there is paragraph tag (<p>) added. I removed that and now the notification works fine. But as I enable the plugin the paragraph tag is back.
Isn't there a way to let notification work with this (<p>) tag so because working in admin section without the editor is very difficult.

**Comment by q2amarket** [comment]
@gurjyot In that case you may have to modify either plugin css or the theme css. You can do easily by targeting the root element something like below.

***You can modify css for `p` notification parent selector***

````css
.notification-parent-selector p{
	margin: 0; 
}
```` 

***Or you can target `p` with your plugin's selector***

````css
.plugin-parent-selector p{
	margin: 0; 
}
````

**Comment by gurjyot** [comment]
Ok... now this is good. I'll try this, thanks for your assistance Jatin... :)
