### ISSUE TITLE
Bug: If an admin retagged a question and then changed his username then "anonymous" shows in question

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#282]
An admin has retagged a questions some days back, now when I was exploring the website then I say it was saying "retagged by anonymous" so I click on anonymous and it shown the IP address of that admin. 
So I thought this might be due to change of username, as that admin changed the username in between. Please fix this.

**Comment by amiyasahu** [comment]
I am unable to reproduce this . I created a Admin , retagged a question . Then changed the username . And as expected it shows the changed username there . Not sure how did you get this issue .

**Comment by gurjyot** [comment]
Hello @amiyasahu brother, I have again encountered this very problem on my website.
I'll send you more info at your fb account if you can see that..

**Comment by svivian** [comment]
Do you have my tagging tools plugin installed? There was an issue (can't remember if I've fixed it yet) where mass retagging from the admin panel would set the editor as anonymous. Might also be applying here if your admin retagged a question and TT changed/removed a tag.

Otherwise it could be another plugin that does some kind of editing in an event etc.

**Comment by gurjyot** [comment]
Yes I am using that plugin and the admin whose name is showing as anonymous has also used that plugin to correct a tag for some questions. Maybe that's the issue, but only you (@svivian ) can confirm it by having a look at that plugin.

**Comment by svivian** [comment]
Are you using the latest version of Tagging Tools? I checked and the bug I mentioned was fixed ages ago.

So I'm still unable to reproduce this. Is it still happening on your site?

**Comment by gurjyot** [comment]
I just checked the plugin and its latest, 1.8 I guess. No I am not facing that problem right now but I was facing that just a month ago. So have you updated the plugin just a month back or it's due to something else.

**Comment by svivian** [comment]
Yes that's the latest version. So I think it must be something else causing the problem. Let me know if you find a way to reliably reproduce this.
