### ISSUE TITLE
Many new users are not getting mails for registration confirmation

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#283]
Many users have contacted me that they are not getting confirmation mails. Even if they resend the mail then also they are not getting the mail. They have checked the spam folder but the mail is not even in that.
Although this is not the case with all users, because many are easily able to register but still 10% are complaining for this, so I guess the percentage of users not getting mail would be great as 10% are having enough time to contact us.
I am using Q2A 1.7.1
Theme: SnowFlat
Hosting: Shared Hosting from Hostgator (linux)

So if there is a way to improve the code for mails that they should reach to users or admins could have a way to auto confirm user's account from user's profile. After all confirmation is to tell that user is legit and if he is mailing us the issue then he is legit.

**Comment by svivian** [comment]
The emails are handled with PHPMailer which is a solid library (also used by Wordpress and Joomla). You could try upgrading to the [latest version here](https://github.com/PHPMailer/PHPMailer/releases) (Q2A currently uses 5.2.7) in case there is a bug with PHPMailer, but I think the most likely explanation is the hosting. Do you have SMTP details from your host, or some other configuration details you are supposed to use?

**Comment by gurjyot** [comment]
Thanks for your super quick reply Scott. 
Firstly, don't you think PHPMailer 5.2.7 is quite old now at it was release in 2013 and it should be updated.
Secondly, how and where to update it. Do I have to update it in Q2A source files or in my hosting.
Finally, I am using local mail instead of SMTP. But if you are talking about SMTP details of my host in other way then I haven't checked them as I never used them.

**Comment by svivian** [comment]
> Firstly, don't you think PHPMailer 5.2.7 is quite old now at it was release in 2013 and it should be updated.

It was updated for 1.7 (see 422f110). There have only been 3 minor updates since then, but yes it will be updated in Q2A.

> Secondly, how and where to update it. Do I have to update it in Q2A source files or in my hosting.

The PHPMailer files are in `qa-include/vendor/PHPMailer/`. All you should need to do is copy the same files from [the repo](https://github.com/PHPMailer/PHPMailer) to that folder.

> Finally, I am using local mail instead of SMTP. But if you are talking about SMTP details of my host in other way then I haven't checked them as I never used them.

If your host does not have any special requirements to send mail then it should be working fine. You should probably check with them if there's anything special you need to do for sending emails.

**Comment by gurjyot** [comment]
Okh then I'll update the files but as you are saying those were not major updates so there is great possibility that it might not fix the issue coming. The issue can be somewhere else.
I know it is not the place for request, but still I am doing this because many users who use Q2A are facing this problem -- to implement an alternate solution for account confirmation. I don't know what can be the best solution but if can suggest users a solution or directly implement a solution.

**Comment by svivian** [comment]
I've just upgraded PHPMailer to the latest version, though as you say it may not fix your problem. I can't really see the problem being anywhere in Q2A or PHPMailer, it's very likely to be an issue with the mail server on your hosting. If you're able to point to any specific problems in the Q2A code I'll reopen this ticket.

BTW a good alternative is to use a "transactional email service" such as [Mandrill](http://mandrill.com/) or [Mailgun](http://www.mailgun.com/). They give you SMTP details to use, and both give you thousands of free sends a month which should be plenty for most circumstances.
