### ISSUE TITLE
Error when a question needs approve

### ISSUE THREAD

**Issue by fardina** [q2a/question2answer#284]
I received an email about approving a question. when I clicked on the link of the question (because I wasn't log in) I saw this error:
 Notice: Undefined index: q_view in /home/.../public_html/.../qa-include/qa-base.php(591) : eval()'d code on line 654

Is it a bug?
Q2Aversion: 1.7.1
Theme: SnowFlat

**Comment by svivian** [comment]
I cannot reproduce this on the default Q2A setup. Could be related to a plugin - can you try removing them one by one and seeing if the notice goes away?

**Comment by fardina** [comment]
Hi svivian,
Thanks for the response. I found this happens only when I use mobile!

**Comment by fulldecent** [comment]
I am clicking on the link when logged in and am not seeing this error

**Comment by svivian** [comment]
Closing this. If you can provide a live example or a way to reproduce the error, let me know.
