### ISSUE TITLE
htaccess redirect www to non-www

### ISSUE THREAD

**Issue by rinkublog** [q2a/question2answer#285]
I am using htaccess file for SEO Url.

I added below rules in htaccess file to redirect www to non-www.

RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]

But when i access like www.mysite.com/1/question-title

Then i land on www.mysite.com/index.php?qa-rewrite=1/question-title

i means i want to redirect all www pages to non-www.

Please help.

**Comment by svivian** [comment]
Hello, the Github repo is for reporting bugs, not for general help. Please ask your question on the [Q2A site here](http://www.question2answer.org/qa/). But first search for existing questions because this has probably been answered before. Thanks.
