### ISSUE TITLE
Bug: If the answer is too big then some of its portions is getting hidden.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#287]
I have been reported about a problem by one of moderators on my website. That if the answer is too big then some of the end part of it is getting hidden. Sometimes it shows the limit message but some times it just hides the end content and answer is left incomplete.
Then I tried the same with an admin account and the same happened to me as well.
Need solution for this at high priority.

**Comment by svivian** [comment]
I can't reproduce this. Are you using the standard WYSIWYG editor without modifications? Is your qa_posts.content field still the standard 8000 characters or have you changed it?

Please can you provide a test case, i.e. the exact content that is submitted to receive this error (pastebin.com may be useful for that).

**Comment by gurjyot** [comment]
Thank you for such quick response. I am using same standard editor of Q2A 1.7.1. 
Yes I have changed character limit from 8000 to 16000 as my users were complaining about that character limit message. I had no choice but to increase that.

I have arranged the content in pastebin.com
My moderator increased the size of this content that's why he got the issue. But for me to test I have to paste the same content twice to get the same issue. One more thing, there was also an image in between.

**Comment by svivian** [comment]
I tested with your sample content and still no problems for me. Your sample content is only 4662 characters though. And if you're using the WYSIWYG plugin it's not the exact content (I'd need the HTML from the database).

Is it perhaps due to you not setting the max size constants? If QA_DB_MAX_CONTENT_LENGTH is larger than the field length (16000) then it may be trimmed without a warning. But there's not really much I can do without a specific test case, sorry.

**Comment by gurjyot** [comment]
So what should I do to make this work @svivian. Moreover you also closed the issue without even providing a solution for this.
Secondly, I am still getting this issue on my another website where I increased the DB character size to 12000 as you did it for Q2A 1.8.

What is happening is, sometime users get a warning that character limit is crossed but mostly they do not get any warning and they easily post there answer. Although the answer is getting trimmed without any warning.

**Comment by svivian** [comment]
Do you have a link to an example question/answer on your site where the post was trimmed?

Also if possible, can you give me the exact row from the database? (For example: in phpMyAdmin select that specific row with `select * from qa_posts where id=X` with the post id in X, then click "Export" under "query results operations".)

You didn't answer my point about `QA_DB_MAX_CONTENT_LENGTH` - are you setting that in your `qa-config.php`? Is it the same as the size of the 'content' field?

What content editor are you using? The default CKeditor? Any extra CKeditor plugins?

Are you using any other Q2A plugins that might be modifying the content?

**Comment by solidChen** [comment]
You should check your content.

 I had met one similar situation:
When I import some data from excel to the database and I found the content is to long to show. It print words over the frame.
But, when I check these content, I found that "space" between words are not the normal one. I copy and replace all the problem "sapce" and I found all question tile and content became normal.

Consider about it.
