### ISSUE TITLE
Allowing them to use the symbols at the @#$%^&*(),.? for registration?

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#288]
Allowing them to use the symbols at the @#$%^&*(),.? for registration?
My site users for register site use symbols @#$%^&*(),.?. After i share facebook or social network link dont work because user use for login symbol .. ()

Is it possible to prevent a user so that it can only be used in the login only characters:
abcdefghijklmnopqrstuvxyz0123456789

**Comment by svivian** [comment]
Yes it's possible using a filter plugin. I was searching for an answer I gave on Q2A about that and you already asked this question there... http://question2answer.org/qa/43664/register-page-for-username-dont-use-%40%23%25%24-and-cyrillic-symbols

And here's a more detailed example: http://question2answer.org/qa/27723/dont-allow-people-to-register-with-some-usernames-like-admin?show=27726#a27726
