### ISSUE TITLE
Button alignment issue with small sized pic

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#290]
This issue also arose before but that time it got fixed. This time the pic was set for left side alignment and that caused the issue.

![paintissue](https://cloud.githubusercontent.com/assets/6462850/10055409/c0452006-6253-11e5-8011-6261a2ba29a9.png)

When the pic is set for "no alignment" then everything got fixed without any issue.

Can't we change the style of button they appear in. I mean just the icons is creating problem to users and it looks very crowded... so here is a solution for two problems at one. 

![paint](https://cloud.githubusercontent.com/assets/6462850/10055522/519220ea-6254-11e5-9392-51811b67ff81.png)

This way the questions or answers will not be too crowded with buttons and secondly you can write complete text for buttons instead of just icons. Using just icons has increased flagging to 5 times on my website and they all do it by thinking that it is a way to saying thanks...

**Comment by yerbol89** [comment]
![default](https://cloud.githubusercontent.com/assets/993795/10056492/5c598dfc-625d-11e5-8291-6793e991d866.png)

**Comment by gurjyot** [comment]
@yerbol89 you have shown a nice pic. I also remember that there are plugins which add extra buttons so those make it even more difficult to accommodate in such small place. Because of that reason a dropdown for extra buttons is necessary now for Q2A. With time even more features will be made and at that time also new buttons will be introduced so a dropdown will be the best solution.
What do you have to say @svivian ??

**Comment by svivian** [comment]
Finally got around to fixing this.

Regarding the buttons themselves, I don't think hiding them away in a menu is a great idea because then it's multiple clicks to do anything. I was never sold on using icons only but a lot of people seemed to like it.

I'd be happy to go back to something like the Snow theme where we have the buttons with text. I think if they are smaller than the current ones then they don't get in the way too much. Also remember that most users will only see a few buttons on posts.

**Comment by gurjyot** [comment]
@svivian  Please don't reduce size of buttons, big buttons in SnowFlat actually make it good and readable. At last, the buttons which we want you to hide are only those which are not used on daily basis. 
Secondly, what about the extra buttons which can be added through plugins to add extra features. Those buttons will again disturb the button alignment.
