### ISSUE TITLE
SnowFlat uses Google web fonts even though the fonts are redistributable

### ISSUE THREAD

**Issue by pietsch** [q2a/question2answer#295]
This is a privacy issue. Q2A admins might well prefer to run a tracker-free website. Why make connections to a Google service if you could just as well include the Ubuntu fonts in the theme? Their license permits this. I am preparing a pull request for this.

The way web fonts are loaded has to be changed to independent reasons anyway (see #294).

**Comment by svivian** [comment]
Yes this is a good point. Google Fonts does provide a lot of convenience though since it serves different font types to different browsers. As long as you can put together something that works the same cross-browser, that will be great.
