### ISSUE TITLE
qa-plugin/recaptcha-captcha needs allow_url_fopen to be enabled

### ISSUE THREAD

**Issue by palatinuse** [q2a/question2answer#300]
The qa-plugin/recaptcha-captcha needs the allow_url_fopen option to be enabled in the server's config, which is usually disabled by the hosting provider of the website.

Infos on this issue can be found here:
You can follow the instructions here for more information on this issue - google/recaptcha#36

Please note also, that the version of recaptcha shipped with q2a is outdated, and/or not the full version.

**Comment by amiyasahu** [comment]
@palatinuse , I have updated the recaptcha and fixed the bug . Can you check if it works for you now . 
You can download the latest plugin from here for testing - https://github.com/amiyasahu/question2answer
I have tested , it works for me . If it works on your live server I will send the PR .

**Comment by palatinuse** [comment]
I have tested your modified version of the plugin, and it works flawlessly.
Thank you for the very fast response!

**Comment by amiyasahu** [comment]
you are welcome :smile:
