### ISSUE TITLE
lists in Snowflat & Markdown Editor

### ISSUE THREAD

**Issue by fardina** [q2a/question2answer#307]
Hi
After changing my theme to SnowFlat I saw that list items would be marked with only ✓ even for lists in list.
In Markdown editor a list should be like:
- list item
    - list item
        - list iteme

but now it is just ✓  instead of circles and squars.

In preview everything is okay but after sending question or answer all the list items will be marked by ✓.

**Comment by svivian** [comment]
I've actually already made this change in a commit somewhere (might not be published in the repo yet).

**Comment by fardina** [comment]
So what to do now?

**Comment by svivian** [comment]
Just checked and this was published on the dev branch (so will be part of 1.7.2). Thanks for reporting.
