### ISSUE TITLE
Pic always aligns to the left instead of being in the centre. 

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#308]
When ever we upload a pic then it automatically aligns itself to left even when no alignment property is selected. Now if we select the left property then it aligns to the same place but just the text starts to show with it. The worst part is, there is no property to align the pic in centre. 
Could you please make necessary adjustments, so that when no alignment property is applied to a pic then it should show in centre.

**Comment by amiyasahu** [comment]
in which theme you are getting this issue

**Comment by gurjyot** [comment]
@amiyasahu bro it's in SnowFlat theme... Maybe some other theme can also be showing the same behaviour but I have just checked this in SnowFlat.

**Comment by svivian** [comment]
I'm not sure if this would be possible. To centre an image you need to centre the surrounding paragraph/div which is not doable in CSS.

Plus, left aligning by default is the standard, I don't really see a need to stray from that.

**Comment by gurjyot** [comment]
It can be done in Wordpress so definitely it can also be done in Q2A. 
If you need a reason then I was working on a page where I needed a centralised pic so that users can understand what I want them to know. But when it shifts to left then it just ruins the design. 
Basic UI things are very important for any website to stand out form the crowd.

**Comment by svivian** [comment]
Maybe I'm not understanding your feature request. If you want to center an image on a particular post just press the center button in the WYSIWYG editor.

To center all images on all posts, the only method I can think of is to set them to display block with auto margins. But that is messy and causes other problems, not to mention that it's not what everyone wants on their site. How does Wordpress do it?

**Comment by gurjyot** [comment]
I am not saying to place all images to centre. I am saying when we upload
an image then it should be displayed in centre.
Currently it is displayed in left.
Now you said to press the centre button for image placement. But there is
no option for centre alignment of an image in WYSIWYG editor...

**Comment by svivian** [comment]
Not in the image upload dialog. The "Align" field there is for floating to the left or right. But when you click OK and the image is in the editor you can press the Center button there to align it (well, the paragraph) to the center.

If you want a center option in the upload dialog you'll have to take it up with the CKeditor developers, since that's not really something we can control.
