### ISSUE TITLE
Minor CSS issue, Wide images overlap with user avatar in questions

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#311]
If the image is wide enough, then it overlap with user avatar in questions. See to this pic below.

![issue](https://cloud.githubusercontent.com/assets/6462850/10876204/9d55d44c-8160-11e5-9847-5674c80e8f4d.png)

**Comment by svivian** [comment]
I was never a massive fan of the way the avatar drops below the horizontal line like that. And also it being over to the side away from the actual username. Let me know if you have any ideas for a better layout there.

**Comment by gurjyot** [comment]
Actually it looks better the way it is not, shows symmetry in the structure. But some spacing should be there between the content and the user avatar lift on the left side (with voting). 

Another way could be, bring avatar to the left just where voting is shown. Shift the voting after the avatar and the problem will be fixed, but I don't know whether users will like it or not.

**Comment by svivian** [comment]
This was fixed in a4b35c4.
