### ISSUE TITLE
Suggestion: Make Tag Cloud Widget more feasible to read

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#312]
It's a normal thing, that most people can't read very small things and that's the reason that so many good readable fonts started to show up.
The same is the case with this widget, currently only two or three tags are readable and rest are so small that many people are not able to read them. So a good way to implement this widget is to change it's UI. Make it something like this.

![tags](https://cloud.githubusercontent.com/assets/6462850/10892389/19c13928-81c9-11e5-8eab-194b2c8b5a67.png)

**Comment by svivian** [comment]
But then it wouldn't be a tag cloud... the point of a tag cloud is for the popular tags to be larger and the less popular to be smaller.

I could make it so that it doesn't ever get too small, but I we do what you suggest then it's a different plugin.

**Comment by amiyasahu** [comment]
I agree with @svivian . 

@gurjyot , the popular tags with the question count already there in the tags page .

**Comment by gurjyot** [comment]
Then I would just say one thing, let's think on this plugin again. UI matters the most for any user, and this plugin is not suitable for a large volume of users. 
If this plugin is causing problem then shouldn't we consider to include a better plugin in Q2A core which is good for all users equally and even go with the UI.
I just need your suggestions on this.

**Comment by fardina** [comment]
@svivian @amiyasahu at first I really appreciate your efforts.
And Thanks @gurjyot for creating this issue.
To be honest I don't remember if I have ever used Most Popular tags widget in Q2A website!
But from the time I changed the CSS of the plugin to be like This(http://question2answer.org/qa/49272) it has been one of the useful plugins in my forum. I don't say change it to be like what I suggested but please (if it is possible for you) make it a real useful tag cloud.
Thanks.

**Comment by svivian** [comment]
Fardina's comment from #334 

> As I suggested [here](http://question2answer.org/qa/49272/suggestion-about-most-popular-tags-widget?show=49287#a49287) I think it is better to change this line
> `$size = number_format($maxsize * $count / $maxcount, 1); `
> to
> `$size = (($count - min($x)) / (max($x) - min($x)) * ($maxsize - $minsize)) + $minsize; `
> Maybe this can help to have a better cloud tag?

**Comment by svivian** [comment]
Took an idea from an old plugin by NoahY and used a log scale for the sizing, which should close up the sizes on most sites. Default minimum size is also larger.

**Comment by fardina** [comment]
@svivian Hi Scott. this is an image from my website when I am using my approach:
![mytag](https://user-images.githubusercontent.com/13521621/31483014-9afcf26e-af37-11e7-90e5-8583c8b098fa.png)

And this one is default Q2A
![your tag](https://user-images.githubusercontent.com/13521621/31483031-aaa50eea-af37-11e7-9af5-76b3d905d7ac.png)

which shows that my suggestion maybe is better?
