### ISSUE TITLE
Improve basic-adsense plugin for responsive ads

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#313]
Q2A 1.7 was all about responsive design and making everything working under mobile. But one thing was left completely untouched and that is ads. 
Right now, if I apply an ad to show just after menu then it shows perfectly, but when I open the website in mobile then that ad is not made to fit in mobile screen. Instead a half cut ad shows which is worst as user doesn't understand that what's the half ad is for and it even looks bad.

So please improve that plugin and provide some solid solution for placing ads. It's one of the most important plugins for users so make it worth to be in Q2A core, otherwise ditch this plugin and include a third party plugin which can take care of most ads type.

**Comment by amiyasahu** [comment]
yes this should be taken care .

**Comment by hypermax** [comment]
And we need to add the possibility to share adsense revenue with others users ( like user can add his adsense code to be showed in his posts )

**Comment by svivian** [comment]
Adsense does responsive ads now so I'll check into it and see if there is a generic code we can use.

@hypermax the Adsense plugin is only meant to be a simple widget. Revenue sharing is much more complex and should be a separate plugin.
