### ISSUE TITLE
Dot and double dot should not be allowed as usernames 

### ISSUE THREAD

**Issue by amiyasahu** [q2a/question2answer#315]
Currently q2a filter modules is taking care of several checks on the username . 

But it allows the user to register as `.` (just a single dot) and `..` (two dots) . 

eg - http://www.question2answer.org/qa/user/.  

The problem is if the user is registered using these usernames , he can do all the activities , but his profile pages and all the pages where username is used at the address bar can not be accessed as these characters are considered as current directory and prev directory . Admin also can not view his ip address to block or can not edit his profile .

It was addressed in this thread - http://www.question2answer.org/qa/47824/i-can-not-access-the-profile-of-user-who-signed-up-using-point

I can fix this , but I want to know others views on this before proceeding . I feel it is a security hole of q2a .

**Comment by svivian** [comment]
I think the problem is with creating the links to the username. The user page works perfectly fine if you encode the URL: http://www.question2answer.org/qa/user/%2E

(BTW it's not a security hole since it doesn't allow the user to do anything untoward.)

**Comment by amiyasahu** [comment]
The URL is not encoded in the user navigation . 

![user](https://cloud.githubusercontent.com/assets/2969035/10929413/26ec0018-82d9-11e5-9c80-e20af429a8fc.PNG)

And also when I follow the encoded link you provided me takes to the logged in profile page . 
When I tried to login in as dot user , when I go to the profile page , it falls into an infinite loop (Not sure why , will take a closer look when I have some time).

**Comment by svivian** [comment]
Turns out that the `%2E` only works on some browsers. So the only real solution was to prevent `.` and `..` from being usernames. Anything else containing dots should be fine.

**Comment by amiyasahu** [comment]
Now it is perfect .. Thanks
