### ISSUE TITLE
Can we use another simpler WYSIWYG editor?

### ISSUE THREAD

**Issue by twolegged** [q2a/question2answer#316]
The current one CKEditor has too many features and the image upload sucks.

**Comment by svivian** [comment]
Yes you can use whatever editor you like if there is a plugin for it, or you develop your own.

The CKeditor was greatly simplified for Q2A 1.7 so I don't know why you think there are too many features. But you can change the config.js file to simplify it further if you like.

PS the GitHub repo is for bugs/PRs so in future feature requests should be made on the Q2A site http://www.question2answer.org/qa/

**Comment by twolegged** [comment]
Thanks. I didn't know.
