### ISSUE TITLE
Discussion: Why "Questions page" sub-menu is not shown on homepage?

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#320]
I know this is no place for discussion or feature request but I didn't knew how to contact you @svivian .

I have raised the same question in Q2A as well (http://www.question2answer.org/qa/48585) and @amiyasahu also supported me and when I talked to him about making a PR for this then he said that he don't know whether you'll accept it or not. So we needed to clear this with you.

Should this feature be implemented in Q2A like the way I said in that questions.

Secondly, please clear that what feature can other developers make so that their work and time doesn't go waste. Or a way to actually talk to you first for coding any such feature.

**Comment by amiyasahu** [comment]
I agree on the idea that the navigation links on the home page should help users to find the posts . 

Just wanted to hear from you @svivian  if this applicable for the core features or not before heading towards the improvement and PR . 

I will proceed accordingly .

**Comment by svivian** [comment]
I answered your question on Q2A. I'll close this for now while we discuss over there.
