### ISSUE TITLE
How do I include ask question box at the bottom of "Recent questions and answers"

### ISSUE THREAD

**Issue by mrraghur** [q2a/question2answer#321]
As soon as I open my website, I see "Recent questions and answers" list. I want a user to be able to add his/her question right away from this page without having to navigate to a different view(/page). 

It appears to me that there is no way to mix qa-page-question-view.php with qa-page-question-post.php
Is this correct or am I missing something?

Thanks!

**Comment by amiyasahu** [comment]
You can try adding the `Ask Box` widget at the `Main area - Below title` in Admin -> Layout .

**Comment by mrraghur** [comment]
@amiyasahu 
Thanks! I tried it but on click, it takes to the normal add interface. Is there no way to directly post from homepage (i.e. no intermediate step?)

**Comment by amiyasahu** [comment]
This feature is not inbuilt in q2a . You have to write a plugin by yourself

**Comment by mrraghur** [comment]
@amiyasahu 
I understand this is not a inbuilt feature. I already started writing a plugin but I am kind of stuck since. I there does not seem to be a way to mix "views" (qa-page-question-view.php) with "posts" (qa-page-question-post.php).

All examples I see in q2a software and in plugins do not mix the two (i.e. a page showing list also showing a post question button).

If you can give some (code level) pointers on how to mix the two, I would really appreciate it.

**Comment by amiyasahu** [comment]
You should create a widget - http://www.question2answer.org/modules.php?module=widget

**Comment by svivian** [comment]
The way to do this would be to add a new form to the bottom of the page. Look at the bottom of `qa-include/pages/ask.php` for the variable `$qa_content['form']` that shows you what format you need to use. You could probably copy all that to wherever you need to put it.

In your case I think you could set it as `$qa_content['form_2'] = array(...)` and it should appear at the bottom.

If you have any further questions I suggest you ask on the [Q2A site](http://www.question2answer.org/qa/). Thanks.

**Comment by mrraghur** [comment]
@svivian,
Thanks very much. I will try it. I had previously asked on  Q2A site but didn't get any responses. So, I asked him. Thanks anyways!
