### ISSUE TITLE
Add schema.org microdata for Q&A pages (SEO)

### ISSUE THREAD

**Issue by PELock** [q2a/question2answer#322]
Please consider adding microdata from schema.org like it's done on StackOverflow, it's the most recent version of microdata related to Q&A pages. I think this change would give any Q&A page a major SEO kick. 

Install this plugin (Chrome & Opera) to preview the schema.org microdata on the SO site

https://chrome.google.com/webstore/detail/semantic-inspector/jobakbebljifplmcapcooffdbdmfdbjh?hl=en

They are using 3 entities

http://schema.org/QAPage - for the entire question page
http://schema.org/Question - for the question
http://schema.org/Answer - for each answer

**Comment by svivian** [comment]
Actually this has already  been implemented! :)

Check out the 1.8 branch to see. The specific commits are: 966feeb fc634ce b07c082

**Comment by PELock** [comment]
I was looking at the current version. Sorry :)

**Comment by hypermax** [comment]
Please any date for the 1.8 release ?

**Comment by yerbol89** [comment]
@hypermax good question

**Comment by svivian** [comment]
I was hoping for December but I have another big project on right now so I can only do little bits here and there for the next few weeks. So it will likely be January when the final release is out.

**Comment by q2apro** [comment]
Close: https://github.com/q2a/question2answer/issues/357
