### ISSUE TITLE
In /users add sorting option "Newest users"

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#325]
Currently, available sorting options are:
- Top scoring users
- Special users
- Blocked users

I am requesting a new
- Newest users

This will help in identifying spam and reviewing new users.

**Comment by svivian** [comment]
Yes I've thought about this too. Would be a good thing to add.

**Comment by gurjyot** [comment]
In addition to this, providing a simple option to show Special Users page to everyone would be great. Users should know, who are the ones moderating the forum.

**Comment by svivian** [comment]
Yes good point @gurjyot.

Not sure when I'll get around to this but if someone else wants to implement it, go ahead.

**Comment by pupi1985** [comment]
I've just implemented @gurjyot's suggestion in this PR #467

**Comment by gurjyot** [comment]
Thanks a lot @pupi1985 for applying this feature. :)

**Comment by pupi1985** [comment]
I've just updated the same PR and included the `Newest users` feature

**Comment by gurjyot** [comment]
That's even better, now I can't wait for Q2A 1.8 to release (Thanks a lot @pupi1985 and @svivian )... :)
