### ISSUE TITLE
Ask Page CSS Issues

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#328]
There are some minor issues with ASK page and I hope those can be rectified with simple modifications.

1. Box border is too lightly coloured, for people with slightly weak eyesight it is very difficult to see question box, category selection box and tags box and comment box in question pages. Making it little bit dark would be much better.

2. The background for "duplicate question checker heading" is Dark red. But the red colour should only be used for any missing field error in that page.  With that super red bar, it is difficult to get the error in first attempt for new users specially in mobiles.
Changing the Red colour for duplicate question checker heading to some other colour will give more focus to the warning in first go.

**Comment by svivian** [comment]
Good points. CSS updated.

**Comment by gurjyot** [comment]
Thanks for the fix Scott... :)
