### ISSUE TITLE
Facebook Login not working on my website any more.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#333]
I have been using FB login for months now, but recently users reported that they are not able to login with that one. I rechecked the public key and secret keys, but both of them are there and they are exactly the same as they are on FB.

So what should I do to get it back running as this one plugin is very important for my users to login.

**Comment by svivian** [comment]
Can you be more clear about what exactly is not working? What actually happens when you try to log in, any error messages, etc?

**Comment by gurjyot** [comment]
We click the FB login in button, a popup window shows up, then we input are username and password and press enter. After this, the pop up window disappear and my website reloads and nothing happens.

**Comment by gurjyot** [comment]
Facebook Login started to work all of a sudden after two some days. I haven't touched anything and its working now. 
Although I don't know whether I should close this issue or let it be here because some problem is definitely there but I am not facing it anymore.

**Comment by svivian** [comment]
It's working fine on the Q2A site, so perhaps it was a temporary glitch with Facebook itself.

**Comment by gurjyot** [comment]
Yes maybe you are right, I just applied FB login back and it's working perfect. Thanks for your time Scott. :)
