### ISSUE TITLE
No error message for content in edit question

### ISSUE THREAD

**Issue by dreamon11** [q2a/question2answer#336]
Same error as https://github.com/q2a/question2answer/issues/327 but for editing question.

Fix replacing :

$pageerror=@$qerrors['page'];

by

$pageerror=@$qerrors['text'];

in qa-include/pages/question-post.php, l.130

With q2a + wordpress.

**Comment by svivian** [comment]
Are you using the latest version from the Github repo? (That fix for 327 is not in v1.7.2).

**Comment by dreamon11** [comment]
Great! I was on "master", switch to "dev" where the fix is and it's OK! :)
