### ISSUE TITLE
When moderating, the moderation count is not updated in real-time

### ISSUE THREAD

**Issue by Spudley** [q2a/question2answer#338]
Go to the admin moderation page in Q2A. The number of questions to moderate will be shown in brackets in the tab heading--  "Moderate (1)"

Click approve or reject to complete the moderation task.

The item being moderated is removed from the page, but the item count in the tab is not updated.

Okay, I know this is a really minor issue, but hopefully it would be pretty easy to fix.

Thank you.

I'm using Q2A 1.7.2.

**Comment by svivian** [comment]
Actually I'm not sure if it wil be an easy fix, since it may depend on the theme and/or language being used. But I will check into it.

**Comment by svivian** [comment]
This isn't possible right now given the way Q2A's AJAX system works. It may be refactored in the future in which case I'll keep this in mind, but for now it's a only minor UI issue.

**Comment by svivian** [comment]
Just a quick note that this has been fixed by pupi1985's recent work converting the AJAX responses to use JSON :)
