### ISSUE TITLE
CSS Bug: In mobile view question title comes down counters if there are too many views

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#339]
Question title in questions list page shifts down in mobile if there are too many question views(I think this is the cause of the problem). See the below pic.

![q2a](https://cloud.githubusercontent.com/assets/6462850/12057736/0168dac4-af6a-11e5-8109-a8cf987ab0f7.png)

**Comment by svivian** [comment]
Made a quick fix for this. But I'll have to take a closer look at the layout some time, because there are a few weird things with the size of the title block (`.qa-q-item-main`), sometimes it isn't filling the whole width.
