### ISSUE TITLE
Move question2answer.org documentation to GitHub Pages / Jekyll

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#341]
Hello all. In order to make updates to question2answer.org easier for more people to get involved, and to reduce the maintenance effort from current management, I propose to move this website to GitHub pages using their web server and Jekyll for page processing.

This may be considered a best practice for open source projects and I have started most of the effort already.

For a live preview of this website, please see https://fulldecent.github.io/question2answer.org/

If you would like to get involved, please see https://github.com/fulldecent/question2answer.org

This issue was created in an effort to find more contributors interested in helping. Please join if you have HTML or Jekyll experience or if you otherwise support the cause.

When the result is good enough, we will <strike>create a pull request from that project into this project in a new `gh-pages` branch</strike> move this project to the `q2a` user. The end result will be a website which is automatically generated from source code here in the `question2answer` repository and supported by the Q2A contributors like you and me. Further discussion on the project plan and migration plan are at https://github.com/fulldecent/question2answer.org/blob/gh-pages/README.md

**Comment by svivian** [comment]
Thanks for taking some initiative with this! However, I've never been sold on Github pages - using a separate branch with entirely different content is weird to me. It would also result in this repo filling up with documentation issues/PRs, which I'd prefer to keep separate.

Furthermore, there are several pages on the current Q2A site that cannot be represented in a static site such as the [Q2A site directory](http://www.question2answer.org/sites.php). I think there is value in hosting the site ourselves rather than relying on a limited offering from Github.

But I don't want any of your effort to go to waste - I'd love to have you on board with some kind of user-contributed documentation! As it happens I also started working on a similar solution a little while ago - https://github.com/svivian/q2a-docs - and was planning on getting that set up some time this month.

It uses the [Sculpin](https://sculpin.io/) static site generator which I thought would be easier for contributors since it's in PHP. My intention was to set it up in a subdomain/directory (i.e. `question2answer.org/docs/` or `docs.question2answer.org`) and have a separate repo under the @q2a account. That way we can keep PRs contained and easily add Collaborators such as yourself to update the repo.

What do you think?

**Comment by gidgreen** [comment]
Hi guys, thanks for the initiative. I'll be happy to support whatever makes the most sense - I can also write a little script for question2answer.org that pulls a page in from elsewhere and then caches it locally, for delivery by the regular server, with a simple URL parameter that you would add like ?refresh=[some low-security password] to make it pull down and cache the latest version.

**Comment by fulldecent** [comment]
Quick update: assuming that there is an appetite to update the website, I am creating a few more issues which are independent of what choice we make. Also, I will bring an updated proposal soon.

**Comment by fulldecent** [comment]
As promised, I have created three issues related to updating the website: #343 #344 #345 #346.

I have updated the proposal at https://github.com/fulldecent/question2answer.org:

 * Now aspires to be moved into q2a/ GitHub user as a separate project, rather than a new branch for the existing repository
 * Justifies choice of GitHub Pages / Jekyll

If the three issues above are resolved then this proposed website is ready to deploy TODAY. Also, it has been checked for valid HTML, broken links, completeness. And a cherry on top: continuous integration is added.

My goal has been to minimize the scope of this transition by making using the most popular technology and getting it done! After migration, we would be able to allow casual contributions and incremental improvements.

**Comment by svivian** [comment]
Hey, sorry for the delay with this. I wanted to take some time thinking it over :)

I'd love to set up a user-contributed documentation system, but I don't think taking over the entire `question2answer.org` site is the best option. Having to move a bunch of scripts, as well as the entire Q2A installation, to subdomains just isn't feasible IMO for reasons I've outlined in various issue tickets.

However, what I think would be a great solution is to set up a subdomain `docs.question2answer.org` that hosts the documentation using Github Pages. This still ticks all your "benefits" listed and allows us to keep control of the main domain in case we want to add anything dynamic in future. I'm happy to stick with Jekyll - hopefully it wouldn't be a barrier to contribution, and is more mature than similar PHP-based tools. Plus you've already done the work :)

So the next steps would be:

1. Create a new repo named `q2a.github.io` as per https://pages.github.com/ ("User or organization site").
2. Add a CNAME file as per https://help.github.com/articles/adding-a-cname-file-to-your-repository/
3. Set up a CNAME `docs` that points to `q2a.github.io`
4. Copy your Jekyll site to the repo.

1 & 3 will need to be handled by @gidgreen, I can do the rest. Let me know if I've missed anything here!

**Comment by fulldecent** [comment]
@svivian I fully support your updated proposal. It has the added benefit that it can be deployed today with zero side effects (because nothing currently points to the new site!)

I willing to be a GitHub "contributor" for this new repository.

After this new site is published then I will send a proposed update for http://question2answer.org/index.php which links to the new docs repository and more clearly shows the separation between the docs and the rest of the site.

**Comment by q2a** [comment]
Hi guys,

I've done steps 1 and 3, and also given you both push rights to the q2a.github.io repo.

When you're ready, please let me know the next steps in terms of integrating into the main Q2A site.

Thanks!

Gideon

**Comment by svivian** [comment]
Great! So from the look of it, @fulldecent you can push your repo direct to this by following the third section on https://github.com/q2a/q2a.github.io

I'll open an issue over there for discussion on organisation and so on.

**Comment by fulldecent** [comment]
I am closing this issue as *solved*. Site is live at https://q2a.github.io/ and discussion can continue at https://github.com/q2a/q2a.github.io

I will create a new issue here to update http://question2answer.org/ to point to our new documentation site.

**Comment by fulldecent** [comment]
@q2a You mention that a CNAME was created.

Please let me know what CNAME was used

**Comment by fulldecent** [comment]
Then the new name can replace https://q2a.github.io/ at https://github.com/q2a/q2a.github.io/blob/master/README.md

**Comment by svivian** [comment]
It's http://docs.question2answer.org/ as requested. The CNAME file in the repo needed to be updated which I've now done.

**Comment by q2apro** [comment]
Sidenote: From http://docs.question2answer.org/ the first link in the top menu (Sites) does not work, it points to http://sites.question2answer.org/ (I am sure, you Scott, know about it.)

**Comment by fulldecent** [comment]
FYI @q2apro that is fixed in https://github.com/q2a/q2a.github.io/commit/95ab4816b14d0026e265b26ae8184fec73907fa4
