### ISSUE TITLE
Add third-party language packs to GitHub release

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#343]
Currently, third-party language packs are hosted on question2answer.org (see http://question2answer.org/addons.php). This implies endorsement but is inefficient for distribution.

To be more efficient, please attached these ZIP files directly here: https://github.com/q2a/question2answer/releases

This will remove file hosting as a required feature of the question2answer.org website and it will bring all of the files associated with a release into the same, versioned, authoritative location.

Benefits include:
- GitHub is secure, http://question2answer.org/ is not (code injection)
- Simpler to find all release files
- More obvious endorsement of these third-party packages
- Reduced responsibility of web server at http://question2answer.org/

**Comment by fulldecent** [comment]
I see that the language packs hosted on http://question2answer.org/ are the old and unmaintained ones for 1.6.x.

It is probably easiest to add these as one big ZIP file ("Additional language extensions") and add to the 1.6.3 release.

This is only regarding the file hosting. The webpage https://github.com/q2a/question2answer/releases will only be changed so that it links to the releases page.

**Comment by svivian** [comment]
> To be more efficient, please attached these ZIP files directly here

What makes this more efficient? Do you mean because the GitHub servers are (presumably) faster than Q2A's? Also, are you suggesting to upload each language pack (German, French, etc) individually? I'm not sure if they would fit as releases, since that's only for the software rather than add-ons.

> GitHub is secure, http://question2answer.org/ is not (code injection)

What do you mean here? If you've found a security flaw with the Q2A website, please let Gideon or myself know the details via email (or PM from the Q2A Q&A). Thanks.

**Comment by fulldecent** [comment]
Regarding efficient, I am just referring to the distribution of all related files in one location.

Regarding security, the website question2answer.org is served over http and files can be modified during transit. Files served from GitHub are served with https which is better. Also, GitHub may provide other information security assurances.

**Comment by svivian** [comment]
Out of interest, do you know of any projects that have 20+ files in their releases? I'm just curious how the page would look.

Also as a general rule we don't add new language keys in patch releases (x.x.1) so I'm not sure how we'd handle that - add the 20 files to every release (1.7.0, 1.7.1, 1.7.2...) or just the first (1.7.0)?

**Comment by fulldecent** [comment]
The easiest way would be one big zip file -- q2a-translations-1.7.1.zip.

An example of a repository that has releases with lots of files is:
 * https://github.com/atom/electron/releases
 * https://github.com/syncthing/syncthing/releases

Also, a project that uses releases creatively is https://github.com/adobe/brackets/releases see how both https://github.com/adobe/brackets/releases/tag/release-1.5%2Beb4 and https://github.com/adobe/brackets/releases/tag/release-1.5 are released base on the same commit but they have different binaries attached. This is a way to get language packs uploaded as a separate release if necessayr.

**Comment by fulldecent** [comment]
Related discussion is at https://github.com/q2a/question2answer/issues/341 However, this issue still remains valid.

**Comment by svivian** [comment]
Overall, I think this is fine as-is. We have the docs on GitHub now so anyone can link their translation from there. Most of the translations themselves are on GitHub too.
