### ISSUE TITLE
Create qa.question2answer.org server and move `/qa/` to there

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#345]
Currently, http://question2answer.org/qa/ contains an installation of Q2A. This part of the site runs different software than the rest of the site.

Because this part of the site is run differently, is managed by different people, and serves a different purpose than the site http://question2answer.org/ (which is focused on marketing and documentation) the /qa/ part should be moved to a different subdomain / server.

Benefits

 - More clear delineation between the two parts of the site which are managed separately
 - Reduced responsibility for the main site (can be static html)

**Comment by svivian** [comment]
How do we handle redirects? As far as I can see from your posts, all we are able to do is create static HTML files which do a "meta refresh" and not the proper 301 redirect. I don't think it will be feasible to create thousands of these (54k by Google's count) for `/qa/...`

**Comment by fulldecent** [comment]
80/20: I just added a redirect for the main page. 

Also attached is a complete list of backlinks to the /qa/ pages:

[www.question2answer.org-backlinksimilarlinks-prefix-03-Jan.csv.zip](https://github.com/q2a/question2answer/files/76785/www.question2answer.org-backlinksimilarlinks-prefix-03-Jan.csv.zip)

The vast majority are copy/paste spam. For the stackoverflow links, I can personally handle those.

~~~~

If we will consider a slower deployment strategy for this transition, then we could do just this one move using current infrastructure, and use 301 with the existing server.

Along this line, we can also still deploy as planned in this proposal. Then rather than changing the DNS setting to point http://question2answer.org/ to GitHub, instead the existing server can be used and can be set as a reverse proxy (one line of Apache configuration) to serve GitHub content.

This solution allows us to respect full semantics for 301, deploy "today", and then simplify the infrastructure after everyone has had "fair notice" of updates based on the 301.

**Comment by fulldecent** [comment]
This is still ready and live to go.

**Comment by DanielRuf** [comment]
Afaik GitHub pages just map one (sub)domain with the CNAME file. So it should be fine to add a DNS entry for the new subdomain which points to the right gh-pages with the right CNAME file and the main website still points to the current server.

Theoretically one single 301 RewriteRule should be enough to route the old qa URIs to the new subdomain.

Regarding the HTML redirect file, we can always parse the requested URI with JavaScript and build a redirect dynamically.

**Comment by fulldecent** [comment]
Closing based on decision at https://github.com/q2a/question2answer/issues/345
