### ISSUE TITLE
Add an email address for feedback

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#346]
Currently contact information for "contacting the creators of Question2Answer directly" is hidden behind a web form at http://question2answer.org/feedback.php

Please instead, publish an email address (spam guarded if necessary) at http://codelair.com/ or if you are ballsy, just paste it here.

Why:

  - Email forms suck
  - Hidden address email form functionality in the http://question2answer.org/feedback.php website is incompatible with opening sourcing that website

**Comment by svivian** [comment]
codelair.com is one of my domains and is unrelated to Q2A, besides having a couple of blog posts on it. And it has no emails associated with it.

Gideon has an `@question2answer.org` address which I assume is where that feedback form goes to. If necessary we can add an address for me, but Q2A itself has a feedback feature so we could use that instead.

**Comment by gurjyot** [comment]
I know this is somewhat different from the issue.
But @svivian how will you make people realise that they can actually contact core devs using Feedback page (because the term feedback means something else) and on a product website like Q2A we need a contact page or some contact info to contact you on professional matters rather than just giving you feedback about Q2A.

**Comment by fulldecent** [comment]
How about add a line to: https://github.com/q2a/question2answer/blob/dev/CONTRIBUTING.md along the lines of:

----

## Contact

You can contact the creators of Question2Answer directly at EMAIL. Please contact us using this form for business issues, to engage in a consulting engagement, and for security matters. For routine discussion of issues with the software and how to use it, please use the other methods below which will have wider exposure.

----

Then the feedback page can be removed and we can link directly to this page.

**Comment by fulldecent** [comment]
Is there an email address to contact core devs? I can create the PR to fix this.

**Comment by svivian** [comment]
I've updated the feedback link in the docs to be clearer, and added a link to the contributing.md file.
