### ISSUE TITLE
Private messages and "User accounts are handled by external code"

### ISSUE THREAD

**Issue by IgorCode** [q2a/question2answer#350]
I'm using q2a 1.7.2 with WordPress integration.

If I go to users profile and click on "Private Messages" I receive error: "User accounts are handled by external code". I believe this error comes from [qa-include/pages/messages.php#L47](https://github.com/q2a/question2answer/blob/dev/qa-include/pages/messages.php#L47):
```
if (QA_FINAL_EXTERNAL_USERS)
	qa_fatal_error('User accounts are handled by external code');
```

From the code above it seems that private messages are not meant to work with WordPress integration, but the link for private messages still exists in user profiles. I'm just starting to get acquainted with q2a but I think this code in [qa-include/app/format.php#L1342](https://github.com/q2a/question2answer/blob/dev/qa-include/app/format.php#L1342):
```
if (!$ismyuser || !qa_opt('allow_private_messages') || !qa_opt('show_message_history'))
	unset($navigation['messages']);
```
is missing a `QA_FINAL_EXTERNAL_USERS ||` condition, right?

**Comment by svivian** [comment]
Yes you're absolutely right. Thanks for spotting that!
