### ISSUE TITLE
fully support IPv6

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#354]
This code part does not work for IPv6 addresses: `COALESCE(INET_ATON(`

An IPv6 address does not have a `.` in its format

At least loginip and createip are affected by this.

**Comment by svivian** [comment]
We had a PR regarding this before - #240 - but unfortunately the IPv6 changes were mixed among other changes that weren't appropriate for Q2A. So if anyone wants to tackle this they can go ahead.

**Comment by DanielRuf** [comment]
Thanks for the link to the PR. Very interesting, because I also use CloudFlare and think more people use it.

I am not sure if we should convert IPs, makes no sense to me.
http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_inet6-aton

I think we just have to adjust the MySQL query.

> mysql> SELECT HEX(INET6_ATON(INET_NTOA(167773449)));
>         -> '0A000509'
> mysql> SELECT INET6_NTOA(UNHEX('FDFE0000000000005A55CAFFFEFA9089'));
>         -> 'fdfe::5a55:caff:fefa:9089'
> mysql> SELECT INET6_NTOA(UNHEX('0A000509'));
>         -> '10.0.5.9'

So instead of `INET_ATON`, use `INET6_ATON` and instead of `INET_NTOA` use `INET6_NTOA`

> SELECT INET6_ATON('fdfe::5a55:caff:fefa:9089')
> fdfe0000000000005a55cafffefa9089
> 
> SELECT INET6_NTOA(UNHEX('fdfe0000000000005a55cafffefa9089'))
> fdfe::5a55:caff:fefa:9089

> SELECT INET6_ATON('10.0.5.9')
> 0a000509
> 
> SELECT INET6_NTOA(UNHEX('0a000509'))
> 10.0.5.9

See? Quite easy. The INET6_ functions handle this without any issue.

**Comment by svivian** [comment]
What version of MySQL do we need for these functions? We may need to use version detection for implementation.

**Comment by DanielRuf** [comment]
When I read the commits at https://github.com/mysql/mysql-server/commits/5.6/sql/item_inetfunc.cc and compare it to the releaes https://github.com/mysql/mysql-server/releases/tag/mysql-5.6.11 and release notes https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-11.html

MySQL 5.6.11 at least, which was released in April 2013.

**Comment by svivian** [comment]
Noticed yesterday that PHP has some functions for handling IPv6: [inet_ntop](http://php.net/manual/en/function.inet-ntop.php)/[inet_pton](http://php.net/manual/en/function.inet-pton.php). Available since 5.1 so might be better to use those for compatibility.

**Comment by DanielRuf** [comment]
Good catch, will test these functions.

**Comment by DanielRuf** [comment]
Seems good, should be fine and a much better replacement and alternative than the native MySQL functions:

https://3v4l.org/ouENQ

```php
// for PHP before 5.4
if ( !function_exists( 'hex2bin' ) ) { 
    function hex2bin( $str ) { 
        $sbin = ""; 
        $len = strlen( $str ); 
        for ( $i = 0; $i < $len; $i += 2 ) { 
            $sbin .= pack( "H*", substr( $str, $i, 2 ) ); 
        } 

        return $sbin; 
    } 
}
echo bin2hex(inet_pton('fdfe::5a55:caff:fefa:9089'))."\n";
echo inet_ntop(hex2bin('fdfe0000000000005a55cafffefa9089'))."\n";
echo bin2hex(inet_pton('10.0.5.9'))."\n";
echo inet_ntop(hex2bin('0a000509'))."\n";
```

Output:
```
fdfe0000000000005a55cafffefa9089
fdfe::5a55:caff:fefa:9089
0a000509
10.0.5.9
```

**Comment by DanielRuf** [comment]
Please let me know if I can prepare some PR for this after testing it locally.

Where would this belong to?
```php
// for PHP before 5.4
if ( !function_exists( 'hex2bin' ) ) { 
```

**Comment by svivian** [comment]
Yes that would be great, thanks. It may be quite a task... IPs are used in quite a few different places. Though I assume there would be no changes to IPv4 usage itself? For example in the "blocked IPs" section, users would still enter `a.b.c.d`

Re polyfills: I've done a little refactoring since your previous PR and moved the polyfills to the `qa_initialize_constants_1` function in qa-base.php. So you could add a file in the vendor folder like you did with password_compat and include that from `qa_initialize_constants_1`.

**Comment by DanielRuf** [comment]
Is this a senseful approach / solution?

- Rename current ip fields.
- Use the old code with the renamed old fields when they are not empty otherwise use the new code.
- Convert old to new IP field if old IP field is not empty and empty the old field afterwards.
- Store all new IPs as hex string in new IP fields with the right type and length

Because we do the decoding with PHP and can fetch both old and new fields in the query and check in the PHP code which one is set and use the right code for the decoding using `bin2hex(inet_pton(` and `inet_ntop(hex2bin(` instead of `INET_ATON` and `INET_NTOA`.

We have these fields (if I did not miss some)
```
cookies.writeip
cookies.createip

iplimits.ip

blobs.createip

posts.lastviewip
posts.lastip
posts.createip

users.createip
users.loginip
users.writeip
```

And some keys:
https://github.com/q2a/question2answer/blob/c6a3629cdc970d81fffafde2f2bb73a3636e1207/qa-include/db/install.php#L329
https://github.com/q2a/question2answer/blob/c6a3629cdc970d81fffafde2f2bb73a3636e1207/qa-include/db/install.php#L337

**Or what should we do with the old data? Convert it directly when we run an upgrade?**

Do not have a final plan for this PR.

PS: https://github.com/q2a/question2answer/blob/c6a3629cdc970d81fffafde2f2bb73a3636e1207/qa-include/db/install.php#L125 The K from KEY should be uppercase.

**Comment by DanielRuf** [comment]
I think I have some SQL code so far, which we can use for the conversion of the existing data.

```sql
ALTER TABLE table MODIFY field VARBINARY(16) NOT NULL;
UPDATE table SET field = UNHEX(HEX(CAST(field AS UNSIGNED)))
```

**Comment by DanielRuf** [comment]
Still need some feedback, if this is the right and a good approach.

**Comment by svivian** [comment]
Hi, sorry for the delay.

> I think I have some working SQL code so far, which we can use for the conversion of the existing data.

The field should allow NULLs, so the query should be more like

    ALTER TABLE `qa_posts` CHANGE `createip` `createip` VARBINARY(16) NULL DEFAULT NULL

Speed-wise, it's quite slow for me. Running it on a copy of my `qa_posts` table (223k rows) took 20s for the alter and 15s for the update. (And even slower on localhost for some reason.)

Multiplying that for all the fields that need to be converted, it does add up. However, there's not really anything else we can do, even adding a new field takes the same amount of time. Since mine is one of the larger sites it will probably be fine for most people.

---

By the way, for checking what the IP address of the user is, we can use `filter_var`:

    if(filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
        // ...
    }
    elseif(filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
        // ...
    }

Where `$ip` is the textual representation of the IP.

---

Side question: apparently `::1` is the equivalent of the IPv4 address `127.0.0.1`. But when I call `inet_pton` on each one I get different output - any idea why? See https://3v4l.org/BVLNo

**Comment by DanielRuf** [comment]
Ok, updated the code in https://github.com/q2a/question2answer/issues/354#issuecomment-177245459

> Multiplying that for all the fields that need to be converted, it does add up. However, there's not really anything else we can do, even adding a new field takes the same amount of time.
Right, because MySQL creates a new empty table with the new structure, inserts the old data, deletes the old table and renames the new one. See http://stackoverflow.com/a/12774774

So we can not do much about this. Very big tables need many hours for this process. It can be improved using triggers but this may not be available on most shared servers.

It also depends on memory and IO throughput.
This is why people should always make a backup before doing some update or upgrade, in any webapplication. 

So the MySQL server did not go away on your side and the queries completed successfully?

> By the way, for checking what the IP address of the user is, we can use filter_var:
Not sure about this but where do we need this? `inet_pton()` / `inet_ntop()` and so on do not depend on the IP version. Might be useful in some places but might not be needed for this PR.

Btw, we don't have to rename the field so MODIFY is enough ;-)
http://stackoverflow.com/a/14767467

> Side question: apparently ::1 is the equivalent of the IPv4 address 127.0.0.1. But when I call inet_pton on each one I get different output - any idea why? See https://3v4l.org/BVLNo

The IPv6 and IPv4 addresses are not equal, so you can not compare them or covnert the one to another. Makes also no sense as in practive people will use some dual stack connection and IPv6 addresses are not the same as IPv4.

See https://tools.ietf.org/html/rfc4291#section-2.2
> For example, the following addresses
> 0:0:0:0:0:0:0:1                the loopback address
> may be represented as
> ::1                            the loopback address

**Comment by svivian** [comment]
One optimisation we can make with the migrations is modifying all the fields in a table at once. When I did that on the `qa_posts` table it took the same time to do the 3 fields as it did for 1. As you mentioned MySQL recreates the table so it only does that once with all field changes.

One other thing - in the "Blocked IPs" section we can enter wildcards and ranges (e.g. `192.168.0.0-192.168.0.31` or `192.168.0.*`). Will this work the same with IPv6? This is the situation I was thinking of with the `filter_var` thing, we might need to detect the type... though we may need something else as `filter_var` isn't gonna work with wildcards.

**Comment by DanielRuf** [comment]
> One optimisation we can make with the migrations is modifying all the fields in a table at once.
Makes sense. Will prepare the PR this weekend. I just want to make sure that I do not oversee something, like `qa_block_ip_match`.



> One other thing - in the "Blocked IPs" section we can enter wildcards and ranges (e.g. 192.168.0.0-192.168.0.31 or 192.168.0.*). Will this work the same with IPv6? This is the situation I was thinking of with the filter_var thing, we might need to detect the type... though we may need something else as filter_var isn't gonna work with wildcards.

Theoretically we can replace wildcard characters with 0.

> Edit: for reference, the relevant function is qa_block_ip_match in app/limits.php. On first glance it looks like it should be simple to handle. For IP ranges, each IP is converted to a number and we check if our IP is between. For wildcards it replaces the * with a regex [0-9]+ so expanding that for hexadecimal like [0-9a-f]+ should be fine.

Will take a look at it and test it for IPv4 and IPv6.

**Comment by DanielRuf** [comment]
Have some working code, please take a look at it and let me know if it is ok.

http://ideone.com/lQj7Cn

**Comment by svivian** [comment]
What's the `inet_ptoi` function for? It's not used in your snippet there.

The IP match doesn't appear to work when mixing IPv4 and IPv6, for example these return false:

    var_dump(qa_block_ip_match("127.0.0.1", "0:0:0:0:0:ffff:7f00:0001"));
    var_dump(qa_block_ip_match("0:0:0:0:0:ffff:7f00:0001", "127.0.0.1"));
    var_dump(qa_block_ip_match("::127.0.0.1", "127.0.0.1")); // IPv4 compatibility mode

**Comment by DanielRuf** [comment]
> What's the inet_ptoi function for? It's not used in your snippet there.

Just for reference, needed a function for converting IP to bigint with BCMath or core Math_BigInteger function.

The used function uses following PHP core functions
http://www.php.net/decbin
http://www.php.net/str_pad
http://www.php.net/unpack
http://www.php.net/base_convert
http://www.php.net/ltrim

They are all availavle for PHP 4, 5 and 7, so I think they are ok to use?
The smaller function which I use might be the better solution than the bigger one.


> // IPv4 compatibility mode
this one is not needed, just input normal IPv4 and IPv6 addresses.
IPv6 and IPv4 addresses are not directly convertible.
Even if a user has a dualstack and uses both, the IP addresses are different and not the same and just one is used.

Have some new code here, we may improve some code parts but so far this also works with your examples (IPv6 & IPv6, IPv4 & IPv4)

http://ideone.com/OFkXz9

**Comment by svivian** [comment]
OK thanks for the explanation, my understanding of IPv6 is still quite rudimentary.

> Have some new code here, we may improve some code parts but so far this also works with your examples (IPv6 & IPv6, IPv4 & IPv4)

That's not working for me for some reason.

**Comment by DanielRuf** [comment]
> That's not working for me for some reason.

Huh, can you give me the errors produced by this and what cde you have used for testing?

**Comment by DanielRuf** [comment]
Is there some reason why we use here MyISAM but InnoDB in all other tables by default? Because MyISAM does not run ANALYZE TABLE after every query like InnoDB and so we

https://github.com/q2a/question2answer/blob/c6a3629cdc970d81fffafde2f2bb73a3636e1207/qa-plugin/event-logger/qa-event-logger.php

These queries should do the conversion part:
```sql
ALTER TABLE ^eventlog MODIFY ipaddress VARBINARY(16) NULL DEFAULT NULL;
UPDATE ^eventlog SET ipaddress = UNHEX(HEX(CAST(ipaddress AS UNSIGNED)));

ALTER TABLE ^cookies MODIFY writeip VARBINARY(16) NULL DEFAULT NULL, MODIFY createip VARBINARY(16) NULL DEFAULT NULL;
UPDATE ^cookies SET writeip = UNHEX(HEX(CAST(writeip AS UNSIGNED))), createip = UNHEX(HEX(CAST(createip AS UNSIGNED)));

ALTER TABLE ^iplimits MODIFY ip VARBINARY(16) NULL DEFAULT NULL;
UPDATE ^iplimits SET ip = UNHEX(HEX(CAST(ip AS UNSIGNED)));

ALTER TABLE ^blobs MODIFY createip VARBINARY(16) NULL DEFAULT NULL;
UPDATE ^blobs SET createip = UNHEX(HEX(CAST(createip AS UNSIGNED)));

ALTER TABLE ^posts MODIFY lastviewip VARBINARY(16) NULL DEFAULT NULL, MODIFY lastip VARBINARY(16) NULL DEFAULT NULL, MODIFY createip VARBINARY(16) NULL DEFAULT NULL;
UPDATE ^posts SET lastviewip = UNHEX(HEX(CAST(lastviewip AS UNSIGNED))), lastip = UNHEX(HEX(CAST(lastip AS UNSIGNED))), createip = UNHEX(HEX(CAST(createip AS UNSIGNED)));

ALTER TABLE ^users MODIFY createip VARBINARY(16) NULL DEFAULT NULL, MODIFY loginip VARBINARY(16) NULL DEFAULT NULL, MODIFY writeip VARBINARY(16) NULL DEFAULT NULL;
UPDATE ^users SET createip = UNHEX(HEX(CAST(createip AS UNSIGNED))), loginip = UNHEX(HEX(CAST(loginip AS UNSIGNED))), writeip = UNHEX(HEX(CAST(writeip AS UNSIGNED)));
```

Please test with a copy / backup of your DB if this works on your side.

Did I forget some field?

**Comment by DanielRuf** [comment]
Please test the PR https://github.com/q2a/question2answer/pull/377

**Comment by DanielRuf** [comment]
@svivian can I somehow reproduce the issue that you had with the latest code sample? Not that there is some bug which still has to be fixed.

**Comment by svivian** [comment]
OK sorry I think I misread your comment about mixing IPv4/IPv6. The bit that wasn't working was my `127.0.0.1` vs `0:0:0:0:0:ffff:7f00:0001` example.

The `qa_block_ip_match` function _can_ be called with mixed IPs though. Q2A sites currently have IPv4 IPs in their blocked list. If a visitor has an IPv6 address then their IP will be compared against the v4 IPs. In which case, I think you're saying they will *never* match, is that right?

**Comment by DanielRuf** [comment]
> In which case, I think you're saying they will never match, is that right? My concern was that if $blockipclause is v4, the function goes ahead and calls ipv6_expand on it anyway. As long as that doesn't return something that matches an IPv6, that's fine.
Eactly. This should always return false. I could doublecheck this and directly retur false if the inputs are diffrent IP versions so all the other checks are skipped.

**Comment by DanielRuf** [comment]
> Exactly. This should always return false. I could doublecheck this and directly retur false if the inputs are diffrent IP versions so all the other checks are skipped.

Added a check in https://github.com/DanielRuf/question2answer/commit/dc752ccd8217d681eb1111efd01f4269d5dca3f5
