### ISSUE TITLE
Improve random data generation

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#355]
We should not use mt_rand, there are much better alternatives in new PHP versions with random_int and random_bytes:
https://github.com/paragonie/random_compat

Also email tokens should use a more secure function in `qa_db_user_rand_emailcode` http://stackoverflow.com/a/18890309/753676

Currently `mt_rand` in `qa_random_alphanum` is used for the generation of an email token.

`qa_db_user_rand_sessioncode` is very short and should use a better implementation

A Facebook file for example uses `hash_hmac('sha256')`.

Just a few things I noticed. Did not look at all code parts and files.

**Comment by svivian** [comment]
For most of the uses in Q2A that shouldn't be a problem. But the session code and email code like you mentioned should be updated.

Do you know if there is a difference between `random_bytes` and `openssl_random_pseudo_bytes`, besides the latter having better support (5.3+)?

**Comment by DanielRuf** [comment]
If we use the random_compat library, it uses `openssl_random_pseudo_bytes` as fallback afaik. But compared to random_bytes, it is not a CSPRNG, it is just a PRNG, it lacks the cryptographically secure part.

Anyway, the native `random_bytes` method also has secure fallbacks and `random_bytes` and `random_int` are the way to go when i comes to library independent code. Also `random_bytes` throws an exception while `openssl_random_pseudo_bytes` returns false when something fails.

**Comment by svivian** [comment]
Additional note for this (or maybe #380) - if the security of `qa_random_alphanum` is improved, we should probably regenerate the `form_security_salt` option that's used in `qa_calc_form_security_hash`.

**Comment by DanielRuf** [comment]
Do you mean recalculate the already stored salt as upgrade step?

**Comment by svivian** [comment]
> Do you mean recalculate the already stored salt as upgrade step?

Yes. Currently it's only used in the CSRF protection, so won't cause any major problems. At worst, a few people will need to resubmit their posts again (they don't lose them).
