### ISSUE TITLE
Set HttpOnly flag for cookies

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#358]
http://php.net/manual/en/session.configuration.php#ini.session.cookie-httponly

http://php.net/manual/en/function.setcookie.php

> httponly
When TRUE the cookie will be made accessible only through the HTTP protocol. This means that the cookie won't be accessible by scripting languages, such as JavaScript. It has been suggested that   this setting can effectively help to reduce identity theft through XSS attacks (although it is not supported by all browsers), but that claim is often disputed. Added in PHP 5.2.0. TRUE or FALSE

**Comment by svivian** [comment]
Yes this makes sense. I don't think there is any reason the login cookie should need to be accessible via JavaScript.

**Comment by DanielRuf** [comment]
Let me know if I should create a PR for this.

I think it makes sense to retrieve the cookie parameter `secure`and manually set the `httponly` parameter to true.

http://php.net/manual/de/function.session-get-cookie-params.php
http://php.net/manual/de/session.configuration.php#ini.session.cookie-secure

Because the `secure` value could be set in .htaccess or in some file with `ini_set`. If it is not set, it should be 0 / false as it enforces https / TLS.

https://www.owasp.org/index.php/SecureFlag

**Comment by svivian** [comment]
Yes you can go ahead and create a PR for httponly cookies.

If I'm not mistaken the secure parameter requires HTTPS. Most Q2A sites are not using HTTPS so we shouldn't enforce that.

**Comment by DanielRuf** [comment]
Yes, I do not enforce it then but if this setting is set by the environment (by .htaccess, ini_set or something else), it uses the setting. This is what I wanted to do with `session_get_cookie_params` here. The last parameter `HttpOnly` will be manually set in the code.

Because I generally use HTTPS for all websites + HSTS ;-)
