### ISSUE TITLE
404 (Not Found) /images/loadingAnimation.gif

### ISSUE THREAD

**Issue by ufukart** [q2a/question2answer#359]
Failed to load resource: the server responded with a status of 404 (Not Found)
/images/loadingAnimation.gif

**Comment by svivian** [comment]
Can you add some more information? Under what circumstances do you get the error? What theme are you using?

There is no file `loadingAnimation.gif` in Q2A or any of the default themes. Could be an issue with an alternate theme.

**Comment by ufukart** [comment]
after your answer, i searhed with notepad++ and i find this image path in q2a-embed plugin.
This plugin; https://github.com/NoahY/q2a-embed
Thank you for your reply. Resolved.
