### ISSUE TITLE
X-Frame-Options, X-XSS-Protection and X-Content-Type-Options headers

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#361]
What do you think about setting the headers for X-Frame-Options, X-XSS-Protection and X-Content-Type-Options?

https://securityheaders.io
https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options

This would harden the website a bit more against possible attacks and should not cause any problems (unlike CSP, which has to be used with caution).

CSP may be more difficult to integrate, as this is not supported in every browser and has to be used with caution (adding allow origins for example) but may be a look worth.

**Comment by svivian** [comment]
These seem like the kind of thing that are better set at the server level rather than app level. For example there's little point Q2A preventing framing if the rest of the website doesn't.

**Comment by DanielRuf** [comment]
You are right. And the XSS and content type setting too?

**Comment by svivian** [comment]
On second thoughts, the content type one would be a good idea for the "blobs" that are served via Q2A.

The XSS one is best left on the server I think. Q2A does have XSS protection anyway so the benefit is minimal.

**Comment by DanielRuf** [comment]
Maybe we just should mention and link to general ressources about hardening webservers as there are also other servers like Nginx, Caddy and so on.

For example 
https://github.com/BetterCrypto/Applied-Crypto-Hardening | https://bettercrypto.org/static/applied-crypto-hardening.pdf
https://github.com/hardening-io/hardening | http://hardening.io/
https://github.com/h5bp/server-configs (the security category in the config files)

I think it makes not much sense to focus only on one webserver when it comes to these headers (which could be also set with PHP). Hardening involves much more things like HTTPS (TLS) with HSTS, CSP, database, and so on.

**Comment by svivian** [comment]
Sounds good. We have a [security page here](http://www.question2answer.org/secure.php) so when we get the new docs up and running you're welcome to update that page :)

**Comment by DanielRuf** [comment]
Ok. Yes, this seems to be a good place for such information. Do we have some label for issues related to the docs?

**Comment by amenezes** [comment]
Hello all. There's a puppet module for enable, configure and manage secure http headers in a simple way. Currently the module can provide configuration for apache2/httpd, nginx and lighttpd.
* [http_hardening][1]

I think that's no doubt about the importance to use secure http headers in web apps. Just look main web sites of tech companies and you can confirm use and support about this feature in your softwares. Still there's references like:
* [secure headers gem from Twitter][2];
* [HSTS in chromium project][3];
* [Useful http headers in OWASP][4].

[1]: https://forge.puppetlabs.com/amenezes/http_hardening
[2]: https://github.com/twitter/secureheaders
[3]: https://www.chromium.org/hsts
[4]: https://www.owasp.org/index.php/List_of_useful_HTTP_headers

**Comment by DanielRuf** [comment]
@amenezes not everyone can run puppet. ;-)

I am not surewhat you mean. Even big sites fail at using these headers. HSTS is just for these who use TLS. And the other headers are also optional. CSP is a bit tricky. Also not every servers sipports setting them via PHP or htaccess as these have to be supported on the server-side.

We just can recommend general guidelines for server hardening but can not force the people to use the headers actually. It's clearly not on our side. gem is not available on most shared servers. We can not recommend specific tools which require specific infrastructures but should point to the guidelines and tools like already mentioned.

**Comment by amenezes** [comment]
@DanielRuf I'm sorry if my last comment I have done some undue promotion of a module of the puppet. It's not my intention. I simply would like to present some ways to use secure headers.

About your comment relative to failure in use of secure headers by big sites, I'm not agree. If you observe web traffic of services available by google, dropbox or microsoft, for example, you will see that secure headers will be present. In greater or lesser extent. Of course there are some that do not use.

I agree that some headers only will make sense in some cases, as well as the hard work in defining appropriate CSP policy, but I still believe in the relevance of this effort to promote more secure and reliable applications. Logical that the measure is not absolute for ensuring all the security of an application, but I see it as an additional layer.

And finally, no one is forced to do anything ;-)

**Comment by DanielRuf** [comment]
@amenezes seems Microsoft does not apply critical headers ;-)

https://securityheaders.io/?q=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2F

Sure, some browsers like Chrome enable the XSS protection by default if the header is not set at all and use the internal XSS Auditor to prevent many but not all XSS attacks, also there are always working bypasses for the XSS Auditor in Chrome and Firefox.

Also other domains and the root website with and without www use none of the headers. At least they do redirects but browsers do not have to follow them, underlying curl and sockets have the according setting and you can not rely on these redirects. Theoretically if you want to secure a domain, you have to a cure all redirects and subdomains too.

It seems microsoft.com is also not on the HSTS preload list and there is no HSTS header on the main domain ;-)

Anyway, we should keep it as simple as possible and provide snippets and instructions for different servers (IIS, Apache, Nginx, Cabby, LiteSpeed, ...).

**Comment by cheri3a** [comment]
you can add this on your conf nginx or apache or any other web server just go to google devloperor mozila devloper

**Comment by DanielRuf** [comment]
> you can add this on your conf nginx or apache or any other web server just go to google devloperor mozila devloper

Sure. But why not mention / link it on the security page? Not everyone knows about these headers.
https://github.com/q2a/question2answer/issues/361#issuecomment-176775742

**Comment by cheri3a** [comment]
check my domain https://www.cheri3a.com/qa/ 
go to network html no css and js check all header 

as i saidd you must change the config files

**Comment by cheri3a** [comment]
nginx config 
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";

**Comment by svivian** [comment]
> On second thoughts, the content type one would be a good idea for the "blobs" that are served via Q2A.

Looked into this a bit more and it turns out the `nosniff` directive only works for CSS and JS, not images. So it's not really relevant for Q2A.

Our [docs are now open source](https://github.com/q2a/q2a.github.io/) so if anyone wants to update the security page with some basic info on these headers (in terms of server-side), go ahead.
