### ISSUE TITLE
Update htmLawed to 1.1.20

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#365]
http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/

**Comment by yerbol89** [comment]
@svivian please update htmLawed. We want to use iframe youtube, vimeo and any video embed in add content.

**Comment by DanielRuf** [comment]
@yerbol89 Do you mean HTML5 features? There is a 1.2 beta version of htmLawed: http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/beta/
