### ISSUE TITLE
Use the new reCAPTCHA API and API client library

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#366]
https://github.com/google/recaptcha
https://developers.google.com/recaptcha/intro

**Comment by svivian** [comment]
We actually are using the new API already, and a modified version of Google's repo. Unless the API changes I don't think we need to update this :)

**Comment by DanielRuf** [comment]
For me it looks like we still use the old 1.0 API https://developers.google.com/recaptcha/old/docs/php
> If you want to use the PHP library to display the reCAPTCHA widget, you'll need to insert this snippet of code inside the <form> element where the reCAPTCHA widget will be placed:
>
>  require_once('recaptchalib.php');

The new and current 2.0 API links to https://github.com/google/recaptcha which uses Composer or the shipped autoloader and has a completely different structure and code.

This seems to be a whole new version https://github.com/google/recaptcha/releases compared to the latest archived versions https://code.google.com/archive/p/recaptcha/downloads.

But the demo should be possibly updated to the latest stable release (1.7.2).

Softaculous uses 1.7.2 ;-)
https://www.softaculous.com/demos/Question2Answer

**Comment by svivian** [comment]
Don't let the filename fool you! We upgraded to the new API a while back (release 1.0.0 from Google's repo), and we're now using a modified version of the 1.1 release. See #302.

Not sure exactly what you mean about the error messages but the script in the line you highlighted is in the file `qa-recaptcha-captcha.php`

**Comment by DanielRuf** [comment]
Right, this confused me. I thought the library is directly used, didn't know that.

> Don't let the filename fool you! We upgraded to the new API a while back (release 1.0.0 from Google's repo), and we're now using a modified version of the 1.1 release

**Comment by DanielRuf** [comment]
It seems I pasted the wrong link.

Meant the part with `code-references` here: https://github.com/google/recaptcha/blob/master/examples/example-captcha.php
