### ISSUE TITLE
Add Atom feeds

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#368]
Atom is an official specification of the IETF and the defacto standard for feeds today.

https://tools.ietf.org/html/rfc4287
https://tools.ietf.org/html/rfc5023

http://www.problogger.net/archives/2006/03/30/rss-vs-atom-whats-the-big-deal/

> RSS has only three required fields on a per item basis- title, link and description. There are a variety of optional fields but some key features, such as a “last updated” field are missing.
> ...
> And my favorite – Atom feeds provide an “updated” field which means that any feeds that are modified have a timestamp associated with them. Trust me when I say I find this useful.

**Comment by svivian** [comment]
Interesting, I thought RSS was the de facto standard. Will look into this.

**Comment by DanielRuf** [comment]
The RSS specification was created by Harvard University and is not very flexible.

http://cyber.law.harvard.edu/rss/rss.html

Many move to Atom feeds and I think it may be good to support also Atom feeds in the future.

The updated field, the extensibility and other features like encoded HTML content and more, may be useful.

**Comment by svivian** [comment]
Closing this for now but I'd accept a PR if anyone wants to write it.
