### ISSUE TITLE
qa_read_blob_file() throws error: failed to open stream

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#372]
In app/blobs.php the `function qa_read_blob_file($blobid, $format)` will throw: 

	failed to open stream: No such file or directory in qa-include/apps/blobs.php

for blobs that are requested via URL and do not exist. 

We should either check if the file exists or surpress this error by using: 

	return @file_get_contents(qa_get_blob_filename($blobid, $format));

I had some weird blob requests, e.g. one for .../favicon.ico.png so I guess also bots are responsible for wrong URLs.

----

Edit: I also get:

	Undefined index: format in /qa-include/qa-blob.php on line 53
	Undefined index: filename in /qa-include/qa-blob.php on line 72

**Comment by q2apro** [comment]
/*
		Read the content of blob $blobid in $format from disk. On failure, it will return false.
		BUGFIX - CHECK IF FILE EXISTS
	*/
	function qa_read_blob_file($blobid, $format)
	{
		$filename = qa_get_blob_filename($blobid, $format);
		if(file_exists($filename))
		{
			return file_get_contents($filename);
		}
		else
		{
			// logging
			error_log('Requested blobid '.$blobid.'does not exist. Filename: '.$filename);
			return null;
		}
	}

**Comment by q2apro** [comment]
The undefined index warning I solved by changing `/qa-include/qa-blob.php` line 50 from: 

	if (isset($blob)) {

to: 

	if (isset($blob) && isset($blob['format']) && isset($blob['filename'])) {

Probably that should go into core as well.

**Comment by svivian** [comment]
OK I think I've fixed this in 18aacb0f1ca616fe987bc2ab871da24a2f077f3c and 768ed4d105674df4af96e968dcd91264ae89fd98

I wasn't getting the undefined index warnings, so can you check that my solution is working for you? Thanks.

**Comment by q2apro** [comment]
You write

	if (isset($blob) && defined('QA_BLOBS_DIRECTORY') && !isset($blob['content']))

but this is not checking for the undefined index of `$blob['format']` and `$blob['filename']`

**Comment by svivian** [comment]
We shouldn't need to check for those because the query always returns those columns, or null which the `isset($blob)` checks for. Are you still getting the PHP Notices?
