### ISSUE TITLE
Warning shows when hosting is down.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#373]
Warning message is shon with hosting a file link. Please add a general Server down message so that other warning is not shown to users.

![yoalfaazprob](https://cloud.githubusercontent.com/assets/6462850/12781307/9705428a-ca99-11e5-9e0f-2086f504d39e.png)

**Comment by svivian** [comment]
You should not have error display turned on in production (the php.ini option `display_errors`).

There's not really anything Q2A can do about that. We could use `ini_set` to attempt to turn it off, but then you wouldn't see any errors in development (localhost).
