### ISSUE TITLE
Could not send email confirmation

### ISSUE THREAD

**Issue by franzpc** [q2a/question2answer#375]
From last update 1.7.3, users cannot register, because Q2A could not send email confirmation, with all themes (include SnowFlat), the same thing occur when a user forgot the password.

 
Question2Answer fatal error:

**Could not send email confirmation**

Stack trace:

require() in index.php:27 
require() in qa-index.php:183 
qa_get_request_content() in qa-page.php:824 
qa_call_override() in qa-page.php:194 
qa_call() in qa-base.php:671 
qa_get_request_content_override_1_in_qa_cv_overrides_php() in qa-base.php:619 
qa_get_request_content_base() in qa-base.php(595) : eval()'d code:9 
qa_call() in qa-base.php(669) : eval()'d code:1 
qa_get_request_content() in qa-base.php:619 
require() in qa-page.php:203 
qa_send_new_confirm() in confirm.php:50

 

Question2Answer fatal error:

**Could not send reset password email**

Stack trace:

require() in index.php:27 
require() in qa-index.php:183 
qa_get_request_content() in qa-page.php:824 
qa_call_override() in qa-page.php:194 
qa_call() in qa-base.php:671 
qa_get_request_content_override_1_in_qa_cv_overrides_php() in qa-base.php:619 
qa_get_request_content_base() in qa-base.php(595) : eval()'d code:9 
qa_call() in qa-base.php(669) : eval()'d code:1 
qa_get_request_content() in qa-base.php:619 
require() in qa-page.php:203 
qa_start_reset_user() in forgot.php:71

**Comment by gurjyot** [comment]
I just checked your problem on my website (which is on Q2A 1.7.3), but it is working just fine. I am getting mail for user account confirmation. So the problem maybe somewhere else.

**Comment by svivian** [comment]
As I mentioned on the Q2A site, it's an issue with a function override for `qa_get_request_content`. Do you have a plugin that overrides that function?

**Comment by svivian** [comment]
@franzpc Any luck with diagnosing the problem? The `qa_cv_overrides` part looks to be from the comment voting plugin. I tried installing that but there were no problems there.

Nothing has changed in the `app/emails.php` code. The only relevant thing that changed was upgrading PHPMailer. You could try downgrading to 5.2.13 ([download here](https://github.com/PHPMailer/PHPMailer/releases), copy files to `qa-include/vendor/PHPMailer`) and see if that helps.

**Comment by franzpc** [comment]
@svivian Thank´s a lot, I changed to 5.2, now is running.

**Comment by svivian** [comment]
Interesting... must be a bug in PHPMailer then. Are there any other errors in your logs from PHPMailer itself?

**Comment by franzpc** [comment]
@svivian I don´t have anymore problem with PHPMailer.

I would like to know hot to put ads in the content on the answers, I have SnowFlat Theme.

**Comment by svivian** [comment]
One way would be to create a layer plugin that overrides one of the theming functions like `a_view()` and puts your ad code in. Check the docs for more details. If you have any further questions, feel free to ask on the [Q2A Q&A](http://www.question2answer.org/qa/).

**Comment by shionphan** [comment]
@svivian I had config mail as smtp, errors always display

**Comment by Eniyi** [comment]
unfortunetely I have this problem too, and upgrading phpmailler didnt help :( , any other idea ?
