### ISSUE TITLE
Vote box gap is showing on some pages after Q2A 1.7.3 update

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#378]
On pages where vote box is not shown, there a gap equal to vote box is showing between answer count box and the question. This has happened after Q2A 1.7.3 update, before this update it was just perfect. 

![test](https://cloud.githubusercontent.com/assets/6462850/12879155/08bd7d8e-ce55-11e5-9853-5cca22df8a5e.png)

**Comment by gurjyot** [comment]
I just checked most of the pages, and the pages which are showing this issue are "Recent Activity" and "All Answers". I do not think it is happening on any other page.

**Comment by svivian** [comment]
OK thanks, I've fixed this now.
