### ISSUE TITLE
use hash_equals

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#379]
http://php.net/manual/en/function.hash-equals.php
> (PHP 5 >= 5.6.0, PHP 7)
hash_equals — Timing attack safe string comparison

For older PHP versions: http://php.net/manual/en/function.hash-equals.php#115635

https://github.com/q2a/question2answer/blob/c6a3629cdc970d81fffafde2f2bb73a3636e1207/qa-include/app/users.php#L359

https://github.com/q2a/question2answer/blob/c6a3629cdc970d81fffafde2f2bb73a3636e1207/qa-include/app/users.php#L1144

Did just a quick search on GitHub with the master branch. There might be more places.

**Comment by svivian** [comment]
Would a timing attack over the internet would ever be feasible, given that the comparison would be microseconds? This is certainly something we could add though.

**Comment by DanielRuf** [comment]
> Would a timing attack over the internet would ever be feasible, given that the comparison would be microseconds?

Definitely.

http://blog.ircmaxell.com/2014/11/its-all-about-time.html

**Comment by svivian** [comment]
OK fair enough. If you want to do a PR, feel free.

**Comment by DanielRuf** [comment]
Ok.

**Comment by DanielRuf** [comment]
Resolved with https://github.com/q2a/question2answer/pull/389
