### ISSUE TITLE
use hash_hmac

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#380]
Session codes and other things should use `hash_hmac` if possible.

https://en.wikipedia.org/wiki/Hash-based_message_authentication_code

`hash_hmac` signs the hashes so we can verify if they are really created by this server and not forged

http://stackoverflow.com/a/8954943

http://php.net/manual/en/function.hash-hmac.php
http://php.net/manual/en/function.hash-hmac.php#93440

But this might be trickier and not the ideal solution as it requires the hash extension.

Using `hash_hmac` would also improve the CSRF tokens and there is also a script for generating secure CSRF tokens (but uses `hash_hmac`). https://github.com/paragonie/anti-csrf

At least https://github.com/q2a/question2answer/issues/379 should be implemented.

**Comment by svivian** [comment]
According to the manual [here](http://php.net/manual/en/hash.requirements.php) the hash functions are part of the core.

However I'm not seeing the benefit to this (I might be misunderstanding the function). Is there a situation where someone could create a legitimate CSRF token and get a user to post a form to Q2A?

**Comment by DanielRuf** [comment]
At least this is an unsigned SHA1 hash using a salt generated using mt_rand (I think we already had the discussion about random_compat for qa_random_alphanum and other functions).

All the other parameters are either static ore timebased. At least the generation of the salt should be hardened / improved.

HMAC also signs the hash so we can verify that it is really created by the script.

But currently HMAC might not be necessary.

**Comment by svivian** [comment]
> HMAC also signs the hash so we can verify that it is really created by the script.

How does this work? I tried using the function on my computer, then on 3v4l.org and I get the same hash. How do you verify where it's created?

**Comment by DanielRuf** [comment]
HMAC prevents tmining and length extension attacs and also collissions in the underlying hashing algorithm.

http://crypto.stackexchange.com/questions/15071/why-concatenate-the-key-a-second-time-in-hmac

**Comment by svivian** [comment]
OK guess I misunderstood what is meant by "signed". The only verification that it's created by the script is the key/salt. Improving the salt generation solves that issue. But obviously the timing and length attacks are something that can be solved.

**Comment by DanielRuf** [comment]
Theoretically we could use the current salt as key for the HMAC function so this should be easy for the first migration. It seems we also do not need the polyfill as the Hash extension is bundled with PHP 5.1.2+

http://php.net/manual/en/hash.installation.php
> As of PHP 5.1.2, the Hash extension is bundled and compiled into PHP by default.
