### ISSUE TITLE
Answer box remains green even if the answer is deleted

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#384]
If an answer is selected as "Best answer" and then deleted due to some reason then in questions list, the answer count box shows "0 answers" but the box remains in green colour.

Or maybe the answer has been converted to a comment (quite not sure about this).

**Comment by svivian** [comment]
This may be the same issue as #79, which has been fixed for v1.8.

The change in 8c4db57c71383cf679f0992311430843b4dff764 is quite small, so perhaps you can add those lines on your site and check it solves the issue for you?

**Comment by svivian** [comment]
Checked into this and it was occurring when converting an answer into a comment. Fixed in b7cb859d28a69383b2db32775d2328e50cfeb184
