### ISSUE TITLE
Improving the performance of function qa_db_related_qs_selectspec()

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#385]
Just did some more debugging on the question pages and found out that: 

	SELECT qa_posts.postid, qa_posts.categoryid, qa_posts.type, LEFT(qa_posts.type, 1) AS basetype, INSTR(qa_posts.type, '_HIDDEN')>0 AS hidden, qa_posts.acount, qa_posts.selchildid, qa_posts.closedbyid, qa_posts.upvotes, qa_posts.downvotes, qa_posts.netvotes, qa_posts.views, qa_posts.hotness, qa_posts.flagcount, qa_posts.title, qa_posts.tags, UNIX_TIMESTAMP(qa_posts.created) AS created, qa_posts.name, qa_categories.title AS categoryname, qa_categories.backpath AS categorybackpath, CONCAT_WS(',', qa_posts.catidpath1, qa_posts.catidpath2, qa_posts.catidpath3, qa_posts.categoryid) AS categoryids, qa_uservotes.vote AS uservote, qa_uservotes.flag AS userflag, qa_userfavorites.entityid<=>qa_posts.postid AS userfavoriteq, qa_posts.userid, qa_posts.cookieid, INET_NTOA(qa_posts.createip) AS createip, qa_userpoints.points, qa_users.flags, qa_users.level, qa_users.email AS email, qa_users.handle AS handle, BINARY qa_users.avatarblobid AS avatarblobid, qa_users.avatarwidth, qa_users.avatarheight, score FROM qa_posts LEFT JOIN qa_categories ON qa_categories.categoryid=qa_posts.categoryid LEFT JOIN qa_uservotes ON qa_posts.postid=qa_uservotes.postid AND qa_uservotes.userid='1' LEFT JOIN qa_userfavorites ON qa_posts.postid=qa_userfavorites.entityid AND qa_userfavorites.userid='1' AND qa_userfavorites.entitytype='Q' LEFT JOIN qa_users ON qa_posts.userid=qa_users.userid LEFT JOIN qa_userpoints ON qa_posts.userid=qa_userpoints.userid JOIN (SELECT postid, SUM(score)+LOG(postid)/1000000 AS score FROM ((SELECT qa_titlewords.postid, LOG(10000/titlecount) AS score FROM qa_titlewords JOIN qa_words ON qa_titlewords.wordid=qa_words.wordid JOIN qa_titlewords AS source ON qa_titlewords.wordid=source.wordid WHERE source.postid=319014 AND titlecount<10000) UNION ALL (SELECT qa_posttags.postid, 2*LOG(10000/tagcount) AS score FROM qa_posttags JOIN qa_words ON qa_posttags.wordid=qa_words.wordid JOIN qa_posttags AS source ON qa_posttags.wordid=source.wordid WHERE source.postid=319014 AND tagcount<10000) UNION ALL (SELECT qa_posts.postid, LOG(10000/qa_categories.qcount) FROM qa_posts JOIN qa_categories ON qa_posts.categoryid=qa_categories.categoryid AND qa_posts.type='Q' WHERE qa_categories.categoryid=(SELECT categoryid FROM qa_posts WHERE postid=319014) AND qa_categories.qcount<10000)) x WHERE postid!=319014 GROUP BY postid ORDER BY score DESC LIMIT 4) y ON qa_posts.postid=y.postid WHERE (qa_posts.closedbyid IS NULL)

Uses: 

	47.77 ms - 4 rows - 36 columns

From my total mysql load time of 75.9 ms. 

This is indeed a lot, about 63 % only for the related questions.

So my question, how can we improve this. Change the query? 

Ref: https://github.com/q2a/question2answer/blob/dev/qa-include/db/selects.php#L686

----

Update: Another question page performed with: 

	15.42 ms - 4 rows - 36 columns

**Comment by svivian** [comment]
Yes I've also noticed this in my testing. A good candidate for caching :)

**Comment by amiyasahu** [comment]
I too found the same issue. caching this would be a great idea :+1:

**Comment by svivian** [comment]
Caching for this has been added in the latest commits.

**Comment by q2apro** [comment]
Could you link the commit if you refer to it? Would help a lot. Thanks.

**Comment by svivian** [comment]
The specific commit for related questions is f748dd63

But that relies on several of the previous commits from https://github.com/q2a/question2answer/commits/1.8
