### ISSUE TITLE
add CKEditor markdown addon

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#386]
http://ckeditor.com/addon/markdown
https://github.com/hectorguo/CKEditor-Markdown-Plugin

**Comment by svivian** [comment]
Thanks for the suggestion, but I don't think this makes sense for the core. You can customise the CKeditor yourself, see the `CUSTOMIZE.md` file in the plugin for instructions. There is also a separate [Markdown editor that I made](https://github.com/svivian/q2a-markdown-editor) if that suits.

P.S. The Github repo is intended for bugs/issues only. We can discuss features over at the [Q2A site](http://www.question2answer.org/qa/) :)

**Comment by DanielRuf** [comment]
> There is also a separate Markdown editor that I made if that suits.

Much better. Thanks, will use this.

> We can discuss features over at the Q2A site :)

Okay, GitHub is just better to keep track of the things in combination with codes but will discuss further features on the mentioned website (when I have created an account there) =)

**Comment by svivian** [comment]
Thanks. I don't mind discussions that relate directly to the code like your security tickets (although those are closer to bugs anyway). I simply prefer to keep requests separate to avoid clogging up the Issues tab. Q2A also has voting so we can gauge how popular features are.

**Comment by DanielRuf** [comment]
I totally understand and you are right, this issue was not directly code or security related, should have filed a feature request at the Q2A site. 

Will do one PR after another to have a clean workspace and avoid possible conflicts.

Any news / feedback about my IPv6 PR?

**Comment by svivian** [comment]
> Any news / feedback about my IPv6 PR?

I will get to it when I can, hopefully this week. Been busy with work and trying to sort out a few other things.

**Comment by DanielRuf** [comment]
Ok, no problem.
