### ISSUE TITLE
Implementing a user bridge

### ISSUE THREAD

**Issue by Guite** [q2a/question2answer#390]
I need to incorporate Q&A into another system. There are two different modes planned: 1st embed a sidebar showing the latest questions as well as a possibility to post a new one (I thought that this sidebar could be included using an iframe probably); 2nd the whole application called standalone like usual (could also be included using an iframe to simplify reusing common layout, that is header and footer).

To cope with this there is some kind of user bridge required, because there are already users existing. So Q&A should reuse their settings, like name and avatar.

What would be the correct approach for such an integration? Implement a `login module` and doing the core logic in `check_login()`? What else must be considered?

Thanks for your advice.

**Comment by phy25** [comment]
http://www.question2answer.org/single-sign-on.php

If you have further questions just ask them on http://www.question2answer.org/qa/

**Comment by Guite** [comment]
Thank you!
