### ISSUE TITLE
How to remove q2a?

### ISSUE THREAD

**Issue by sebuls** [q2a/question2answer#391]
I installed q2a on a site. But I got many spams. So I removed all files in q2a directory from that site. But I think that this is not all. How to remove q2a DB from this site? I can use phpMyAdmin.

I will reinstall q2a.

**Comment by phy25** [comment]
Just drop all tables prefixed with "qa_" or the value of `QA_MYSQL_TABLE_PREFIX` in `qa-config.php`. Be careful and don't delete other app's tables.

If you have further questions just ask on http://www.question2answer.org/qa/

**Comment by svivian** [comment]
And don't forget to set up reCAPTCHA on the new site, it stops spam pretty well.
