### ISSUE TITLE
Enable phpcs

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#399]
phpcs is currently disabled in Travis.

We can enable it to automatically find any problems with code style. If this is done then we can also update https://github.com/q2a/question2answer/blob/dev/CONTRIBUTING.md coding style section to mention:

> Check if your code is formatted correctly by running this one command: COMMAND

**Comment by fulldecent** [comment]
Related: #400

**Comment by svivian** [comment]
I've removed phpcs for now until we have a chance of passing :) Will add it back when I reformat the code prior to v1.8 release.

**Comment by fulldecent** [comment]
Sounds good, I'll leave code formatting to you :-) I won't get involved until after dev and 1.8 merge
