### ISSUE TITLE
Q2A logo

### ISSUE THREAD

**Issue by techtonik** [q2a/question2answer#402]
I reworked logo a bit to fit square dimensions. Hope you will find it useful (as favicon etc.)
.
![question2answer](https://cloud.githubusercontent.com/assets/515889/14121334/a34bfcbe-f5ff-11e5-9922-455a151231d2.png)

Attached is also final GIMP save with layers.

[question2answer.xcf.zip](https://github.com/q2a/question2answer/files/194200/question2answer.xcf.zip)

**Comment by svivian** [comment]
Thanks for the effort, but I think it's a little bit cramped and hard to read. We currently use just the orange question mark as the favicon on the Q2A site, and a 'padded' logo [on Twitter](https://twitter.com/Q2Answer) which I think works quite well already.

**Comment by techtonik** [comment]
As you wish. You may want to upload Twitter logo somewhere. I wouldn't do this if I could find the logo.

**Comment by svivian** [comment]
OK we can probably add our logo from Twitter to the docs. Out of interest, what are you using the logo for?

**Comment by techtonik** [comment]
For software detection - https://github.com/AliasIO/Wappalyzer/pull/1127

**Comment by svivian** [comment]
OK cool. Feel free to use our logo from Twitter if you like.
