### ISSUE TITLE
createip is null even though ipaddress is set - Possible issue with INET_ATON(#)

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#404]
I have written some code that prevents users with createip==null to post. 

    // prevent anonymous users without IP to answer or comment, allow on ask page
    public function form_buttons($form, $columns)
    {
        $isaskpage = ($this->template == 'ask');
        $userid = qa_get_logged_in_userid();
        $userip = qa_remote_ip_address();
        if($isaskpage || !empty($userip) || isset($userid))
        {
            // call default method output
            qa_html_theme_base::form_buttons($form, $columns);
        }
    } 

I am using `function qa_remote_ip_address()` which reads the IP address by: `@$_SERVER['REMOTE_ADDR'];`

And the IP address is saved to the database by `COALESCE(INET_ATON(#), 0)`

I am quite sure that there is a problem with `INET_ATON(#)` because my code would not allow the user to answer (removes buttons) if the IP is null. However, I still have users without IP (null) who do post in my forum. Thus the IP is there but not saved to the database correctly!

**Comment by svivian** [comment]
It's possible this is fixed by the changes coming in 1.8 (IPv6 support). Do you know what the value of `$_SERVER['REMOTE_ADDR']` is for those users? As far as I know it's impossible for that to be NULL, but if your server supports IPv6 then it could be something like `1234:abcd::9876`.

**Comment by q2apro** [comment]
I have just tried: 

   UPDATE qa_posts 
   SET createip = COALESCE(INET_ATON("2a00:8640:1::224:36ff:feef:1d89"), 0)
   WHERE postid = 1

which leads to a value of `0` for `createip` but not `NULL` as I hoped.

I have checked the server log times and the database posts, I could track down one visitor. He got createip NULL and had the IP: ... (moment)

**Comment by svivian** [comment]
This is all fixed in 1.8. Unfortunately because it required major changes, it's not possible to integrate into 1.7. The link you posted has nothing to do with IPv6 so won't help.

If you have MySQL 5.6+ you could try changing all the IP columns to `VARBINARY(16)` and then replacing all occurrences of `INET_ATON` with `INET6_ATON`, and `INET_NTOA` with `INET6_NTOA`. Can't guarantee it will work though.

**Comment by q2apro** [comment]
Bad luck for me and my users. So I have to wait for v.1.8 ...
