### ISSUE TITLE
Using qa_db_query_sub() removes leading zero of given value

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#408]
I am using the following query: 

		qa_db_query_sub(
			'INSERT INTO ^booking_users (userid, 'phone') VALUES(#, #) ON DUPLICATE KEY UPDATE `phone`=#',
				$userid, $value, $value
		);

As soon as $value has a leading zero, the `0` is not saved into the database but removed!

For example, `0123456789` becomes `123456789`.

What is going on? I would say the `qa_db_query_sub()` respectevly the called `qa_db_apply_sub()` is filtering out the leading `0` somewhere.

**Comment by q2apro** [comment]
Update: 

The $query in results in: 

	INSERT INTO qa_booking_users (userid, phone) VALUES(1, 0123456789) ON DUPLICATE KEY UPDATE `phone`=0123456789

which is correct.

However, since the VALUES are not in question marks, the 0123456789 is treated obviously as number and not string and becomes 123456789.

Looks to me like we need to add quotes around the value here.

**Comment by gidgreen** [comment]
Use `$` rather than `#` in the query template to represent a string rather than number substitution. See `qa_db_apply_sub()` for the logic of how those are applied.

**Comment by q2apro** [comment]
Oh, I have not seen the comment for qa_db_apply_sub(). Now it is clear. Thank you!

Correct query is now: 

    qa_db_query_sub(
        'INSERT INTO ^booking_users (userid, 'phone') VALUES(#, $) ON DUPLICATE KEY UPDATE `phone`=$',
            $userid, $value, $value
    );
