### ISSUE TITLE
Integration with moodle

### ISSUE THREAD

**Issue by franzpc** [q2a/question2answer#410]
Could be fantastic if Q2A can integrate with Moodle 3, through a plugin.

**Comment by svivian** [comment]
What is Moodle? If it's something with a user system then you can write a plugin to integrate with it. It's unlikely that Q2A would add a plugin to core.

**Comment by DanielRuf** [comment]
Moodle is an opensource elearning software written in PHP. Quite complex in some code parts. Often plugins have to be updated for new minor releases.

Not sure but Moodle uses just a few tables for users.

Are there more Moodle users requesting this?

**Comment by svivian** [comment]
If you'd like someone to write a plugin for you, try asking on the [Q2A site](http://www.question2answer.org/qa/), someone may be able to help you.
