### ISSUE TITLE
Password with whitespace at the end doesn't work

### ISSUE THREAD

**Issue by fzoske** [q2a/question2answer#412]
Hi,

we added a plugin for login through LDAP/AD and encountered a bug with the login process.

One person had a white space in her password which got trimmed in qa_post_text().

I coded a workaround like the following:
```diff
--- qa-base.ori.php     2016-04-28 13:42:15.802140582 +0200
+++ qa-base.php 2016-04-28 13:35:22.349604966 +0200
@@ -1008,7 +1008,7 @@
        {
                if (qa_to_override(__FUNCTION__)) { $args=func_get_args(); return qa_call_override(__FUNCTION__, $args); }

-               return isset($_POST[$field]) ? preg_replace('/\r\n?/', "\n", trim(qa_gpc_to_string($_POST[$field]))) : null;
+               return isset($_POST[$field]) ? preg_replace('/\r\n?/', "\n", $field !== 'password' ? trim(qa_gpc_to_string($_POST[$field])) : qa_gpc_to_string($_POST[$field])) : null;
        }

        function qa_post_array($field)

```

Can you include this in Question2Answer? Shall I open a PR?
Or do you have a better solution for this?

Regards,
Fabian

**Comment by svivian** [comment]
Hi, sorry for the late reply. I'm not sure if we would be able to implement that, as any user who already used spaces would no longer be able to log in. Having said that, they should be able to reset their password, and it's probably a rare occurrence.

**Comment by fzoske** [comment]
Thx for reply.

I can't image any case in which not trimming the password could cause problems.
Can you tell me any case where you see a problem with the suggested change?

**Comment by svivian** [comment]
Yes, the case is as I described - if a user has already registered with a space at the end of their password, and we stop trimming spaces, then they won't be able to log in.
