### ISSUE TITLE
question about OOP and the use of q2a code

### ISSUE THREAD

**Issue by GitFuture** [q2a/question2answer#413]
The q2a  is great, but i'd like to ask why not use **OOP** to built website.
 I think It may be much better to understand the source code and more helpful for those like me who want to learn how to built a website with php and the q2a source code. 
And I want to ask that I have used a lot of codes from q2a to built my own website. 
I just use many classes to write the codes.  I have uploaded my source code into my github.  Will it be ok or shall I make some other statements?

**Comment by svivian** [comment]
Hi, I'm the current main developer. I can't really speak for exactly why Gideon (the original dev) made it that way.

However, it is something I am working towards. It's not an easy thing to do as we try to keep backwards compatibility where possible. We have a lot of plugins now so it must be easy for plugin devs to upgrade.

Hope that helps explain.

**Comment by GitFuture** [comment]
Oh, I didn't realize that there are so many plugins in q2a. There must be so many troublesome problems besides the plugins when upgrading that you need to consider about. 

I'm learing php and q2a and I'm using them in my favorite way.  I hit the problem that was questioned in this issue when coding. 

Thank you for reply.
