### ISSUE TITLE
developing plugins

### ISSUE THREAD

**Issue by babitabhandari** [q2a/question2answer#414]
how to develop rich snippets plugin in php.Can you tell me

**Comment by phy25** [comment]
http://docs.question2answer.org/plugins/
2016年5月17日 下午1:13，"babita bhandari" <notifications@github.com>写道：

**Comment by babitabhandari** [comment]
But using this code it shows syntax errors.

**Comment by DanielRuf** [comment]
> But using this code

Which code exactly? Which Q2A version do you use? What did you try so far?

**Comment by svivian** [comment]
Closing this. If you have more questions, please ask on the [Q2A site](http://question2answer.org/qa/), thanks.
