### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#415]
question2answer.org should provide a valid TLS certificate so we can also use the protocol relative URLs pointing to this domain and make the upcoming release fully https compatible.

**Comment by twins16** [comment]
which server name if you want a ssl use ubuntu 14.04 install LEFM CONFIGURATION AND THAN INSTALL 
LET'S ENCYPTE CORECTLLY THAN RUN  IT IT'S FOR ME COORECTLY 100% 
LOOK HER https://www.cheri3a.com/qa

**Comment by svivian** [comment]
Gideon didn't seem overly keen when I asked him, probably it's a bit of hassle on Q2A's current server. Maybe in the future this will get done.

**Comment by DanielRuf** [comment]
I hope so. Because this could be misused for attacks (MITM and other types).
