### ISSUE TITLE
Page not loading on qa and error in error.log

### ISSUE THREAD

**Issue by samerafach** [q2a/question2answer#423]
Hi there:

Only half of some page loads (only the part with the question) and I'm getting this error:

	[Wed Jun 29 19:00:25.413891 2016] [:error] [pid 7142] [client 127.0.0.1:35861] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /somepath/qa/qa-include/qa-base.php(595) : eval()'d code:88
	Stack trace:
	#0 /somepath/qa/qa-include/qa-theme-base.php(1779): qa_layer_3_from_wordpress_names_php->post_meta(Array, 'qa-q-view',NULL, '<br/>')
	#1 /somepath/qa/qa-include/qa-theme-base.php(2068): qa_html_theme_base->post_avatar_meta(Array, 'qa-q-view')
	#2 /somepath/qa/qa-include/qa-theme-base.php(2038): qa_html_theme_base->q_view_main(Array)
	#3 /somepath/qa/qa-include/qa-theme-base.php(798): qa_html_theme_base->q_view(Array)
	#4 /somepath/qa/qa-include/qa-theme-base.php(765): qa_html_theme_base->main_part('q_view', Array)
	#5 /somepath/qa/qa-include/qa-theme-base.php(672): qa_html_theme_base->main_parts(Array)
	#6 /somepath/qa/qa-include/qa-theme-base.php(395): qa_html_theme_base->main()
	#7 /somepath/qa/qa-include/qa-theme-base.php(342): qa_html_theme_base->body_content()
	#8 /somepath/qa/qa-include/qa-th in /somepath/qa/qa-include/qa-base.php(595) : eval()'d code on line 88, referer: https://qa.example.com/

I use version 1.7.4. There's no permission problems, as the whole qa directory is owned by www-data and I verified that they're accessible by it.

What is this caused by? I'm glad to provide more information.

**Comment by phy25** [comment]
It should be the problem of your custom theme or something. Search for `qa_layer_3_from_wordpress_names_php`.

    #0 /somepath/qa/qa-include/qa-theme-base.php(1779): qa_layer_3_from_wordpress_names_php->post_meta(Array, 'qa-q-view',NULL, '<br/>')
    #1 /somepath/qa/qa-include/qa-theme-base.php(2068): qa_html_theme_base->post_avatar_meta(Array, 'qa-q-view')

**Comment by svivian** [comment]
The `qa_layer_3_from_wordpress_names_php` part implies this is coming from a layer plugin - some kind of Wordpress names plugin? There is no `DOMDocument` used anywhere in Q2A so the error cannot be from Q2A itself.

**Comment by samerafach** [comment]
I reinstalled Q2A and it works now...
