### ISSUE TITLE
Dublicate content error answers page url start=

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#424]
My site google webmasters i see dublicate content.
`<link rel="canonical" dublicate url.`

Dublicate description, title

Example:
Its normal page.

```
view-source:http://www.question2answer.org/qa/31514/what-do-you-want-in-question2answer-1-7
<link rel="canonical" href="http://www.question2answer.org/qa/31514/what-do-you-want-in-question2answer-1-7">
<link rel="next" href="../31514/what-do-you-want-in-question2answer-1-7?start=12#a_list_title" >
```

After i botton next page answers.

```
view-source:http://www.question2answer.org/qa/31514/what-do-you-want-in-question2answer-1-7?start=12#a_list_title
<link rel="canonical" href="http://www.question2answer.org/qa/31514/what-do-you-want-in-question2answer-1-7?start=12">
<link rel="prev" href="../31514/what-do-you-want-in-question2answer-1-7?start=0#a_list_title" >
```

> Parametr ?start=12 dublicate content. How i delete ?start=\* in site.

**Comment by svivian** [comment]
What are the actual 'start' values you're seeing for your site? (The one that is giving you the duplicate content notice)

And how many answers do you have set per page? Have you changed this in the past? The problem with the 'start' parameter is that any number can be put in there regardless of answers per page, eg 'start=1'

Could also be a problem with the same question appearing on each page. Not sure there's a way to solve that.

**Comment by yerbol89** [comment]
https://moz.com/learn/seo/duplicate-content

**Comment by yerbol89** [comment]
https://github.com/q2a/question2answer/blob/4fce0eb2390f56b645dad375d1d81e9f91a97e69/qa-include/pages/question.php#L337

Delete: ($pagestart>0) ? array('start' => $pagestart) : null, qa_opt('site_url')

$qa_content['canonical']=qa_path_html(qa_q_request($question['postid'], $question['title']));

**Comment by svivian** [comment]
Checked into this and the way we do it now is correct. See [Google blog](https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html)L

> **Mistake 1: rel=canonical to the first page of a paginated series**
>
> Specifying a rel=canonical from page 2 (or any later page) to page 1 is not correct use of rel=canonical, as these are not duplicate pages. Using rel=canonical in this instance would result in the content on pages 2 and beyond not being indexed at all.

And then it says to use `rel="next"` which we do.

BTW you may want to look at the "URL Parameters" section in Search Console (new name for webmaster tools), in there you should see the `start` parameter in the table. Set that to "Paginates" and "Let Googlebot decide". Should solve any problems you're having.
