### ISSUE TITLE
Undefined index: content in /qa-include/qa-theme-base.php on line 2328 (comment)

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#425]
PHP Notice:  Undefined index: content in /qa-include/qa-theme-base.php on line 2328 (q2a v1.7.1): 

https://github.com/q2a/question2answer/blob/dev/qa-include/qa-theme-base.php#L2325

```
public function c_item_content($c_item)
{
    $this->output('<div class="qa-c-item-content">');
    $this->output_raw($c_item['content']);
    $this->output('</div>');
}
```

I could not track down the reason why it is undefined, but obviously there is such a case (no plugin interfering). Maybe it has to do with C_HIDDEN?

Suggestion: Check if isset().

**Comment by svivian** [comment]
It's possible the missing content was due to the old bug with emojis getting removed in MySQL. Either way it's good practice to check the element exists before trying to output it so I've added that.
