### ISSUE TITLE
1.8 version error microdata upvoteCount

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#433]
Today i install my site 1.8 version. Its nice work. I enable cache. Its work nice.

I enable Use schema.org microdata:
But i see this error.
**The property upvoteCount is not recognized by Google for an object of type QAPage**

https://search.google.com/structured-data/testing-tool?hl=en#url=https%3A%2F%2Fsurak.szh.kz%2F632252%2F%25D1%2588%25D0%25B5%25D0%25BA%25D1%2582%25D1%2596-%25D0%25B6%25D0%25B8%25D0%25B5%25D0%25BD%25D0%25B5%25D0%25B9-%25D1%2580%25D1%2583%25D1%258B%25D0%25BD%25D1%258B%25D2%25A3-%25D1%2582%25D0%25BE%25D0%25BB%25D1%258B%25D2%259B-%25D1%2588%25D0%25B5%25D0%25B6%25D1%2596%25D1%2580%25D0%25B5%25D1%2581%25D1%2596-%25D0%25BA%25D0%25B5%25D1%2580%25D0%25B5%25D0%25BA-%25D0%25B5%25D0%25B4%25D1%2596

**Comment by svivian** [comment]
You are missing the attributes on the `qa-main` div. It's probably an issue with your theme. Check the functions in your `qa-theme.php` and compare to those in `qa-theme-base.php`.

You probably need these two lines:

	$extratags = isset($this->content['main_tags']) ? $this->content['main_tags'] : '';
	$this->output('<div class="qa-main'.$hidden.'"'.$extratags.'>');

**Comment by svivian** [comment]
It would be [line 358](https://github.com/amiyasahu/Donut/blob/master/qa-theme/Donut-theme/qa-donut-layer.php#L358). Replace that line with

    $extratags = isset($this->content['main_tags']) ? $this->content['main_tags'] : '';
    $this->output( '<div class="' . $width_class . ( @$this->content['hidden'] ? ' qa-main-hidden' : '' ) . '"'.$extratags.'>' );

**Comment by yerbol89** [comment]
Thanks @svivian Its nice work.
@amiyasahu please add this code Donut theme.

**Comment by yerbol89** [comment]
@amiyasahu please add Donut next version.

**Comment by amiyasahu** [comment]
I added to the issue list and will be fixing soon
