### ISSUE TITLE
Usage of limits on db/selects.php

### ISSUE THREAD

**Issue by arjunsuresh** [q2a/question2answer#438]
I had to make the following changes to correct the questions displayed on each page of question lists after overriding basic_select_spec function. Is this a change that can be made on core?

--"type=$ ".$sortsql." LIMIT #,#) y ON ^posts.postid=y.postid";
++"type=$  ) y ON ^posts.postid=y.postid ".$sortsql." LIMIT #,#";

**Comment by svivian** [comment]
Can you explain what the exact problem is?

**Comment by arjunsuresh** [comment]
Hi Scott,
On my site I'm overriding basic selecspec and in it adding an extra join clause to filter out certain questions from user. But in the question listing queries for recent questions etc, the limit is getting applied before my filter is happening via override and hence some pages display fewer questions than the set value of 30. Changing the limit to the end of the query fixes this as then the join happens before and limit at the end. With this change it is very easy to filter out specific category, tag etc for users and so would be quite useful for Q2A in general.

**Comment by svivian** [comment]
Sorry forgot about this issue.

The reason the LIMIT is there is performance, moving it outside the subquery will make it slower. It's a bit difficult to explain but basically the inner query does an index select to filter/limit the rows (more efficient), and the outer query join that to select all the fields. Moving the LIMIT out means you join the entire table before filtering which is inefficient.

The ideal solution in your case would be to somehow add the filter to the inner query. Unfortunately I don't think there is any way without a core hack.
