### ISSUE TITLE
file_get_contents(/.): failed to open stream: Permission denied in /qa-include/qa-base.php(591) : eval()'d code on line 81

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#444]
I get this error: 

     PHP Warning:  file_get_contents(/.): failed to open stream: Permission denied in /qa-include/qa-base.php(591) : eval()'d code on line 81

Line 591 of qa-base.php: 

    eval('?'.'>'.$eval);

Line 81 of my plugin [q2apro-better-upload-folders](https://github.com/q2apro/q2apro-better-upload-folders/blob/master/q2apro-better-upload-folders-overrides.php#L81): 

    return file_get_contents($filename);

I did some tests and it seems that maybe file_get_contents() is also not throwing back `false` but directly an error. 

I do not understand why qa-base.php is having a stake here. But I see that eval is called because of my override by the plugin.

---

Note: Running PHP 7.0. Q2A v.1.7.1

**Comment by q2apro** [comment]
I assume either the `$filename` passed causes problems when the parsing takes place by `qa_eval_from_file($layerphp, $filename);` or `file_get_contents($filename)` causes problems, feeling says first one.

**Comment by q2apro** [comment]
Think I fixed it within the plugin: 

Checking now for isset (not null) in the same if line with `file_exists`: 

    if(isset($filename) && file_exists($filename))

Seems to fix it.

**Comment by svivian** [comment]
Yeah the error you get when there is a problem in the plugin is a bit cryptic. That's due to they way function and layer overrides work (using eval).

I have some ideas for a better override system that should solve that problem. Will get implemented whenever I get any free time...
