### ISSUE TITLE
nginx confuraion for permelink pretty

### ISSUE THREAD

**Issue by twins16** [q2a/question2answer#445]
any idéés for nginx confuraion for permelink pretty

**Comment by svivian** [comment]
Take a look at the Q2A site, there are several questions there that should help.

http://www.question2answer.org/qa/3064/howto-run-configure-it-right-on-nginx-web-server
http://www.question2answer.org/qa/49781/how-to-config-nginx-on-ubuntu-for-q2a
http://www.question2answer.org/qa/43081/the-correct-rule-of-rewrite-for-nginx
General search: http://www.question2answer.org/qa/search?q=nginx

**Comment by twins16** [comment]
thank's
