### ISSUE TITLE
Nginx time out when i rest the pass 

### ISSUE THREAD

**Issue by twins16** [q2a/question2answer#446]
hay today i set  the q2a in my host and the server IS LEMP NGINX UBUNTU 14.04 
WHEN I USE THE FORGET PASS THE SERVER TIME OUT AND BLICK ALL THE DOMAINS ANY IDÉÉS PLEASE I CAN SEND ANY EMAIL FROM THE Q2A

**Comment by svivian** [comment]
Can't think of any reason that would happen. You should contact your host to see if there is a problem on their side. Do you have any errors in the error logs?

**Comment by twins16** [comment]
i am ttthe hosting isloved my problme thank's
