### ISSUE TITLE
Confirmation success displayed using $qa_content['error']

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#449]
https://github.com/q2a/question2answer/blob/dev/qa-include/pages/confirm.php#L90

```
$qa_content['error']=qa_lang_html('users/confirm_emailed');
```

and https://github.com/q2a/question2answer/blob/dev/qa-include/pages/confirm.php#L93

```
$qa_content['error']=qa_lang_html('users/confirm_complete');
```

This is always confusing for the users, getting a big red warning --- which is a success message?! 

Please change this. (Do we need to introduce a $qa_content['success'] for this?)

**Comment by svivian** [comment]
Good point. I've fixed this in e694b26 and added `$qa_content['success']` that uses a class `.qa-success`
