### ISSUE TITLE
stop php fpm and get 404 , render ccs using snow theme 

### ISSUE THREAD

**Issue by cheri3a** [q2a/question2answer#478]
FastCGI + google page speed 
sudo tail -n 20 /var/log/nginx/error.log
2016/12/19 03:23:12 [error] 19155#0: *585701 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 274
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 275
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 276" while reading response header from upstream, client: 41.106.80.26, server: cheri3a.com, request: "GET /qa/qa-theme/SnowFlat/fonts/fontello.eot?70015067 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.cheri3a.com", referrer: "https://www.cheri3a.com/qa/2646/%D8%A7%D8%B4%D8%B1%D8%AD-%D8%B9%D8%A8%D8%A7%D8%B1%D8%A9-%D8%B1%D8%A7%D8%A8%D8%B7%D8%A9-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%A7%D9%82%D9%88%D9%89-%D9%88-%D8%A7%D9%88%D8%AB%D9%82-%D9%85%D9%86-%D9%83%D9%84-%D8%A7%D9%84%D8%B1%D9%88%D8%A7%D8%A8%D8%B7"
2016/12/19 03:23:12 [error] 19155#0: *585707 open() "/var/www/html/qa/qa-theme/SnowFlat/images/spinner-icon-14x14.gif" failed (2: No such file or directory), client: 41.106.80.26, server: cheri3a.com, request: "GET /qa/qa-theme/SnowFlat/images/spinner-icon-14x14.gif?1410117644 HTTP/1.1", host: "www.cheri3a.com", referrer: "https://www.cheri3a.com/qa/2646/%D8%A7%D8%B4%D8%B1%D8%AD-%D8%B9%D8%A8%D8%A7%D8%B1%D8%A9-%D8%B1%D8%A7%D8%A8%D8%B7%D8%A9-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%A7%D9%82%D9%88%D9%89-%D9%88-%D8%A7%D9%88%D8%AB%D9%82-%D9%85%D9%86-%D9%83%D9%84-%D8%A7%D9%84%D8%B1%D9%88%D8%A7%D8%A8%D8%B7"
2016/12/19 03:23:13 [error] 19155#0: *585708 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 274
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 275
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 276" while reading response header from upstream, client: 41.106.80.26, server: cheri3a.com, request: "GET /qa/qa-theme/SnowFlat/fonts/fontello.eot?70015067 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.cheri3a.com", referrer: "https://www.cheri3a.com/qa/2646/%D8%A7%D8%B4%D8%B1%D8%AD-%D8%B9%D8%A8%D8%A7%D8%B1%D8%A9-%D8%B1%D8%A7%D8%A8%D8%B7%D8%A9-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%A7%D9%82%D9%88%D9%89-%D9%88-%D8%A7%D9%88%D8%AB%D9%82-%D9%85%D9%86-%D9%83%D9%84-%D8%A7%D9%84%D8%B1%D9%88%D8%A7%D8%A8%D8%B7"

2016/12/19 03:29:16 [error] 19152#0: *586387 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 274
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 275
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 276" while reading response header from upstream, client: 66.249.76.92, server: cheri3a.com, request: "GET /qa/tag/%D8%AA%D8%AD%D8%B6%D9%8A%D8%B1_%D9%86%D8%B5%D9%88%D8%B5_%D8%A7%D9%84%D9%84%D8%BA%D8%A9_%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9_%D9%84%D9%84%D8%B3%D9%86%D8%A9_%D8%A7%D9%88%D9%84%D9%89_%D9%85%D8%AA%D9%88%D8%B3%D8%B7 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.cheri3a.com"
2016/12/19 03:29:34 [error] 19155#0: *586407 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 274
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 275
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 276" while reading response header from upstream, client: 66.249.64.122, server: cheri3a.com, request: "GET /qa/register?to=tag%2F%25D8%25AA%25D8%25AD%25D8%25B6%25D9%258A%25D8%25B1_%25D9%2586%25D8%25B5%25D9%2588%25D8%25B5_%25D8%25A7%25D9%2584%25D9%2584%25D8%25BA%25D8%25A9_%25D8%25A7%25D9%2584%25D8%25B9%25D8%25B1%25D8%25A8%25D9%258A%25D8%25A9_%25D9%2584%25D9%2584%25D8%25B3%25D9%2586%25D8%25A9_%25D8%25A7%25D9%2588%25D9%2584%25D9%2589_%25D9%2585%25D8%25AA%25D9%2588%25D8%25B3%25D8%25B7 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.cheri3a.com"
2016/12/19 03:29:48 [error] 19155#0: *586407 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 274
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 275
PHP message: PHP Notice:  Undefined index: description in /var/www/html/qa/qa-include/qa-theme-base.php on line 276" while reading response header from upstream, client: 66.249.64.122, server: cheri3a.com, request: "GET /qa/register?to=user%2FHa%2BSsina HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.cheri3a.com"

**Comment by svivian** [comment]
Can you explain in more detail what the problem is and when it occurs?

**Comment by cheri3a** [comment]
from nginx send euror log can we add all css on the  html and comprase it i see that with vanich is very speed but i some time all server get 404 because sory i don't now what is that mean i just copie and paste just he not work probably wit vanich block :+1:

**Comment by svivian** [comment]
Sorry I am unable to reproduce the error. The error messages indicate it's an issue with `$this->content['description']` in the `qa_theme_base::head_metas()` method, but Q2A's code already handles when the description is not there (so the error should never show).

In your HTML you have various extra meta elements like Twitter/Facebook cards, so it's probably a plugin causing the notices to appear.
