### ISSUE TITLE
Unapproved users are suggested to provide details to their account, but don't have permission

### ISSUE THREAD

**Issue by SuperUserNameMan** [q2a/question2answer#479]
Hi,
using 1.7.4,

if I set the user approbation as required (``[options/approve_user_required]``), as soon as a new user has registered, the ``[users/approve_required]`` message is displayed with a link suggesting to provide more details to their account.

This link leads to the user's account page showing a ``[users/no_permission]`` warning message, followed by the account details in which they can't edit any field excepted the password.

edit : ``'approve_required' => 'Please wait for your account to be approved or ^1add more information^2.',``

**Comment by pupi1985** [comment]
Good point. There seems to be some inconsistency there. In fact, this actually could happen if the user is blocked by an admin, blocked by IP or still pending approval. Those states are all in the same bag.

I wonder:
 * Should those states be 100% restricted in terms of personal data edition?
 * Should a blocked by admin user be treated the same way as a pending approval user?

**Comment by SuperUserNameMan** [comment]
Concerning pending approval users, i see at least several scenario depending on how are set possible extra custom profile fields (``[admin/profile_fields]``) :

1) if there is no extra profile fields, then the pending user's profile should contain nothing to edit - excepted, maybe, the avatar and the password ?

2) if some extra profile fields are set to be shown on the register form, then the admin might not want them to be edited afterward ... so the pending approval user should not be allowed to edit them.

3) if some extra profile fields are set, then, the pending user could be allowed to edit them to polish his/her profile till he/she is approved. (this would be a proof that this user is not a bot btw)

**Comment by svivian** [comment]
Originally all users could edit their profile information but this was changed in 1.6.3 to prevent blocked users from changing their profile (for spam reasons). I guess non-approved users are caught in that too.

So yes there should probably be some differentiation between the two states, with an option to allow pending users to edit their profile. (If the option is off we wouldn't invite them to change their info.)

**Comment by svivian** [comment]
Solved by removing the unnecessary `approve_user_required` option in d225ef2.
