### ISSUE TITLE
when avatars are disabled, [options/avatar_message_list_size] still displayed into admin center

### ISSUE THREAD

**Issue by SuperUserNameMan** [q2a/question2answer#482]
hi,
1.7.4

this is minor bug into the "admin - users" page.

when both avatars and gravatars are disables, all the `[options/avatar_xxxxx_size]` are hidden, excepted `[options/avatar_message_list_size] => "Avatar size on message lists:"` that remains visible.

**Comment by pupi1985** [comment]
As next release will be 1.8 then I can't branch from the 1.7.4 branch. However, you can apply those changes manually based on this PR #483. This should get it fixed.

**Comment by SuperUserNameMan** [comment]
Yes this fixes it !
it's line 350 on 1.7.4.

**Comment by svivian** [comment]
Thanks, fixed.
