### ISSUE TITLE
Page admin/plugins showing all plugins as "Unnamed Plugin"

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#487]
When you switch to PHP 7.1 the entire plugin names are not showing up under /admin/plugins

I checked `/pages/admin/admin-plugins.php` and could see that 

    $contents = file_get_contents($pluginFile, false, null, -1, 8192);

is empty. Switching back to PHP 7.0 the names show up again. 

Maybe we should use curl here? Or force all plugins to use metadata.json.

**Comment by pupi1985** [comment]
IMO, I don't think the PHP version has anything to do with this (or at least I see no documented change in the `file_get_contents()` function). This smells like a read permission issue on those files. Those files are not fetched from the network but locally.

**Comment by q2apro** [comment]
As said, when I switch the version to 7.0 it works.

**Comment by svivian** [comment]
PHP 7.1 allows negative offsets while previous versions don't, so passing in -1 means it's taking only the last character from the file. Why we're used -1 I'm not sure, but it seems that many code examples around the web also use -1. I'll double check but I'm sure it can simply be changed to 0.

**Comment by pupi1985** [comment]
Funny thing. Google decided to send me to the Spanish documentation of PHP by default. It seems the Spanish docs have not yet been updated with this change yet: http://php.net/manual/es/function.file-get-contents.php

**Comment by svivian** [comment]
Figured it out. The docs used to give -1 as the default for `$offset` - http://web.archive.org/web/20160102080528/http://php.net/manual/en/function.file-get-contents.php

So as we were only specifying the length I used the default value for the other parameters. Nothing suggests that -1 was a special value so I'll change it to 0.
