### ISSUE TITLE
BUG: Widgets are not showing "Specifically" on user pages 

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#493]
If I add a widget and click on "Show this widget on all available pages" then that widget shows properly (even on user pages). But, if I specifically want a widget to be added to on "User pages" then it is not showing there. Either the widget is stock or third party, the same is happening with both type of widgets.

Please fix this.

**Comment by svivian** [comment]
What is the widget, and which position are you setting the widget to? Some positions (like the sidebar) are not available on user pages. And some widgets won't have anything to show on user pages (like the related questions widget).

**Comment by svivian** [comment]
Cannot reproduce. If you can give more details I'll reopen the bug.

**Comment by gurjyot** [comment]
Widgets like Activity Count, Facebook like box, Google Ad (and many more) does not show if I want those to show specifically on user pages. 
Until and unless I click these widgets to show on all available pages, these does not show on user pages.

**Comment by SuperUserNameMan** [comment]
I can reproduce with 1.7.4.

How to reproduce :

step 1 :
- add "Activity Count" widget to "users pages", at any sidebar position.
- goto any user any page (Wall, Recent activity, Question, Answer) : "Activity Count" widget does not appear there.

step 2 :
- move "Activity Count" widget to "display on all pages"
- goto any user any page (Wall, Recent activity, Question, Answer) : "Activity Count" widget is displayed.

**Comment by svivian** [comment]
Thanks for the specifics, I can see the bug now.

**Comment by svivian** [comment]
Fix in 2cf5701.

Might need some refactoring in the future. The "templates" for those user pages are all different - `user`, `user-activity`, `user-wall` etc but templates for other sections are not (e.g. `users` for top users, blocked users, etc). Perhaps the user wall page should just have template `user` then we use another method for targeting specific pages.
