### ISSUE TITLE
q2a 1.8 version cache not remove after use

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#497]
I use my site question2answer 1.8 version. Today i see my server big files cache folder - 6 Gb.

Q2A not remove files after use cache file.

<img width="576" alt="2017-02-27 22 46 47" src="https://cloud.githubusercontent.com/assets/993795/23370377/aaa1ef0e-fd3e-11e6-92e4-4c4d4dddafd4.png">

**Comment by svivian** [comment]
That's how it's designed. When you visit a page, it checks if a cache file exists and is not expired. If so it uses that cache file. If it does not exist or is expired, it generated the page as normal and makes the cache file.

It's not possible to automatically delete old caches (unless you set up a cron job to do it). But it would be useful to have a button in the admin to delete expired caches, so I'll look at adding that.

**Comment by ProThoughts** [comment]
How cache is implemented by Wordpress? they do have plugin for that
https://wordpress.org/plugins/wp-super-cache/
https://wordpress.org/plugins/w3-total-cache/

what are technical difficulties to implement similar solution? It will be easy to enable/disable.

**Comment by svivian** [comment]
I'm not sure about Wordpress but I know that other systems such as Laravel and CodeIgniter do not automatically clear expired cache.

**Comment by ProThoughts** [comment]
Best feature of w3 total cache and wp super cache is we can configure for CDN. Plugin automatically pushes cache content to CDN. This helps to load site much faster. We can clear cache also.  Please check that plugin when you get time. thanks.

**Comment by svivian** [comment]
CDN doesn't apply in this case. The data we're caching needs to be read by PHP so it will actually be *slower* for the server to read it from another place. 

A CDN feature like that is for external files like JS/CSS/images, which can be directly served to users.

**Comment by svivian** [comment]
Solved in recent commits. There are now buttons to delete entire cache or just expired cache.
