### ISSUE TITLE
Does this version has the option to email all questions and their answers to all members ?

### ISSUE THREAD

**Issue by Coderx7** [q2a/question2answer#500]
Hello everyone. 
A very good feature that google user groups and pretty much any other usergroups/mailing lists have, is the ability to receive an email for any questions asked in the group and their subsequent answers to all members. 
Does this version have such a capability implemented ?
If not I guess it would be a very good idea to have a plugin (or maybe implement this as a core feature) that would provide such capability. 
Users may specify to receive an email for any questions asked plus their answers 
This can be further expanded by specifying several options on receiving emails e.g. receive emails about questions with specific tags or from a specific group/category. or deactivate it altogether. (default would be to receive all emails)
This would imho increase the sites activity considerably since it removes the necessity of checking the site every time and when someone checks his/he email he can see what interests him/her and act upon it.
It would even be more interesting if we could however make it possible to post answers directly from emails to the specified questions

**Comment by svivian** [comment]
Currently, users can be emailed on replies to any of their questions/answers/comments. But not on any new question or new questions in a category/tag. I think that kind of thing would be best done as a plugin.

Regarding answering from email, that is quite a complex subject. There was a question about this on the [Q2A site](http://www.question2answer.org/qa/) before where I gave some details.

P.S. in future, please try and keep feature requests to the Question2Answer site. The Github Issues are intended for bugs.
