### ISSUE TITLE
Adding location map plugin

### ISSUE THREAD

**Issue by SangramChavan** [q2a/question2answer#502]

**Comment by SangramChavan** [comment]
#Feature request

**Comment by svivian** [comment]
I don't think that would fit with the core, it should be a separate plugin.

Check out the docs for help on making a plugin, or if you don't know PHP, ask on the [Q2A Q&A](http://www.question2answer.org/qa/) if someone wants to make a plugin for you.

(By the way, the GitHub repo is not intended for feature requests. If you have more requests in the future, ask on the Q2A site. Thanks.)
