### ISSUE TITLE
1.8 Database Initialization Issue with load_order

### ISSUE THREAD

**Issue by q2amarket** [q2a/question2answer#511]
@svivian @pupi1985 

I was trying to update [Star Rating plugin](https://github.com/q2amarket/q2am-star-ratings) and stuck with the weird issue.
If I define `load_order:` to `after_db_init` the database doesn't initialize to install required table for the plugin. However, it works fine if `load_order:` set to `before_db_init`.

I understand that to add table; it has to be load before database initializes but then the plugin can't be disabled.

I have checked event logger plugin metadata.json and realized no `load_order:` parameter is set. So in that case what will happen? How will Q2A react if the haven't been set?

Is there any way in 1.8 which allows to Enable/Disable plugin and can create a table on the first load?

**Comment by svivian** [comment]
I get the banner come up, saying the plugin needs database initialization. However, when I click the link it says the database has been checked with no problems. So most likely the install page is not loading the optional plugins which have the DB init code. Hopefully that won't be too difficult to fix.

If no `load_order` plugin is set, it default to `before_db_init` - in other words, the plugin will always be enabled.

**Comment by q2amarket** [comment]
Thanks Scott for the feedback. I have changed `load_order` to `before_db_init`

**Comment by svivian** [comment]
Made some updates to the 1.8 branch to fix this. You can set your plugin `load_order` to `after_db_init` and the DB install queries will run properly.

**Comment by q2amarket** [comment]
Cool thanks.. I will try and get back to you. Thanks for the fix.

**Comment by q2amarket** [comment]
You might have to re-open this issue as I found there is a bug. When I have set the `load_order` to `after_db_init` the plugin never gets `Enabled`

**Comment by svivian** [comment]
What do you mean by "never" gets enabled? By default new plugins with that option are not enabled. You need to go to the Plugins section in Admin and enable them. Then you'll see the notice regarding database updates.

**Comment by q2amarket** [comment]
I mean, when I select the checkbox and hit save button, the checkbox state go back to unchecked. Moreover, not getting any data initialization notice at the top. So it might be possible the plugin is not getting enabled.
