### ISSUE TITLE
Custom table dropped on Q2A version update

### ISSUE THREAD

**Issue by q2amarket** [q2a/question2answer#515]
@svivian When I have updated Q2A to 1.8 all my custom table has been deleted while updating the database. Any idea?

**Comment by svivian** [comment]
Can you add a more detailed description of what you did. Were there any error messages? I presume you were upgrading to the latest version from Github (18d1068865b6a0826789e4a84b624ec67dc25660). What are the table names that were dropped, were they ones from plugins or completely separate from Q2A?

There are no upgrade queries dropping tables so I'm not really sure how this could be caused by Q2A.

**Comment by q2amarket** [comment]
Just 10min before posting this issue I have updated my Dev version with the 1.8 branch _(not so sure about the commit)_

As soon as I visit the site, it has updated the database. My table was from the `Star Rating Plugin` named with `prefix_star_ratings` - `qa_star_ratings` 

I am too not so sure how this happened. What I can do to cross check is reinstall old version or Q2A and upgrade it again with 1.8 branch. Will do in weekend and let you know.

Please let me know if you have any update on it before that.

**Comment by svivian** [comment]
By "dev version" do you mean running it on your computer (as opposed to a live website)?

> As soon as I visit the site, it has updated the database.

To clarify, do you mean that when you went to your site the upgrade was already done? i.e. you didn't need to click the upgrade button?

If you were running the upgrade on a live site, it's possible that multiple visitors came to the site before you and all clicked the upgrade button at the same time. However, I can't see how that would end up deleting any tables.

**Comment by q2amarket** [comment]
Yes, dev means my local dev environment. At the first visit after updating the source, the database initialized automatically without asking or notifying. For instance, as it ask for plugin db initialization.

I'm wondering too as never faced table deleting issue before. It's the first time.

**Comment by phy25** [comment]
There's no `DROP TABLE` in qa-include/db/install.php. So it can't be Q2A core's fault.

**Comment by phy25** [comment]
There's no `DROP TABLE` in qa-include/db/install.php, so it can't be Q2A core's fault.

**Comment by q2amarket** [comment]
@phy25 Thanks...

@svivian Closing this issue as it might be irrelevant. I will try to find the cause and let you know if there is anything relating to source.
