### ISSUE TITLE
remove obsolete font files

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#516]
We just need woff / woff2

https://github.com/q2a/question2answer/tree/1.8/qa-theme/SnowFlat/fonts

**Comment by svivian** [comment]
I assume you're referring to the icon font? Those have been kept for BC with older browsers. Even though there are very few visitors with those browsers, having the icons visible is more important than the regular font (there is no safe fallback). We could add woff2 for the icons though.

I looked at adding woff2 to the Ubuntu font when updating the CSS the other day, but the woff2 version on Google Fonts is split into multiple Unicode ranges so it's not possible to use both at the same time (Google Fonts does browser detection and serves only one format).

**Comment by DanielRuf** [comment]
Maybe we have the Ubuntu webfont as package somewhere.

**Comment by DanielRuf** [comment]
Right, ok.

**Comment by svivian** [comment]
I tried putting the Ubuntu font through the font squirrel generator and the woff comes out larger than the current one. Even the woff2 is only a tiny bit smaller than the woff.

Re the font icons, we may be able to remove the ttf and svg files. I'm not sure if any browsers supported those and not woff at any point.

**Comment by DanielRuf** [comment]
And [these](https://github.com/earaujoassis/ubuntu-fontface/tree/master/fonts)?

**Comment by SuperUserNameMan** [comment]
@svivian : note that the SVG is usefull if you want to import the icons back into fontello.com to modify them.

**Comment by svivian** [comment]
@DanielRuf those are even larger (170 KB for `ubuntu-regular-webfont.woff`, 100 KB for the woff2)

There is a field `$localfonts` in SnowFlat that can load the fonts from Google Fonts, so I think that will be the easiest for most people. (At some point I hope to add "theme options" like plugin options.)

Closing this for now, but if you do find some woff2 files smaller than the woff files let me know or open a PR.

**Comment by DanielRuf** [comment]
Okay
