### ISSUE TITLE
site with q2a demo plugin not working 

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#517]
I installed latest q2a v1.8 with q2a demo plugin but it is showing blank. could you please look into this. Thanks

http://demo18.question2answer.info

**Comment by svivian** [comment]
Please check your error logs, there must be something in there. Also make sure you're using the latest version, I fixed an installation bug yesterday.

**Comment by ProThoughts** [comment]
It is working now, thanks! it was issue with demo plugin.
