### ISSUE TITLE
Custom userfields on top of the email, username, password

### ISSUE THREAD

**Issue by JackSiro** [q2a/question2answer#518]
1. I would like to see on the register page that the custom user fields like fullname, website, on top of the default ones like email, username, password. 

2. I also would like to have the form style set to wide and not tall

for more info refer to my resipiratory here [https://github.com/q2a/question2answer/issues](https://github.com/JackSiro/Question2Answer/blob/master/qa-include/pages/register.php)
![register](https://cloud.githubusercontent.com/assets/1726074/25167584/a739430e-24e8-11e7-95de-ee40ae7c8ea5.png)

**Comment by svivian** [comment]
Answered in #519
