### ISSUE TITLE
Custom userfields to be seen on registration form by default

### ISSUE THREAD

**Issue by JackSiro** [q2a/question2answer#519]
How i wish "qa_db_default_userfields_sql()" on the qa-include/db/install.php that userfields like full name, website, location and about be shown on registration form by default. I already have this implemented on my forked Q2A

**Comment by svivian** [comment]
Thanks for the suggestion. Site owners can set this themselves easily under Admin > Users > Edit field and ticking "Show field on user registration form".

I disagree it should be the default - personally I like the registration for being simple. Those fields are not vital for operation of the site so I don't think they need to be there by default.
