### ISSUE TITLE
[Bug] Missing fields on admin->spam page

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#520]
Please see below images, there may similar issue with other admin pages. This issue is seen with latest Github version. You can check at http://demo18.question2answer.info

<img width="762" alt="screen shot 2017-04-22 at 11 08 31 pm" src="https://cloud.githubusercontent.com/assets/6511264/25315479/408494c2-280a-11e7-9965-f0b7003e3aa8.png">
<img width="770" alt="screen shot 2017-04-23 at 8 32 30 am" src="https://cloud.githubusercontent.com/assets/6511264/25315480/44a381e4-280a-11e7-8939-b879ad0ebb18.png">

**Comment by svivian** [comment]
Those options are under the Users section of admin.

**Comment by ProThoughts** [comment]
Ok, please see above 2nd image carefully, there just points field but no description before that.

**Comment by svivian** [comment]
Sorry I'm not sure what you mean. Which fields are missing?

**Comment by ProThoughts** [comment]
sorry for the confusion, everything looks fine to me.
