### ISSUE TITLE
Widget names shows in "Layout" even if the plugin is removed.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#529]
I have noticed it many times that even if I remove the plugin, the widget with that plugin keep showing in Layout page. 
Instead, everything related to that plugin should be removed as it happens in WordPress.

**Comment by ProThoughts** [comment]
Which plugin you are using?

**Comment by gurjyot** [comment]
@prothoughts plugins like Social Share and Activity Count.

**Comment by ProThoughts** [comment]
could you post link to those plugins, will check on demo site.

**Comment by gurjyot** [comment]
@prothoughts here is the link of Social Share
https://github.com/amiyasahu/q2a-social-share

For another plugin you can see Tag Cloud which is stock plugin.

**Comment by ProThoughts** [comment]
This plugin is broken, checked on demo site and it is not working. which version of php, mysql you are using?

here is error for me
PHP Parse error:  syntax error, unexpected T_STATIC in /home/public_html/qa-plugin/q2a-social-share-master/opengraph/open-graph-protocol.php on line 162

**Comment by svivian** [comment]
I'm not sure this is really a bug. There is no "uninstall" mechanism as such, you just remove the plugin's folder. But the entries in Layout are stored in the database.

I don't think we should be automatically removing those entries if the plugin cannot be found. There could be other reasons for removing a plugin (like you are disabling it to test something) where you don't want to lose all your widgets you added.
