### ISSUE TITLE
[Bug] category label is shown twice in sidebar

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#531]
Please see this screenshot, "Categories" and "All categories" are shown in sidebar, it will look better if we show just one label "All categories"

<img width="273" alt="screen shot 2017-07-22 at 11 57 45 pm" src="https://user-images.githubusercontent.com/6511264/28497366-3fcff40a-6f3a-11e7-9213-a1f3cdd438ff.png">

you can reproduce this at http://demo18.question2answer.info

**Comment by svivian** [comment]
I think this is a theming issue. On the SnowFlat theme the "All categories" appears as a link instead of a heading. I wonder if it's worth having a link to all categories at all? Because it's only a link to the home page.
