### ISSUE TITLE
[Bug] Voting on comments not shown

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#533]
Installed latest q2a version but I dont see any options to vote for comments. Also enabled voting option from in admin->viewing. May be you need to modify themes (Snow, SnowFlat etc) to add support for this.

https://github.com/q2a/question2answer/commit/912cabc4d0c6265a70f31013da1f48e215f66b35

**Comment by svivian** [comment]
Comment voting has not been implemented yet, that commit is just the options to control it. There's still a fair bit more to do yet :)

**Comment by ProThoughts** [comment]
Ok, no problem. I will test this feature once it is ready. I'm doing regression testing of latest version so will keep posting issues as soon as I see :)

**Comment by svivian** [comment]
I've just pushed some more commits which handle the display of the comment voting, but the voting does not work just yet. There is an issue with the way the forms are structured that means comment voting gets caught in the XSS filter. Might need a big refactor...

Anyway I will let you know when it's ready for testing :)

**Comment by svivian** [comment]
OK the comment voting is just about ready. Managed to refactor all the forms so everything works now.

Note that the themes are not yet complete - the voting arrows on SnowFlat look crappy as I just did a quick resize for testing. The other themes don't have styles set up for voting at all, they just show the regular voting block the same size as questions/answers. But the functionality should all be there ready to test if you'd like to take a look some time.

**Comment by ProThoughts** [comment]
great! we can design small vote button for this later. I do see you added support for SnowFlat theme, please add support for Snow theme also. thanks!

**Comment by ProThoughts** [comment]
I'm using latest code on below site, see voting in action.
http://meta.question2answer.info/

I feel we should move voting to right side, and show no of votes on left site.

**Comment by ProThoughts** [comment]
one issue, comment button for question is missing now....
<img width="771" alt="screen shot 2017-08-02 at 1 44 05 pm" src="https://user-images.githubusercontent.com/6511264/28894179-e23fc2dc-7788-11e7-933a-a7df438df6b0.png">

**Comment by svivian** [comment]
Do you have the option "Allow comments on questions" turned off? I just checked on your other demo site and it was deselected in the admin.

**Comment by ProThoughts** [comment]
I totally forgot to see that option before reporting:( ...Yes it was not enabled. now it is working. thanks! :)
