### ISSUE TITLE
Newest user tab is visible to all users

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#534]
Newest user tab is visible to all users, is this expected behavior or bug? when clicked(as a visitor, not logged in user) it shows error "You do not have permission to perform this operation"
You can see here http://meta.question2answer.info/users

<img width="332" alt="screen shot 2017-08-05 at 8 32 40 pm" src="https://user-images.githubusercontent.com/6511264/29000419-bd844d3a-7a1e-11e7-9b93-adb8eed8e72a.png">

**Comment by svivian** [comment]
Yes it was a bug. Now fixed, thanks for reporting.

**Comment by ProThoughts** [comment]
Thank you! Testing site is helping :)
