### ISSUE TITLE
A serious security problem

### ISSUE THREAD

**Issue by l3m0n** [q2a/question2answer#535]
Hello，I found a serious security problem
Can you give me your email？
I'll explain it in detail
emmmm...I want to apply for CVE
so i hope you can help me.
Thank you!

**Comment by svivian** [comment]
Hello, I've added my email to https://github.com/svivian

Or you can send me a private message via http://www.question2answer.org/qa/user/Scott

**Comment by l3m0n** [comment]
ok，I have sent you an email

**Comment by svivian** [comment]
Thanks for the email. Will check into it asap and get back to you.
