### ISSUE TITLE
[Bug] Comment upvote is using question string

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#536]
More details here, issue reported by Ronlaw
http://meta.question2answer.info/569/translation-comment-upvote-is-using-question-string

**Comment by pupi1985** [comment]
It might be better just to merge the QAC message similarly to the `vote_disabled_hidden_x` messages. That way you have less language strings to care about.

**Comment by ProThoughts** [comment]
@pupi1985, agree with you.

**Comment by ProThoughts** [comment]
Fixed this issue in my branch, testing now.

**Comment by ProThoughts** [comment]
Oh, just seen your commit, https://github.com/q2a/question2answer/pull/537 , I will not add mine. thanks for the quick fix.
