### ISSUE TITLE
New Warnings with PHP 7.2 RC

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#540]
Just tried the new version, you will get: 

1. Warning 

> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in qa-theme-base.php on line 211

Line: `if (count(@$this->content['widgets'][$region][$place])) {`

https://github.com/q2a/question2answer/blob/dev/qa-include/qa-theme-base.php#L211

2. Warning 

> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in page.php 

Line: `$lastcategoryid = count($categoryids) ? end($categoryids) : null;`

https://github.com/q2a/question2answer/blob/cfec3c0155817ffba49b06435a05ebb3ef9859a1/qa-include/app/page.php#L486

--

Fix is to check before `if(isset(...))`

**Comment by q2apro** [comment]
Serverpilot PHP 7.2 RC running on a droplet of digital ocean. Do you mean that?

**Comment by svivian** [comment]
Fixed these warnings and a couple more I found. It's possible there may be more lurking around so let me know if you find any.

**Comment by Nasdav** [comment]
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/question2answer-1.8.0/qa-include/app/format.php on line 384
