### ISSUE TITLE
ob_clean(): failed to delete buffer

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#542]
Just tried the new 1.8.0-beta and when doing the db upgrade I got: 

> Notice: ob_clean(): failed to delete buffer. No buffer to delete in /qa-include/qa-install.php on line 59

Running query: ALTER TABLE qa_eventlog MODIFY ipaddress VARCHAR(45) CHARACTER SET ascii ...

**Comment by svivian** [comment]
Which PHP version are you using?

**Comment by svivian** [comment]
Should now be fixed. I guess you are all upgraded now so can't run the upgrade again to test?

**Comment by q2apro** [comment]
PHP was 7.1. Upgrade done, installation deleted. I think it was from q2a 1.7.4.
