### ISSUE TITLE
CSS issue: Text fields are going out of mobile screen with My Account page

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#544]
Here you can see the issue.
![css issue](https://user-images.githubusercontent.com/6462850/31058471-b8a58426-a711-11e7-801f-da25545359f1.png)

**Comment by svivian** [comment]
Which theme? Do you have a link to a live page showing the issue?

**Comment by gurjyot** [comment]
@sivian its my Q2A website account only. 

http://question2answer.org/qa/user/Gurjyot+Singh
