### ISSUE TITLE
Recaptcha and category selection is not working

### ISSUE THREAD

**Issue by umerprince** [q2a/question2answer#545]
Hello there, please check http://dastiab.com/ and tell me a fix why recaptcha on ask page is not showing and it was showing before but now its not.

Also I can't select categories for asking questions smoothly, what is the problem? and when will the update of script available at softaculous?

Waiting for the reply!

**Comment by svivian** [comment]
Your problem is your script include:

    <script src='//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-504371a41d50c8dd' type='text/javascript'/>

It should be:

    <script src='//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-504371a41d50c8dd' type='text/javascript'></script>

**Comment by umerprince** [comment]
Hmmm,

Thanks for the 100% correct fix.

Now tell me what should I do to add sharing buttons in question pages?

**Comment by umerprince** [comment]
Hello there, just fixed it and the code <script src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-504371a41d50c8dd"></script> is working fine. 

Thanks
