### ISSUE TITLE
CSS issues: Fixed-height drop-down account menu in SnowFloat

### ISSUE THREAD

**Issue by MichaelClerx** [q2a/question2answer#549]
![snowflat](https://user-images.githubusercontent.com/517644/31494380-f72fca76-af4a-11e7-96d8-6342ea39ccd9.png)

Had an issue with the account drop-down on SnowFlat looking transparent (see above).

Turned out to be due to an inline fixed-height declaration.

Fixed it by adding a `height: auto !important` to `.qa-nav-user` in `qa-styles.css`

Version 1.7.5

**Comment by svivian** [comment]
In what circumstances are you seeing this bug? The CSS that your arrow points to in your screenshot is not anywhere in Q2A as far as I can see.

**Comment by gurjyot** [comment]
It's happening due to open login plugin. If the plugin is removed this issue gets fixed. 
Maybe some one has to get a look at that plugin and fix it to be used for SnowFlat.

**Comment by MichaelClerx** [comment]
Thanks! We have the open login plugin installed (but not enabled), so that could be it!

**Comment by gurjyot** [comment]
You can try to remove the plugin and see if it works to fix your theme issue for now.
