### ISSUE TITLE
[bug] how to change the place of vote count and vote sign

### ISSUE THREAD

**Issue by fardina** [q2a/question2answer#550]
In the RTL languages the votes for qestion and answers does not appear correctly. for example if a question has 1 positive vote it shows 1+ instead of +1

and also for negative votes( 1- instead of -1)

![vote](https://user-images.githubusercontent.com/13521621/31500248-c95ecd30-af73-11e7-8346-bc1caadd4cb9.png)

And Also the up vote and down vote signs should be at the right of vote count not at the left.

you could see these two issues in the image.

**Comment by svivian** [comment]
So it should still be -1 and +1 even in RTL direction?

I had a quick look and I'm not sure there's anything we can do. It's the browser that is switching the symbols. We set `direction: rtl` in the CSS to change the text direction and the browser does the rest.

**Comment by fardina** [comment]
Yes it should be +1 and -1
It is not something could be done via css. But I am sure you could fix this issue. All the RTL websites havd this issue!

**Comment by fardina** [comment]
@svivian solved by adding these lines to css:
```
.qa-vote-buttons {
    float: right;
}
.qa-netvote-count-data {
    direction: ltr;
    display: inline-block;
}
```
