### ISSUE TITLE
Refactoring  :)

### ISSUE THREAD

**Issue by Spudley** [q2a/question2answer#554]
Hi.

Having trawled through the Q2A codebase to write the Joomla integration, I've got an itch to tidy up some of the bigger chunks of code to make them a bit easier to work with.

Would you be okay with me submitting a PR to refactor some of the code?

My plan is to try to convert some of the the procedural code into classes, and also break down some of the bigger chunks of code into smaller more manageable bites.

There's obviously a lot of code in there and I don't have infinite amounts of time, so I'll start with a relatively self-contained bit and do a PR for that, and then further changes later on, as I have time (assuming you're happy with the first one, of course).

If you have any suggestions for bits of the code that would be good for me to work on, please let me know, otherwise I'll root around and find a bit to start on for myself.

**Comment by svivian** [comment]
Sure, I'd love to have you on board! I'm currently working on a few structure changes which are not public yet (using namespaces and OO-routing) so it would be best to hold off for a little while and I'll push those changes to the repo asap. But I'm happy to discuss anything you had in mind.

**Comment by Spudley** [comment]
Hi. Thanks for the reply.

I figured you might be doing stuff like that, which is why I asked first rather than just diving in.

I haven't got any specific part in mind, just intending to focus on the bigger chunks of code. eg I've currently got `/plugins/system/k2.php` open, and `onAfterInitialise()` is over 400 lines long, so that seems like a good candidate. But there's others I could also tackle. Happy to be led by you as to where (and when) I should start.

**Comment by Spudley** [comment]
Just a thought -- you mentioned that you're working on adding namespaces, which is great. That will, of course, mean that Q2A can't support php 5.2 any more. Which is also great  :+1:

Namespaces, of course, came in with php 5.3, so with what you're doing you could just up the minimum to that, but if you're upping the minimum anyway, how about going further, to 5.5 or 5.6, so that you (and I) can start using some of the more recent language features?

Looking forward to seeing your changes. Let me know when I can start diving into the code  :smile:

**Comment by Spudley** [comment]
Hi. Any update on the changes you're working on that you mentioned?

**Comment by svivian** [comment]
Hi, sorry I've been super busy over the past two months. I'll look at publishing what I've done in the next few days so you can look.

Regarding PHP versions, it's a difficult one to manage. We want to support as many people as is feasible, but unfortunately there are still a lot of people using PHP 5.3/5.4. Only 53% of users are on PHP 5.5+ according to [w3techs](https://w3techs.com/technologies/details/pl-php/all/all).

I'll probably target PHP 5.4 for Q2A 1.9 as 5.3 should have dropped off enough by release. I'm not sure there's anything super vital in 5.5/5.6 we need to use. PHP 7 has the useful stuff.

**Comment by svivian** [comment]
Finally got around to publishing my updates. I think this page includes everything: https://github.com/q2a/question2answer/compare/controllers

The basic idea is to use a typical router and controller system.

- A core namespace `Q2A` is mapped to the `qa-src/` directory like [PSR-4](http://www.php-fig.org/psr/psr-4/).
- The router matches URL patterns so it's a bit clearer than the current system.
- Some User controllers have been set up with a little refactoring (e.g. `UsersList:: rankedUsersContent).
- They mostly use the exact same code but they'll eventually be refactored into separate functions for GET (viewing the page) and POST (updating/saving data).
- I started a new Database class (using PDO) but I don't remember exactly how far I got with that.

Was there anything in particular you wanted to work on?

**Comment by Spudley** [comment]
Hi. Fantastic -- thanks for that. I'll read through the changes and see how it looks.

I know I had some pieces of code that I picked out to work on, but I can't remember exactly what now; I'll need to get my head back into the code base again.

In the first instance, my aim is to refactor by breaking up some of the larger chunks of code into multiple smaller functions. In the process, I'll also look to cut out any duplicated code and find other possible improvements. There are a few other things that can be done, like cutting the use of globals, tightening up loops, etc.

It's a process I've done quite a few times for some large applications, and it's always effective at improving a code base, even for reasonably good systems like Q2A.

The window of opportunity I originally had for doing the work came and went, but I do have a bit of time now. More importantly, it it's looking like I will have some time available in January as well, so I'm definitely still up for this. How much I can achieve will depend on how much time I can give to it, of course.

**Comment by Spudley** [comment]
Hi.

Finally found some time to do a bit of refactoring. Please see PR #594.

If you like it, I'll have a go at doing some more next time I have some spare time.  :)
