### ISSUE TITLE
Non-English website Issues while upgrading to 1.8.0beta 1

### ISSUE THREAD

**Issue by Arasahmed** [q2a/question2answer#558]
I faced the following error while tried to upgrade

http://prntscr.com/h8tjvf

-the error appears on the question pages not the homepage
-the website is non-English and the line     '1_answer_title' => '',
exist in the translate file
public_html/qa-lang/ar/qa-lang-question.php
the issue disappeared when I switch the website to English
the pages which contain more than 1 question do not face the issue
this is the language file 
https://file.fm/u/m7fwz76j
The language file is the genuine Q2A Arabic language file

how to resolve  it ?

**Comment by svivian** [comment]
Looks like this was solved in [your Q2A question](http://www.question2answer.org/qa/60762/issues-while-upgrading-to-1-8-0beta-1).
