### ISSUE TITLE
Q2A 1.8 Beta faces URL issue with persian characters

### ISSUE THREAD

**Issue by ehtabar** [q2a/question2answer#559]
Hi There,

My Q2A website is in Persian languge.
When I upgraded my Q2A from 1.7.5 to 1.8.0 beta, URLs of Question pages becomes clean. For example:

The URL before upgrading looks like: https://www.bidbarg.com/bimeh/50921/%D9%85%D8%A8%D9%84%D8%BA-%D9%BE%D8%B1%D8%AF%D8%A7%D8%AE%D8%AA-%D8%A8%DB%8C%D9%85%D9%87-%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%DB%8C-%D8%B3%D8%A7%D9%84-96

However, after upgrading it turns to a link like this:

https://www.bidbarg.com/bimeh/50921/96

I need the rest of URL of Question Pages be showed as before for SEO reasons. Note that the URLs of Tag's and Category Pages don't face this issue. 

Any idea how this URL issue can be fixed on Question Pages?
Q2A version: 1.8.0

**Comment by svivian** [comment]
Did my [answer on the Q2A site](http://www.question2answer.org/qa/60892/q2a-1-8-beta-faces-url-issue-with-persian-characters?show=60958#a60958) fix this for you? The "remove accents" option removes all non-ascii characters.
