### ISSUE TITLE
/qa-include/qa-check-lang.php shows error 502

### ISSUE THREAD

**Issue by Mushan3420** [q2a/question2answer#564]
/qa-include/qa-check-lang.php shows error 502 with nginx 1.12
Rewrite as follows:

if (!-e $request_filename) {
       rewrite ^/(.+)?$ /index.php?qa-rewrite=$1 last;
    }

**Comment by svivian** [comment]
This is an issue with your server config, bot with Q2A itself. So I don't think there is anything for us to update here.
