### ISSUE TITLE
please, help me. "A database error occurred" why?

### ISSUE THREAD

**Issue by AyaanMizan** [q2a/question2answer#565]
when a user ask a question, why show it?

How to solve it?  

<img src="https://dyjpb62732.i.lithium.com/t5/image/serverpage/image-id/161i9C8B522151DA2491/image-size/large?v=1.0&px=999" />

**Comment by svivian** [comment]
You need to look in your web server's error log file to see the error. You might need to check with your host to see where you can find the log.

If you're unable to solve it yourself, post the error here (or on the Q2A site) along with your PHP/MySQL/Q2A versions and we'll try to help.

**Comment by svivian** [comment]
Closing this for now since you have a post [on the Q2A site too](http://www.question2answer.org/qa/61262/when-a-user-asks-a-question-why-does-this-error-show). If it turns out to be a big in Q2A I’ll reopen this ticket.
