### ISSUE TITLE
Notice: ob_clean(): failed to delete buffer. No buffer to delete in /qa-include/qa-install.php

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#566]
Update from 1.7.4 to 1.8.0-beta1 and got the following notice on top of the update script (after execution): 

> Notice: ob_clean(): failed to delete buffer. No buffer to delete in /qa-include/qa-install.php on line 59

Fixable?

**Comment by svivian** [comment]
Is this appearing on every page? Or only when the update script ran? What's your PHP/MySQL version?

**Comment by q2apro** [comment]
I got this only on my local installation. Doing the upgrade online went through without this message. (Maybe because notices are not shown, not sure...)
