### ISSUE TITLE
.entry-content missing in 1.8.0?!

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#568]
I upgraded to 1.8.0-beta and see that the `.entry-content` class was removed from the template. 

Now most of my plugins are not working, and the CSS of my themes has to be rewritten. 

1. Why this decision?

2. Why not leave a class for the post content? This is the only way to target all three types of posts: Q, C, A with one statement. Important for plugins.

Instead: 

     <div itemprop="text">

It should be: 

    <div class="entry-content" itemprop="text">

**Comment by svivian** [comment]
`.entry-content` is from the old microformats spec, Q2A 1.8 uses the latest spec ([here](http://schema.org/Question)). The entry-content div was never intended to be used for CSS.

You can use `.qa-q-view-content, .qa-a-item-content, .qa-c-item-content {...}` to select the content of a post.

**Comment by q2apro** [comment]
Why not have a CSS that lets us access all post fields? That would be so helpful. 

If you need to remove `.entry-content` then I would at least add another name, e.g. `.post-content`

It is much easier for jquery/js modifications and CSS targeting.

**Comment by svivian** [comment]
OK it's a fair point. I've added a new class `qa-post-content` on the content for questions/answers/comments.

**Comment by q2apro** [comment]
Great.
