### ISSUE TITLE
Several Vote events with 1.8

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#571]
I noticed today, after the upgrade to 1.8.0 that obviously the ajax vote events are incoming multiple times. Screenshot from phpmyadmin: 

![image](https://user-images.githubusercontent.com/6764548/34078939-006a7054-e32c-11e7-990c-bd91e5255bc2.png)

My guess is that the user clicked multiple times on the thumbs-up which led to multiple incoming events. I also remember that this happened earlier with "best answer selected" events.

We need to disable the button after the press! We can re-enable then after a successful return.

**Alternative:** Dont allow another ajax request as long as one is in process.

**Comment by q2apro** [comment]
I have checked my changes with the former installation, this is what I added to prevent this: 

	function qa_vote_click(elem)
	{
		// ...

					qa_ajax_error();				
				}
				
				// q2apro added: disable button as soon as vote is done
				$(elem).unbind('mouseenter mouseleave onclick onmouseover onmouseout'); 
				$(elem).attr('disabled', 'disabled');
				// disable vote and remove events
				$('.qa-voted-up-button').unbind('mouseenter mouseleave onclick onmouseover onmouseout'); 
				$('.qa-voted-up-button').attr('disabled', 'disabled');
				$('.qa-voted-up-button').removeAttr('title');

			}
		);

		return false;
	}

**Comment by q2apro** [comment]
Seems that it happened again, even with the hack above :/ 

![image](https://user-images.githubusercontent.com/6764548/34079643-4c9e5f2c-e33a-11e7-8863-313fda62c073.png)

Probably the code must be positioned before the `qa_ajax_post()` call.

**Comment by q2apro** [comment]
Alright, this seems to help (note that I don't use vote down buttons in my forum): 

	function qa_vote_click(elem)
	{
		var ens = elem.name.split('_');
		var postid = ens[1];
		var vote = parseInt(ens[2]);
		var code = elem.form.elements.code.value;
		var anchor = ens[3];

		// q2apro added: remove tipsy and disable button as soon as vote is done
		$('.tipsy').remove();
		$(elem).unbind('mouseenter mouseleave onclick onmouseover onmouseout'); 
		$(elem).attr('disabled', 'disabled');
		
		qa_ajax_post('vote', {postid: postid, vote: vote, code: code},
			function(lines) {
				if (lines[0] == '1') {
					qa_set_inner_html(document.getElementById('voting_' + postid), 'voting', lines.slice(1).join("\n"));

				} else if (lines[0] == '0') {
					var mess = document.getElementById('errorbox');

					if (!mess) {
						var mess = document.createElement('div');
						mess.id = 'errorbox';
						mess.className = 'qa-error';
						mess.innerHTML = lines[1];
						mess.style.display = 'none';
					}

					var postelem = document.getElementById(anchor);
					var e = postelem.parentNode.insertBefore(mess, postelem);
					qa_reveal(e);

				} else {
					qa_ajax_error();
				}
				
				// q2apro: disable newly inserted vote button and remove event handler 
				$('.qa-voted-up-button').unbind('mouseenter mouseleave onclick onmouseover onmouseout'); 
				$('.qa-voted-up-button').attr('disabled', 'disabled');
				$('.qa-voted-up-button').removeAttr('title');
			}
		);

		return false;
	}

**Comment by pupi1985** [comment]
I've made a PR with what seems to be the fix for this

**Comment by q2apro** [comment]
Thanks, the fix should work.
