### ISSUE TITLE
Second installation returns "Table 'qa_users' already exists"

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#575]
Second installation (1.8.0-beta both), goal: shared userbase. Both installations access the same DB. 

For the installation of 2nd installation: I have set `QA_MYSQL_TABLE_PREFIX` to `snd_` and `QA_MYSQL_USERS_PREFIX` set to `qa_`. This should be correct, so that the new "snd_DB" should pick up `qa_users`. However, I get: 

> Database query error 1050
Table 'qa_users' already exists

> CREATE TABLE qa_users (userid INT UNSIGNED NOT NULL AUTO_INCREMENT, created DATETIME NOT NULL, createip VARBINARY(16) NOT NULL, email VARCHAR(80) NOT NULL, handle VARCHAR(20) NOT NULL, avatarblobid BIGINT UNSIGNED, avatarwidth SMALLINT UNSIGNED, avatarheight SMALLINT UNSIGNED, passsalt BINARY(16), passcheck BINARY(20), passhash VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL, level TINYINT UNSIGNED NOT NULL, loggedin DATETIME NOT NULL, loginip VARBINARY(16) NOT NULL, written DATETIME, writeip VARBINARY(16), emailcode CHAR(8) CHARACTER SET ascii NOT NULL DEFAULT '', sessioncode CHAR(8) CHARACTER SET ascii NOT NULL DEFAULT '', sessionsource VARCHAR (16) CHARACTER SET ascii DEFAULT '', flags SMALLINT UNSIGNED NOT NULL DEFAULT 0, wallposts MEDIUMINT NOT NULL DEFAULT 0, PRIMARY KEY (userid), KEY email (email), KEY handle (handle), KEY level (level), KEY created (created, level, flags)) ENGINE=InnoDB CHARSET=utf8

Shouldn't it get through?

**Comment by svivian** [comment]
Are you using the beta download from the Q2A website, or the latest Github version?

**Comment by q2apro** [comment]
1. Yes, the beta download from the Q2A website.
2. Yes, first installation uses the qa_ prefix for all tables.

**Comment by q2apro** [comment]
I cannot see anything within `db\install.php` that hinders the install procedure to create the table `qa_users`. Only at line: 

    if (defined('QA_MYSQL_USERS_PREFIX')) {

within `function qa_db_check_tables()`.

**Comment by q2apro** [comment]
More hints: 

1. When calling the 2nd site, it says "Welcome to Question2Answer. It's time to set up your database! ..."
2. Clicking on the button "Set up the Database including User Management" starts the setup with post `create`.
3. This goes into: 

```
if (qa_clicked('create')) {
		qa_db_install_tables();
```

4. In `qa_db_install_tables()` (db/install.php) it uses now the `$missingtables = qa_db_missing_tables($definitions);` and tries to create `qa_users` which leads to the mysql error.

**Comment by q2apro** [comment]
I am pretty sure that `function qa_db_install_tables()` is the culprit, there `$missingtables = qa_db_missing_tables($definitions);`. which returns all tables as missing including `users`. The code then tries to create qa_users in the next lines...

https://github.com/q2a/question2answer/blob/dev/qa-include/db/install.php#L680

**Comment by svivian** [comment]
Thanks for the diagnosis. It was an issue with the `qa_db_list_tables` function.

**Comment by q2apro** [comment]
Hi Scott, sorry to disappoint, but the error message is still there, even with the new `qa-db.php`...

**Comment by q2apro** [comment]
Update: Worked! Thanks.

**Comment by q2apro** [comment]
I tried with 1.8.4 the error pops up again. Seems not to be fixed.

> Database query error 1050
> Table 'qa_users' already exists
