### ISSUE TITLE
[request] improve login using Single Sign-On (SSO) documentation

### ISSUE THREAD

**Issue by plonknimbuzz** [q2a/question2answer#583]
1st time i install 1.7.5 without SSO : working fine. Then i think i need SSO better than classic login register.

i try 1.7.5 with SSO documentation. include edit the properly conf in `qa-external-users.php` but when i login, i get error: `User login is handled by external code`.
i googling this and find this issue and commit https://github.com/q2a/question2answer/issues/447 then i tried that,

but i error from browser
```
This page isn’t working
localhost redirected you too many times.
```

since that commit is merged in 182, so i install the 182. enabled SSO and i still get unilimited redirection.

====
My question is: 
1. what is the meaning of `User login is handled by external code` ? should i create my own php script to create login, register and logout menu?

2. if so, i think we need to update SSO documentation because i dont see any documentation about this.

**Comment by svivian** [comment]
What SSO system are you using? From your first question it sounds like you aren’t using one. To use SSO you need a separate login system developed - for example if you already have a forum or other login on your site, you can use that with Q2A so your users don’t need a separate account for Q2A.

**Comment by plonknimbuzz** [comment]
damn.. your first line pull me off to googling that. 
i thought OAuth = SSO

but they are different 
thanks for this.

so your suggestion is fully right. yes i never use SSO before.
====
if i want to used SSO to Q2A with my existing website. 
need i edit the core or just edit the qa-external-users.php only?
thanks for your time

**Comment by svivian** [comment]
You would only need to edit the qa-external-users file.

BTW if you want to use OAuth then I think a login module is more appropriate: http://docs.question2answer.org/plugins/

There are a few existing login plugins here: http://docs.question2answer.org/addons/

**Comment by plonknimbuzz** [comment]
woww.. this Q2A so complete. lucky i try this after struggling try the others apps . 

your given links is really helpfull. 
thanks again mate
