### ISSUE TITLE
Adding #ids to Submit Buttons

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#585]
Hi everyone, I would like to suggest to give the submit buttons (for answer and comment) ids, such as `id="qa-btn-c124"` (c for comment, 124 for question-or-answer-id, as already implemented with comments).

Recent situation: I have the SCEditor, submit posts by CTRL + Enter. Problem is that I need to tell SCEditor which button to jquery `.trigger()`, however, I cannot directly target those buttons. They have HTML like: 

	<tr>
		<td colspan="1" class="qa-form-tall-buttons">
			<input onclick="$('textarea[name=&quot;c409486_content&quot;]').val( sceditor.instance( $('textarea[name=&quot;c409486_content&quot;]')[0] ).val() ); return qa_submit_comment(409486, 409486, this);" value="Submit comment" title="" type="submit" class="qa-form-tall-button qa-form-tall-button-comment">
			<input name="docancel" onclick="return qa_toggle_element()" value="Cancel" title="" type="submit" class="qa-form-tall-button qa-form-tall-button-cancel">
		</td>
	</tr>

The CTRL ENTER function is "outside" and does not "know" the element. Solution would be having an id for each input field of type submit.

I know that I can put various "workarounds" to abuse onclick etc. However, we hopefully will go to more Jquery style, plus, it's not handy to put everything in the inline onclick instead of an outside script. At least for me.

**Comment by svivian** [comment]
I guess I overlooked this issue. I think trying to trigger clicks on a button isn't the correct method, as there are multiple ways to submit a form (e.g. multiple buttons or pressing Enter in a text field). You want to use the onsubmit event, something like `$('form').on('submit', ...);`

To get the form you can find the nearest parent element that's a form (`.closest('form')` in jQuery I think). There are also IDs on certain parent elements too, like `id="c1234"` if you specifically need the post ID. Hope that helps.
