### ISSUE TITLE
fix direction problem for Unicode paragraph in snow-extl and snow-flat theme in question2answer

### ISSUE THREAD

**Issue by SeyyedMahdiHP** [q2a/question2answer#587]
if you are using unicode texts like persian, arabic and etc, and are using snow-extl and snow-flat with markdown-editor 
 in question2answer-farsi,and if you have a problemwith text align and direction,you can use this patch and youre problem will be solved:
https://github.com/SeyyedMahdiHP/JavaScript/tree/master/q2a%20patch
you can tweak this code to use it for another language, 
feel free to ask your question,

**Comment by svivian** [comment]
What is the problem this is solving?

**Comment by SeyyedMahdiHP** [comment]
it will correct the unicode direction problem for people who are using question2answer- with rtl enabled

**Comment by svivian** [comment]
Still not exactly sure what the problem is. Sounds like an issue with a different theme.
