### ISSUE TITLE
Very slow query detected

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#593]
My server (via serverpilot) outputs now very slow queries. This is the slowest I found (three findings): 

	# Query_time: 9.701253  Lock_time: 0.000534 Rows_sent: 50  Rows_examined: 133415
	SET timestamp=1516783705;
	SELECT qa_posts.postid, qa_posts.categoryid, qa_posts.type, LEFT(qa_posts.type, 1) AS basetype, INSTR(qa_posts.type, '_HIDDEN')>0 AS hidden, INSTR(qa_posts.type, '_QUEUED')>0 AS queued, qa_posts.acount, qa_posts.selchildid, qa_posts.closedbyid, qa_posts.upvotes, qa_posts.downvotes, qa_posts.netvotes, qa_posts.views, qa_posts.hotness, qa_posts.flagcount, qa_posts.title, qa_posts.tags, UNIX_TIMESTAMP(qa_posts.created) AS created, qa_posts.name, qa_categories.title AS categoryname, qa_categories.backpath AS categorybackpath, CONCAT_WS(',', qa_posts.catidpath1, qa_posts.catidpath2, qa_posts.catidpath3, qa_posts.categoryid) AS categoryids, qa_posts.userid, qa_posts.cookieid, qa_posts.createip AS createip, qa_userpoints.points, qa_users.flags, qa_users.level, qa_users.email AS email, qa_users.handle AS handle, BINARY qa_users.avatarblobid AS avatarblobid, qa_users.avatarwidth, qa_users.avatarheight, score, matchparts FROM qa_posts LEFT JOIN qa_categories ON qa_categories.categoryid=qa_posts.categoryid LEFT JOIN qa_users ON qa_posts.userid=qa_users.userid LEFT JOIN qa_userpoints ON qa_posts.userid=qa_userpoints.userid JOIN (SELECT questionid, SUM(score)+2*(LOG(10000)*(qa_posts.hotness-(SELECT MIN(hotness) FROM qa_posts WHERE type='Q'))/((SELECT MAX(hotness) FROM qa_posts WHERE type='Q')-(SELECT MIN(hotness) FROM qa_posts WHERE type='Q')))+LOG(questionid)/1000000 AS score, GROUP_CONCAT(CONCAT_WS(':', matchposttype, matchpostid, ROUND(score,3))) AS matchparts FROM ((SELECT postid AS questionid, LOG(10000/titlecount) AS score, 'Q' AS matchposttype, postid AS matchpostid FROM qa_titlewords JOIN qa_words ON qa_titlewords.wordid=qa_words.wordid WHERE word IN ('flächeninhalt','einer','funktion','berechnen','f') AND titlecount<10000)) x LEFT JOIN qa_posts ON qa_posts.postid=questionid GROUP BY questionid ORDER BY score DESC LIMIT 0,50) y ON qa_posts.postid=y.questionid;

	# Query_time: 9.278236  Lock_time: 0.000517 Rows_sent: 50  Rows_examined: 179190
	SET timestamp=1516783716;
	SELECT qa_posts.postid, qa_posts.categoryid, qa_posts.type, LEFT(qa_posts.type, 1) AS basetype, INSTR(qa_posts.type, '_HIDDEN')>0 AS hidden, INSTR(qa_posts.type, '_QUEUED')>0 AS queued, qa_posts.acount, qa_posts.selchildid, qa_posts.closedbyid, qa_posts.upvotes, qa_posts.downvotes, qa_posts.netvotes, qa_posts.views, qa_posts.hotness, qa_posts.flagcount, qa_posts.title, qa_posts.tags, UNIX_TIMESTAMP(qa_posts.created) AS created, qa_posts.name, qa_categories.title AS categoryname, qa_categories.backpath AS categorybackpath, CONCAT_WS(',', qa_posts.catidpath1, qa_posts.catidpath2, qa_posts.catidpath3, qa_posts.categoryid) AS categoryids, qa_posts.userid, qa_posts.cookieid, qa_posts.createip AS createip, qa_userpoints.points, qa_users.flags, qa_users.level, qa_users.email AS email, qa_users.handle AS handle, BINARY qa_users.avatarblobid AS avatarblobid, qa_users.avatarwidth, qa_users.avatarheight, score, matchparts FROM qa_posts LEFT JOIN qa_categories ON qa_categories.categoryid=qa_posts.categoryid LEFT JOIN qa_users ON qa_posts.userid=qa_users.userid LEFT JOIN qa_userpoints ON qa_posts.userid=qa_userpoints.userid JOIN (SELECT questionid, SUM(score)+2*(LOG(10000)*(qa_posts.hotness-(SELECT MIN(hotness) FROM qa_posts WHERE type='Q'))/((SELECT MAX(hotness) FROM qa_posts WHERE type='Q')-(SELECT MIN(hotness) FROM qa_posts WHERE type='Q')))+LOG(questionid)/1000000 AS score, GROUP_CONCAT(CONCAT_WS(':', matchposttype, matchpostid, ROUND(score,3))) AS matchparts FROM ((SELECT postid AS questionid, LOG(10000/titlecount) AS score, 'Q' AS matchposttype, postid AS matchpostid FROM qa_titlewords JOIN qa_words ON qa_titlewords.wordid=qa_words.wordid WHERE word IN ('flächeninhalt','einer','funktion','berechnen','f','x','x','3','8x','2','f´5x') AND titlecount<10000)) x LEFT JOIN qa_posts ON qa_posts.postid=questionid GROUP BY questionid ORDER BY score DESC LIMIT 0,50) y ON qa_posts.postid=y.questionid;

	# Query_time: 9.695064  Lock_time: 0.000642 Rows_sent: 50  Rows_examined: 179190
	SET timestamp=1516783716;
	SELECT qa_posts.postid, qa_posts.categoryid, qa_posts.type, LEFT(qa_posts.type, 1) AS basetype, INSTR(qa_posts.type, '_HIDDEN')>0 AS hidden, INSTR(qa_posts.type, '_QUEUED')>0 AS queued, qa_posts.acount, qa_posts.selchildid, qa_posts.closedbyid, qa_posts.upvotes, qa_posts.downvotes, qa_posts.netvotes, qa_posts.views, qa_posts.hotness, qa_posts.flagcount, qa_posts.title, qa_posts.tags, UNIX_TIMESTAMP(qa_posts.created) AS created, qa_posts.name, qa_categories.title AS categoryname, qa_categories.backpath AS categorybackpath, CONCAT_WS(',', qa_posts.catidpath1, qa_posts.catidpath2, qa_posts.catidpath3, qa_posts.categoryid) AS categoryids, qa_posts.userid, qa_posts.cookieid, qa_posts.createip AS createip, qa_userpoints.points, qa_users.flags, qa_users.level, qa_users.email AS email, qa_users.handle AS handle, BINARY qa_users.avatarblobid AS avatarblobid, qa_users.avatarwidth, qa_users.avatarheight, score, matchparts FROM qa_posts LEFT JOIN qa_categories ON qa_categories.categoryid=qa_posts.categoryid LEFT JOIN qa_users ON qa_posts.userid=qa_users.userid LEFT JOIN qa_userpoints ON qa_posts.userid=qa_userpoints.userid JOIN (SELECT questionid, SUM(score)+2*(LOG(10000)*(qa_posts.hotness-(SELECT MIN(hotness) FROM qa_posts WHERE type='Q'))/((SELECT MAX(hotness) FROM qa_posts WHERE type='Q')-(SELECT MIN(hotness) FROM qa_posts WHERE type='Q')))+LOG(questionid)/1000000 AS score, GROUP_CONCAT(CONCAT_WS(':', matchposttype, matchpostid, ROUND(score,3))) AS matchparts FROM ((SELECT postid AS questionid, LOG(10000/titlecount) AS score, 'Q' AS matchposttype, postid AS matchpostid FROM qa_titlewords JOIN qa_words ON qa_titlewords.wordid=qa_words.wordid WHERE word IN ('flächeninhalt','einer','funktion','berechnen','f','x','x','3','8x','2','f´5') AND titlecount<10000)) x LEFT JOIN qa_posts ON qa_posts.postid=questionid GROUP BY questionid ORDER BY score DESC LIMIT 0,50) y ON qa_posts.postid=y.questionid;

Is it normal that it needs around 9 seconds? Or can we improve the query?

From what I see it's coming from `/db/selects.php`

**Comment by svivian** [comment]
Those queries are coming from the search function. I think some people have reported these being slow at times before. It's an incredibly complex query but maybe it can be simplified somehow. I'll take a look at some point.

**Comment by q2apro** [comment]
I am not using the q2a search engine, I am using a google custom search, see hack 3 here: https://github.com/q2a/question2answer/issues/573 and description here:  http://www.question2answer.org/qa/23606/

I also found: http://www.question2answer.org/qa/14847/google-custom-search where gidgreen suggested to disable the search by (qa-base.php hack): 

     qa_register_module('search', 'qa-search-basic.php', 'qa_search_basic', '');

Now I am wondering if the "related questions" are also part of the search module. Because those I need!

**Comment by svivian** [comment]
It's possible with your hack that you are only commenting out part of the code, and are still doing the slow query.

And related questions *do* depend on the search module because it indexes all the posts (in the tables like `qa_words`, `qa_contentwords` etc) and the related questions uses those same tables for matching.

**Comment by q2apro** [comment]
Next to my main site I created a new site, a "brother site". The users wrote me that it's awesomely fast, but that the speed of the main site sucks. 

I am pretty sure that the queries above are part of the problem. And as it seems, only logged-in users are effected. In other words: Write-access to the DB.

**Comment by q2apro** [comment]
PS: This query is also heavily slow, it probably comes from the eventlog plugin (or liveticker plugin): 

	# Query_time: 8.973258  Lock_time: 0.000127 Rows_sent: 0  Rows_examined: 213884
	SET timestamp=1517491609;
	SELECT datetime,ipaddress,handle,event,params 
	FROM `qa_eventlog`
	WHERE UNIX_TIMESTAMP(datetime) > 1517491526
	AND event IN ('q_post', 'a_post', 'c_post', 'a_select') 
	ORDER BY datetime DESC
	LIMIT 10;

Ideas from pupi1985: http://www.question2answer.org/qa/59705/how-to-speed-up-queries-on-qa_eventlog

Btw, also reported here: http://www.question2answer.org/qa/49943/event-logger-cused-to-slow-down-the-website

**Comment by svivian** [comment]
Closing as I think you have your answer from that Q2A thread.

**Comment by q2apro** [comment]
Resurrecting this thread. Sorry for pointing to the liveticker plugin, it is not related to the slow query issue above.

The query is still slowing down the site. Using a cache plugin (HTML cache) makes it at least faster for non-registered users.

Still needs to improve this one. Or an option to disable it.

**Comment by q2apro** [comment]
Update: 

I have just found out that it is the *Related Questions Widget* that comes with the core! 

It is eating all the performance.
