### ISSUE TITLE
Missing Delete button when question is closed and hidden

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#600]
I would like to see the "Delete" button even if the question is closed.

With 1.8.0 and previous a closed question that was hidden shows only one button: `Show again`. To be able to delete it, you need: 

1. Reshow the question
2. Reopen the question
3. Hide the question again
4. Finally delete the question

I really would like to have a delete button directly when the question is hidden (and his no child posts of course). The delete process should re-open the question and delete the post automagically. 

Thanks for considering.

**Comment by pupi1985** [comment]
Well. The request is technically contradictory. If a question is closed it has always a child post, which is the note itself. I've never really fully understood why notes are represented by more rows in the posts table... it's really overkill.

Now, it makes sense not to consider the child note a post that would block the deletion of the question. Doing so would result in having to delete both: the question and the note at the time of deletion. Luckily, referential integrity takes care of the note.

**Comment by svivian** [comment]
Now fixed, thanks @pupi1985

**Comment by q2apro** [comment]
I have update my file according the commit https://github.com/q2a/question2answer/pull/670/commits

But there is no "hide" button on a closed question. But at first I need to click hide, then delete...

I guess it's related to:

	$rules['hideable'] = !$post['hidden'] && ($rules['isbyuser'] || !$post['queued']) && !$permiterror_hide_show_self
		&& ($notclosedbyother || !$permiterror_hide_show);

**Comment by pupi1985** [comment]
I do see the "hide" button in the closed question. Try switching to the `dev` branch to make sure you are not using a tainted function and make sure to remove all plugins.

Please, try to replicate the issue and, if you are able to do so, provide the steps. That will save guessing efforts.
