### ISSUE TITLE
qa-cache slowing down website - bug?

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#601]
Just wanted to report back that I have two websites. Both are using the Cache (mysql query caching) of 1.8.0.

With the site having <100k posts, it was faster. With the site >500k posts, it slowed down the entire page → for loggedin-users. 

Submitting an answer is normally ~1 second, now it was about 3 - 5 seconds. Question page loads took much longer etc.

I am pretty sure it is the cache because after disabling it, everything went back to normal.

**Comment by yerbol89** [comment]
I have the same problem with version 1.8.0-beta2 and 1.8.0. On versions 1.7.5 there are no such problems.

**Comment by svivian** [comment]
How long are you caching the question pages for? And what is the typical traffic to a question page, individually? If you are caching for e.g. 1 hour, but your most popular question only gets 10 views per day, caching will not be effective because the cache will be expired every time a visitor comes.

**Comment by yerbol89** [comment]
[Analytics Все данные по веб-сайту Audience Overview 20180205-20180205.pdf](https://github.com/q2a/question2answer/files/1701621/Analytics.-.Audience.Overview.20180205-20180205.pdf)

**Comment by yerbol89** [comment]
@svivian what do you offer? Now I'm in the settings to cost like this. I'm using version 1.7.4. The caching works fine. I wanted to upgrade to versions 1.8.0 but I'm afraid that the server will again drive.
![2018-03-13_09-35-55](https://user-images.githubusercontent.com/993795/37321351-50b19664-26a2-11e8-8951-8e844472dff2.png)

**Comment by svivian** [comment]
@yerbol89 I’d say cache times of 20 minutes is way too short. That would mean every question needs multiple page views every 20 minutes for caching to work. That’s over 200 views for every question per day.

Personally I have question pages set to cache for 720 minutes (12 hours).

Gonna close this as I don’t have any clear measurements for slowdown, and we already have some other issues open about performance.
