### ISSUE TITLE
Adding $subs['^site_url'] to emails.php

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#603]
I would suggest to add to file https://github.com/q2a/question2answer/blob/master/qa-include/app/emails.php the line: 

		$subs['^site_title'] = qa_opt('site_title');
		$subs['^site_url'] = qa_opt('site_url');  // NEW
		$subs['^handle'] = $handle;
		$subs['^email'] = $email;

This would be *very helpful* to be able add the site URL in language strings, see language files.

**Comment by svivian** [comment]
Is there a particular use case? I don't really have a problem adding this but don't want to open the door to having 20 other things in there as well. You can just put your site URL direct in the language file.

**Comment by q2apro** [comment]
This is very useful in several scenarios.

One of my scenarios:
I add a link to the qa-lang entry, e.g. https://github.com/q2a/question2answer/, hardcoded. When I move the site from github.com to gitstack.com then I need to go through all text-hardcoded language files.

Another scenario (also one of mine):
I have several installations and distributed the same PHP files for all. Having the domain hardcoded is a no-go and results in wrong links with the other text entries.

Hope that is convincing enough for now 😃
