### ISSUE TITLE
suggestion about unanswered questions

### ISSUE THREAD

**Issue by mrzeeshanplus** [q2a/question2answer#606]
the unanswered questions should not be included in sitemap and they should be blocked by search engines but should be visible to users

**Comment by phy25** [comment]
Disagree to be default. However this can be a setting or plugin instead.

**Comment by mrzeeshanplus** [comment]
which setting? I am not a programmer BTW

**Comment by mrzeeshanplus** [comment]
Which setting or plugin?

**Comment by svivian** [comment]
Sorry, I disagree they should be blocked in search engines. Maybe someone finding the site via search is able to answer the question. Or maybe they have a similar question and that question helps them solve the same or a different problem. Or maybe they just find the site, check out other questions and become a regular visitor!

If the question is short (e.g. just the title) Google may class it as "thin content" but that doesn't affect the rest of the site, unless you have 1000s of unanswered questions (in which case you should try and answer them!)
