### ISSUE TITLE
Adding type="email" (HTML5) to form_fields

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#611]
I just want to point out that there is a new type for email fields in HTML5, supported by all browsers.

Maybe we can add this at function form_fields(): https://github.com/q2a/question2answer/blob/dev/qa-include/qa-theme-base.php#L1146

And change the appropriate occurences.

PS: I am not a fan of the `number` type since there are localization issues in Chrome (comma does not work). But `email` should be fine.

**Comment by svivian** [comment]
That would be useful. I may get around to it eventually, otherwise I'm happy to accept a pull request.

What exactly is the issue with numbers? I was considering using that for the various admin settings pages. The numeric fields do not accept commas anyway.

**Comment by q2apro** [comment]
The issue with `numbers` in Chrome is that float values can only be entered with dot and not like in German with comma. https://stackoverflow.com/q/35315157/1066234
