### ISSUE TITLE
Bug in plugin qa-mouseover-layer.php

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#618]
If the HTML content is for instance: 

```
<p>
	Ich habe es im HTML mit folgendem Code&nbsp;probiert, aber der Zeilenumbruch wird nicht angezeigt, sondern nur das Zeichen `\n` bzw. `&lt;br&gt;`:
</p>
<p>
	<code>&lt;textarea cols=&quot;40&quot; rows=&quot;5&quot;&gt;Dies ist Zeile 1.\nDies ist Zeile 2.&lt;/textarea&gt;<br />&lt;textarea cols=&quot;50&quot; rows=&quot;5&quot;&gt;Dies ist Zeile 1.&lt;br&gt;Dies ist Zeile 2.&lt;/textarea&gt;</code>
</p>
```

The mouseover layer produces:

```
<a href="./1226/neue-zeile-html-textarea-erzeugen-zeilenumbruch-erzeugen"><span title="Ich habe es im HTML mit folgendem Code probiert, aber der Zeilenumbruch wird nicht angezeigt, sondern nur das Zeichen `\n` bzw. `&lt;br&gt;`: &lt;textarea cols=&quot;40&quot; rows=&quot;5&quot;&gt;Dies ist Zeile 1.\nDies ist Zeile 2.&lt;/textarea&gt; &lt;textarea cols=&quot;50&quot; rows=&quot;5&quot;&gt;Dies ist Zeile 1.&lt;br&gt;Dies ist Zeile 2.&lt;/textarea&gt;">Neue Zeile in HTML textarea erzeugen? Zeilenumbruch im Text erzeugen?</span></a></div>
```

which renders to:

![2018-03-07 bug](https://user-images.githubusercontent.com/6764548/37083927-b9398abe-21f9-11e8-8156-d3a1c0aee91a.png)

**Possible fix:**

After line:

    $text = qa_shorten_string_line($text, $maxlength);

set extra line:

    $text = strip_tags($text);

**Comment by svivian** [comment]
What is displaying the tooltip like that? I wasn't aware any browsers rendered HTML in tooltips.

**Comment by q2apro** [comment]
That happens with plugins that "beautify" tooltips. I, for instance, use https://github.com/jaz303/tipsy

But in general, there should not be any HTML in the tooltips. This will not help and cause problems.

**Comment by svivian** [comment]
Looked at this and the mouseover plugin is working correctly. The actual HTML of the post *is* removed. In your example the post HTML contains `<p>` and `<code>` tags. The textarea part isn't HTML in the post itself, it's just text. As you've shown in your code up there it's output correctly in the page source using `&lt;textarea cols=&quot;` and so on. I think the problem must be with the JS plugin converting that to HTML.
