### ISSUE TITLE
qa_opt('cache_userpointscount') does not get updated on shared installation

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#626]
Two q2a sites, shared qa_users, problem is that newly registered users increase the `qa_opt('cache_userpointscount')` only on the main installation, as it seems.

Of course, a "recount" in admin section solves it, but it should be updated on each user registration "network wide" itself. In table `qa_options`, see function `qa_db_userpointscount_update()`.

--

Or does it update the cache value on each user registration per site? Now not sure...

**Comment by pupi1985** [comment]
The different sites share the the ^users table. The rest is in a per-site basis. I don't think this is a bug.

In what line of the core is that cached value requested and not updated? (that line would be the bug)

**Comment by q2apro** [comment]
The userpoints table gets only an entry for a new user if there are points for the user. This means, the count of users in ^userpoints is less than in ^users. In my point of view, they should match (same amount of users). Even all 0 point users should be inside.

The recalculation process does this. That's why my different sites display different user counts in the beginning (and none of them the total number from ^users).

So as an idea: When creating a new user *always* add an entry to ^userpoints.

**Comment by q2apro** [comment]
And when you use `qa_opt('cache_userpointscount')` in your theme, it does not display the correct total amount of users. Each site shows another count. That's a bug IMO.

**Comment by q2apro** [comment]
For now, I fixed this by editing the event-logger plugin:

```
if($event=='u_register') {
			// qa_db_points_update_ifuser($userid, true);
			// create userpoints entry for all site
			qa_db_query_sub('INSERT IGNORE INTO `qa_userpoints` (`userid`) VALUES (#)', $userid);
			qa_db_query_sub('INSERT IGNORE INTO `qb_userpoints` (`userid`) VALUES (#)', $userid);
			qa_db_query_sub('INSERT IGNORE INTO `qc_userpoints` (`userid`) VALUES (#)', $userid);
			qa_db_query_sub('INSERT IGNORE INTO `qd_userpoints` (`userid`) VALUES (#)', $userid);
			
			// qa_db_userpointscount_update() is done once a day by the admin plugin
		}
```

**Comment by q2apro** [comment]
Since I have another (external) system that can create new users and does not fire the event `u_register` (no access), I ended up creating a new option for qa_options table: `qa_opt('cache_usercount')`.

The value of this option I am updating once per day.

I changed the files accordingly, where the `qa_opt('cache_userpointscount')` is used:

  - \pages\users-newest.php
  - \pages\users.php
  - \qa-include\plugins\qa-widget-activity-count.php
  - \qa-plugin\qa-widget-activity-count-plus.php
  - q2apro userprofile plugin: q2apro-userprofile-layer.php

And this is how to create/update the missing option:

		// own qa_opt for usercount
		qa_db_query_sub('
			INSERT INTO ^options (title, content) 
				SELECT "cache_usercount", COUNT(*) FROM `qa_users`
			ON DUPLICATE KEY UPDATE content = VALUES(content)
		');

**Comment by svivian** [comment]
> So as an idea: When creating a new user always add an entry to ^userpoints.

The problem with this is that the original site (the one storing the users) does not know anything about the other sites that are using its user tables. And it may not be able to access those other sites' databases (depending on how the MySQL user accounts are set up).

The only real way to solve it would be a cron job on each of the other sites that runs the user points recalculation.

**Comment by q2apro** [comment]
Yes, as I said:

> The value of this option I am updating once per day.

By having an "update date" field, if is not set today then run the count query. So this happens once a day (like a cronjob).
