### ISSUE TITLE
IIS PHP Server - External User avatar Images not showing

### ISSUE THREAD

**Issue by mauricio-sonegatti** [q2a/question2answer#627]
I did succeeded in my try to use Q2A on IIS, the only caveat right now is that the avatars are not showing, the code in qa-external-users is returning the avatar correctly, and the same code on Apache is working.
If someone can point me on the right direction, I would be very grateful.

**Comment by svivian** [comment]
Do you have a live site URL? What SSO integration are you using, Wordpress? Can you give an example of what is the URL returned from the external code, and what is the URL shown in the page?

**Comment by mauricio-sonegatti** [comment]
@svivian I don't have any live site url because I'm using it on the intranet.
The sso is a ldap configuration, and works flawless on Apache PHP.
I tried both this codes on the qa_avatar_html_from_userid

```
function qa_avatar_html_from_userid($userid, $size, $padding)
{
	require_once $_SERVER['DOCUMENT_ROOT'] . '/util.php';
	$f = get_avatar($userid);
	if (!$f) return null;

	$htmlsize = (int)$size;
		return '<img src="http://www.site.intranet/' . get_avatar($userid) . '"' .
			'width="' . $htmlsize . '" height="' . $htmlsize . '" class="qa-avatar-image" alt=""/>';
	
	max-height: %spx; width: auto; height: auto;">', $i, $size, $size);
}
```

I also tried like this:
```
function qa_avatar_html_from_userid($userid, $size, $padding)
{
	require_once $_SERVER['DOCUMENT_ROOT'] . '/util.php';
	$f = get_avatar($userid);
	if (!$f) return null;

	
	$i = 'data:image/jpeg;base64,' . base64_encode(file_get_contents($f));
	echo sprintf('<img class="qa-avatar-image" src="%s" style=" display: block; max-width: %spx; max-height: %spx; width: auto; height: auto;">', $i, $size, $size);
}
```
As I said before, it's working on the Apache PHP, with no problems whatsoever.
I saw this question http://www.question2answer.org/qa/6278/problem-with-avatar-avatar-can-not-be-saved that you have to enable file_uploads to enable the super-global variable $_FILE so it asks to process the avatar picture, but it's already enabled on my config.

I tried copying all the parameters from the apache php.ini to the iis php.ini, still it doesn't work.

**Comment by svivian** [comment]
What is the `get_avatar` function, I presume something custom for ldap?

And what is the HTML that you get on the page for the image? You'd have something like `<img src="http://www.site.intranet/path-to-avatar-jpg">`  does the URL you get definitely exist? Might be a problem with IIS serving files rather than Q2A.

**Comment by mauricio-sonegatti** [comment]
Yes its a custom function that gets the username.
The url is working and the file can be served by the iis.
Here are some screenshots:
IIS serving the image:
![iis_serving_image](https://user-images.githubusercontent.com/22504353/38945636-7c7424ec-430d-11e8-8e39-a5eac2ce2e30.PNG)
Q2A running on IIS
![q2a_iis](https://user-images.githubusercontent.com/22504353/38945637-7ca3394e-430d-11e8-9727-68b40c3b0ca6.PNG)

Q2A on APACHE:
![q2a_apache](https://user-images.githubusercontent.com/22504353/38945685-9dfbfc48-430d-11e8-8c3a-fc2fafcbf3e2.PNG)

Even when I print the function on IIS it serves the image without a problem. It really seems that the image is not being called on IIS.

**Comment by svivian** [comment]
Hey, don't know if you've fixed this by now, but I don't think there is any way for me to resolve it. We don't officially support IIS. But if you find the problem is caused by a bug in Q2A I'd be happy to marge a pull request.

**Comment by macvirii** [comment]
@svivian Hey Scott, I tried but couldn't get to why the avatar is not showing.
For now I stopped worrying about it because everything else is working.
If I discover something I'll make a PR for sure.
Thanks

**Comment by mauricio-sonegatti** [comment]
@svivian Hey Scott, I tried but couldn't get to why the avatar is not showing.
For now I stopped worrying about it because everything else is working.
If I discover something I'll make a PR for sure.
Thanks
