### ISSUE TITLE
Comma or Space as Separator - keeping special chars in tags

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#633]
Discussed on q2a [here](http://www.question2answer.org/qa/23938/special-characters-for-tags-how) and [here](http://www.question2answer.org/qa/803/special-chars-are-not-accepted-in-tags).

I want to add tags like `c++ datatypes`. With q2a v1.8.1 this gets filtered to `c datatypes`. Gideon said, use the comma instead, but this is not convenient.

The file /qa-include/app/format.php has `function qa_get_tags_field_value($fieldname)` which uses function `qa_string_to_words(...)`. Maybe we enter before the return in `qa_get_tags_field_value()` a replacement for whitespace ` ` to comma `,` and use the other return option... or find another way to handle this issue.

**Comment by svivian** [comment]
This was discussed a while back in #262. The short answer is, I'll aim to fix this at some point!
