### ISSUE TITLE
WYSIWYG Editor issue when handling Unicode character  

### ISSUE THREAD

**Issue by Rebekasara** [q2a/question2answer#635]
Hi, I faced a wired problem using wysiwyg editor. It was fine in Basic editor but when use wysiwyg editor for  other language it shows numerical HTML encoding of the Unicode character instead fonts in answer section?

**Comment by svivian** [comment]
Can you give an example of characters that mess up in the WYSIWYG editor? Have you modified the ckeditor config in any way?

**Comment by Rebekasara** [comment]
I actually fix that issue after uninstalling the plugin Hashtagger. Although you can see "I am using Bangla Language for my site. My keyboard is Unicode based call avro or unijoy. see the text example below. 
 ১৯ দশকের মধ্যবর্তী সময়| ভাষায় সমস্যা সমাধানের একটি নির্ভরযোগ্য মাধ্যম। এখানে আপনি আপনার প্রশ্ন করার পাশাপাশি অন্যদের প্রশ্নে উত্তর প্রদান করে অবদান রাখতে পারেন অনলাইনে বিভিন্ন সমস্যার সমাধানের জন্য সবথেকে বড় এবং উন্মুক্ত তথ্যভাণ্ডার গড়ে তোলার কাজে।"
