### ISSUE TITLE
duplicate function qa_get_logged_in_user_field in users.php

### ISSUE THREAD

**Issue by michaelphipps** [q2a/question2answer#640]
This is doing my head in.  There are two functions in users.php with the exact same function name.
I didn't think that was possible in PHP?

![image](https://user-images.githubusercontent.com/457561/40660964-e71ef2f6-6395-11e8-89dd-1383077df665.png)

I can't find any errors or warnings about it in error logs, but I just found it bizarre and figured I'd report it.

**Comment by SamGG** [comment]
Hi,
These definitions are part of a if-else control. One in the if, the other in the else. So no problem when running.
HTH

**Comment by michaelphipps** [comment]
Thanks - I just found the `if (QA_FINAL_EXTERNAL_USERS) {` if statement.
