### ISSUE TITLE
When I login to Admin I get "Please click again to confirm"

### ISSUE THREAD

**Issue by NievesGil** [q2a/question2answer#641]
Hi, I installed the Q&! software on my website at:

http://ireland2spain.com/

But I can't login to admin. When I enter my (correct) email and PW I get:
"Please click again to confirm"
Clicking again does nothing.
Any suggestions? Or can someone tell me where to get help with this?
I have no idea what the problem could be (it's not a browser or computer issue, because I can use the sandbox demo no problem). 
Thanks
Nieves

**Comment by svivian** [comment]
The "please click again to confirm" error usually comes from a problem with CSRF (cross site request forgery). There is a "code" field in the login form that's checked on form submission.

I can't see anything on your site that would be causing the problem. Have you made changes to the login form?

**Comment by NievesGil** [comment]
Thanks for responding. No, I haven't made any changes to ANYTHING since I installed the software. Two weeks later I still can't login, and there doesn't seem to be anywhere to get help/support (no one responded to my request for help on the Q&A forum).
If you can suggest any way to fix this - or point me to someone who can fix it for a reasonable fee - I'd appreciate it. If I can't get a solution soon I'm going to have to uninstall the whole thing and look for something else.
Thanks

**Comment by NievesGil** [comment]
Seriously - there's no one here who can offer help, advice, technical support, even for a fee?

**Comment by svivian** [comment]
Hi, sorry for the delay. Do you have access to error logs? If so, you can find the issue by setting `QA_DEBUG_PERFORMANCE` to true in your `qa-config.php` then trying to log in. You should see errors in your log starting with "PHP Question2Answer form security violation".

If you don't have access to logs, you could instead output the error to the browser. In `qa-include/app/users.php` around line 1388, replace `@error_log` with `echo` and you should see the error message.

**Comment by NievesGil** [comment]
Hi again,
I did all that, but I'm not getting any error message. I just can't login.
It's driving me nuts.
Could you (or anyone else here familiar with this software) take a look at my qa_config file and see if you can spot any mistakes?
[qa-config.txt](https://github.com/q2a/question2answer/files/2412067/qa-config.txt)
Thanks for any help/advice you can give.
