### ISSUE TITLE
Can add feature as Google Search Style AND?

### ISSUE THREAD

**Issue by hoogw** [q2a/question2answer#647]
Current search "aaa bbb", it will find aaa OR bbb.

Can you make it as google style use AND?

if search for "aaa bbb", it will find have both aaa AND bbb?

Google style search is very powerful to filter out unwanted results.

**Comment by hoogw** [comment]
how to choose different search module. ?

`function qa_get_search_results($query, $start, $count, $userid, $absoluteurls, $fullcontent)
{
	// Identify which search module should be used

	$searchmodules = qa_load_modules_with('search', 'process_search');

	if (!count($searchmodules))
		qa_fatal_error('No search engine is available');

	$module = reset($searchmodules); // use first one by default

	if (count($searchmodules) > 1) {
		$tryname = qa_opt('search_module'); // use chosen one if it's available

		if (isset($searchmodules[$tryname]))
			$module = $searchmodules[$tryname];
	}`

**Comment by svivian** [comment]
Actually Q2A search does use an 'AND' search of sorts, in the sense that it prioritises questions that have all the words included. So switching to an AND-only search would mean showing the same results at the top, but then stopping and not showing any more. In my opinion that's not very helpful, it's better to show more results where possible. If you look carefully you'll see that Google also sometimes shows results where one of the words is missing.

But yes it would be possible to create your own plugin that does what you want. Take a look at the [documentation here](https://docs.question2answer.org/plugins/) and the default search plugin in `qa-include/plugins/qa-search-basic.php`, you should be able to take that and modify for your needs. For example after the call to `qa_db_select_with_pending` you could remove entries from the `$questions` array, or make your own version of the `qa_db_search_posts_selectspec` to fetch only the posts you want from the database.

If you have any more questions feel free to ask on the [Q2A site](https://www.question2answer.org/qa/) as the Github repo is intended for bug reports only.
