### ISSUE TITLE
WP integration just for admin

### ISSUE THREAD

**Issue by QROkes** [q2a/question2answer#649]
Would be nice if we had the option to enable WordPress integration just for Admins, this way admins use WP login and all the other public users are forced to use the native login system.

I tried using conditional in config file:
```
require_once '/var/www/domain.com/htdocs/wp-load.php';
if ( is_user_logged_in() ) {
	define('QA_WORDPRESS_INTEGRATE_PATH', '/var/www/domain.com/htdocs');
}
```

It doesn't work because seems like just by having wp-load.php loaded is enough to activate WP integration.

**Comment by svivian** [comment]
Hello, thanks for the suggestion but I think it's too niche and outside the scope of core Q2A. Why not have admins use regular Q2A accounts? For what is only a handful of users it doesn't seem worth it.

However, in theory it could be possible by making your own [login plugin](http://docs.question2answer.org/plugins/modules-login/) that uses Wordpress, then have the admins use that.

**Comment by QROkes** [comment]
Ok. I understand!
Just to clarify, support for multiple login options is not "too niche". It's a very common feature.
Thanks for the link to the "login plugin" docs, definitely I will take a look to see if I can build my own custom solution.

**Comment by svivian** [comment]
> Just to clarify, support for multiple login options is not "too niche".

And Q2A supports that via plugins. And has support for Wordpress out-of-the-box. What you’re asking for is a very specific configuration that’s not quite one or the other. But as I said it should be doable with a plugin. Good luck!
