### ISSUE TITLE
Registration problem 

### ISSUE THREAD

**Issue by Jdweba** [q2a/question2answer#652]
Hi, 
the registration on my site is not working. It just returns to the register page and nothing is confirmed, no email is sent or no conformation. 

Here's the site: http://dv-eye.com/qtoa/
Version: 1.8.0
Installation : 332_41756

I'm getting this in console:

Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] qtoa
Loading failed for the <script> with source “http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. qtoa:176
The resource at “http://connect.facebook.net/en_US/all.js” was blocked because tracking protection is enabled.[Learn More] qtoa
Loading failed for the <script> with source “http://connect.facebook.net/en_US/all.js”. qtoa:1
The resource at “http://www.statcounter.com/counter/counter.js” was blocked because tracking protection is enabled.[Learn More] qtoa
Loading failed for the <script> with source “http://www.statcounter.com/counter/counter.js”. qtoa:1515
Loading failed for the <script> with source “http://connect.facebook.net/en/sdk.js”.

I am really not good with MySqL and data bases so really don't know how to fix this. 

Any help would be much appreciated.

**Comment by svivian** [comment]
Hi, sorry for the late reply. I can't see any reason why it wouldn't be working. If you leave certain fields blank the correct error messages come up.

Do you have any non-standard plugins installed? They could be causing issues. You have some users already so obviously some people were able to register at one time. Maybe you added something that broke the registration. Do you have any errors in your server logs when you try to register?

The errors in the console are not related to the function of Q2A, they're all separate scripts or being blocked by your browser.
