### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by lipsmega** [q2a/question2answer#655]
We need a good notification system thats build with the system. The plugin get slow over the time.

**Comment by okiaso** [comment]
I'm currently working on [Q2A Events Notification](https://github.com/okiaso/q2a-events-notification) plugin.
Features:
1). Site notifications
2). Email notifications
3). SMS notifications

Github: https://github.com/okiaso/q2a-events-notification

**Comment by svivian** [comment]
Notifications are being worked on for the next version.
