### ISSUE TITLE
Please Add AMP and CDN Support

### ISSUE THREAD

**Issue by tosunkaya** [q2a/question2answer#659]
Is it possible to add AMP and CDN support to Q2A?

my q2a page: https://tosunkaya.com/cevaplar/

**Comment by svivian** [comment]
What exactly do you mean by CDN support? What in Q2A does not support your CDN?

AMP support is something I've considered, but it's mostly a theming issue so you could make your own AMP theme.

**Comment by tosunkaya** [comment]
i have CDN on Amazon Cloudfront (https://s.tosunkaya.com) 
file: https://tosunkaya.com/cevaplar/qa-content/qa-global.js?1.8.1
cdn file (i want to use this): https://s.tosunkaya.com/cevaplar/qa-content/qa-global.js?1.8.1

also using local jquery files are totally unneeded when lots of cdns are available for jquery.
https://cdnjs.com/libraries/jquery/
https://code.jquery.com/
https://developers.google.com/speed/libraries/#jquery
https://www.jsdelivr.com/package/npm/jquery

also schema.org has errors and caching isnt working on latest 1.8.1
https://github.com/q2a/question2answer/issues/700
https://i.snag.gy/qw3G0W.jpg

**Comment by svivian** [comment]
There are different schools of thought on whether it's beneficial to use a CDN for JS. It involves extra DNS lookups, and in the case of jQuery it's quite fragmented across many versions, so users many not have it cached. [More details here](https://www.question2answer.org/qa/41884/does-locally-stored-jquery-rather-serving-google-which-faster?show=41920#a41920)

However, you can use an advanced theme to change the URLs of any JS files. [Here is one example](https://www.question2answer.org/qa/9739/how-to-insert-jquery1-6-2) how to do that, there are more on the Q2A site.

Closing this as it's a feature request. You can ask for more help on the Q2A site.

**Comment by PELock** [comment]
https://www.question2answer.org/qa/85850/question2answer-use-jquery-cdn-plugin
