### ISSUE TITLE
Language creation - missing files

### ISSUE THREAD

**Issue by techmandan** [q2a/question2answer#667]
How do I create a new language, without the files? At the tutorial, it says it has 8 files, but the english has only the admin, with 2 sentences..

**Comment by techmandan** [comment]
Find myself: qa-includes contains lang which is used as default when string is missing.
Update your tutorials at the webpage!

**Comment by svivian** [comment]
The bottom of the page shows how to customize select phrases if desired. It's usually assumed that if you are translating Q2A you'll need to translate the majority of the phrases.

If there are some improvements to the wording in the docs you can contribute over here: https://github.com/q2a/q2a.github.io
