### ISSUE TITLE
 count(): Parameter must be an array or an object that implements Countable on php7.2

### ISSUE THREAD

**Issue by eboye** [q2a/question2answer#674]
https://github.com/q2a/question2answer/blob/1a9496fd1c5bc15ceb29c1ad7ae452b5aba3b4da/qa-include/app/format.php#L384

This line makes a warning, it's easily fixable by wrapping it with

```
if ( isset( $favoritemap['category'] ) ) {
}
```

**Comment by pupi1985** [comment]
That has already been fixed in the bugfix branch: https://github.com/q2a/question2answer/blob/40f15d44a49a21d7640e31c36e2facb1c74c4c06/qa-include/app/format.php#L384

BTW, there is no need to wrap as PHP uses short-circuit operators.

**Comment by eboye** [comment]
OK, cool, then close the issue ... I just switched to 1.8.0 final on my local machine to test it and found this one ;)
