### ISSUE TITLE
Can I insert html with tag in editor?

### ISSUE THREAD

**Issue by hoogw** [q2a/question2answer#677]
For example, 

    I want to imbed a iframe tag in editor, how to do that?

I try this one,  `<h1> test</h1>` it does not work in q2a, but it works fine here at github editor.

<h1>

   test

</h1>

how to make it as HTML editor?

**Comment by hoogw** [comment]
here editor at github is a HTML editor, 

   if I type, `<h1> test</h1>`

if will recognize h1 tag, and display it as big fond test.

 `<h1> 
    test
</h1>`

**Comment by svivian** [comment]
I think this is answered in your other issue #681 

The CKEditor that comes with Q2A has a dropdown menu allowing you to set heading 1.
