### ISSUE TITLE
"Messages" page displays error "User accounts are handled by external code" if using external SSO

### ISSUE THREAD

**Issue by trulyfurqan** [q2a/question2answer#679]
Hi,

**Note:** I'm using external SSO.

I'm getting an error on messages page "User accounts are handled by external code" if I directly open the page using its URL.

Example URL: www.some-domain.com/qa/messages

I've recently found on the Q2A community forum that Wall-Post & Private Messaging system doesn't work if you are using external authentication. So, I think the URL must also not work (display 404 page instead) as it looks bad right now and also reveals some error information.

=====

Q2A version: 1.8.0

**Comment by svivian** [comment]
How were you getting to the messages page? There should not be a link if you're using external logins.

**Comment by trulyfurqan** [comment]
@svivian By directly typing the URL of messages page in the address bar of browser.

**Comment by svivian** [comment]
Sorry my bad, you did say that in your post. Yes it probably does make sense to serve a 404 code. But since there are no links to page it’s very unlikely anyone would ever see the page, and it won’t show up in Google.

**Comment by svivian** [comment]
Fixed in 7a246c8 (will be in Q2A 1.8.6).
