### ISSUE TITLE
how to pin post on top?

### ISSUE THREAD

**Issue by hoogw** [q2a/question2answer#682]
I found the solution, it works for 1.8.x

By add plugin, go to

https://github.com/NoahY/q2a-featured

download plugin,  unzip, copy whole folder to under qa-plugin/qa-featured

Then, navigate to your site, go to Admin -> Plugins, find the Featured Questions list, enter featured question ids seperated by commas, then click 'Save'.

**Comment by pupi1985** [comment]
Why did you create an issue that you solve in the description of the issue?
