### ISSUE TITLE
Why are images stored in blob, not in the file system?

### ISSUE THREAD

**Issue by da55y** [q2a/question2answer#686]
It works slower. Nginx faster gives static files than working on a php script + the query to the database. Photo profiles, pictures in questions and answers, if the user base 100.000 + 1.000.000 with photos - it will be a heavy load on the cpu/web server/database server?

**Comment by pupi1985** [comment]
As I mentioned in the same question you posted in the Q&A site, you can change that in qa-config.php if you don't like the default behavior.
