### ISSUE TITLE
Query works on MySQL (phpmyadmin) but not in qa_db_read_one_value(qa_db_query_sub())

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#687]
Query works flawlessly on MySQL (phpmyadmin) but not in qa_db_read_one_value(qa_db_query_sub()). Is that a bug?

```
$userranking = qa_db_read_one_value(
          qa_db_query_sub('
               SET @row_number = 0; 
               SELECT 
                    (@row_number:=@row_number + 1) AS num
               FROM
                    `^userpoints`
               WHERE userid = #
               ORDER BY points DESC
           ', $userid)
);
```
Seems that I cannot specify the `SET @row_number = 0; ` in the same query. How to set it then? Or using another query function?

PS: My goal is to get the user ranking based on the user points.

**Comment by q2apro** [comment]
Solution:

function custom_get_my_ranking($userid)
{
    $userranking = qa_db_read_one_value(qa_db_query_sub(
    'SELECT rank
    FROM (SELECT @row_number:=@row_number+1 AS rank, userid 
        FROM `^userpoints`, (SELECT @row_number := 0) r 
        ORDER BY points DESC) t 
        WHERE userid = $', 
    $userid
    ), true);
    return $userranking;
}

Credtis to https://www.question2answer.org/qa/69172/query-phpmyadmin-qa_db_read_one_value-qa_db_query_sub?show=69180#a69180

Still wondering why two statements do not work in the qa_db_query_sub().

**Comment by svivian** [comment]
The problem is that you're trying to run 2 statements at once. The DB functions in Q2A use `mysqli_query` which only allows one query at a time. That's just how PHP has always worked. I think it's partly a security measure to prevent SQL injection executing any query.

Looks like you've found your solution so I'll close this.
