### ISSUE TITLE
Hack attempt has thrown PHP Notice:  Array to string conversion qa-base.php on line 1649

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#691]
I was wondering to see several entries in my error_log:

> PHP Notice:  Array to string conversion in /public/qa-include/qa-base.php on line 1649

The code line 1649 is:

     $paramsextra .= (strlen($paramsextra) ? '&' : '?') . urlencode($key) . '=' . urlencode((string)$value);

Link: https://github.com/q2a/question2answer/blob/dev/qa-include/qa-base.php#L1617

Here is the Apache Access log:

```
46.148.26.2 - - [19/Nov/2018:16:32:30 +0100] "GET / HTTP/1.0" 301 407
46.148.26.2 - - [19/Nov/2018:16:32:30 +0100] "GET / HTTP/1.0" 301 411
46.148.26.2 - - [19/Nov/2018:16:32:31 +0100] "GET / HTTP/1.0" 200 84219
46.148.26.2 - - [19/Nov/2018:16:32:31 +0100] "POST /?q=/user/password&name[%23post_render][0]=printf&name[%23markup]=ABCZ HTTP/1.0" 200 87042
46.148.26.2 - - [19/Nov/2018:16:32:32 +0100] "POST //user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax HTTP/1.0" 404 9654
```

PHP Access log:

```
46.148.26.2 - [19/Nov/2018:16:32:31 +0100] "GET /index.php" 200 0 - 24441 13128 0.057 4194304 52.94% 0.00% "/"
46.148.26.2 - [19/Nov/2018:16:32:31 +0100] "POST /index.php?q=/user/password&name[%23post_render][0]=printf&name[%23markup]=ABCZ" 200 47 - 24441 13128 0.052 4194304 76.78% 0.00% "/?q=/user/password&name[%23post_render][0]=printf&name[%23markup]=ABCZ"
46.148.26.2 - [19/Nov/2018:16:32:32 +0100] "POST /index.php?qa-rewrite=user/register&element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax" 404 129 - 24441 13128 0.022 4194304 45.25% 0.00% "//user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax"
```

I have checked the IP, it's a hack bot from Ukraine.

I think we should not allow such parameters to create PHP notices or warnings or errors.

Can we fix it?

**Comment by q2apro** [comment]
Would this be a secure fix?

	if (isset($params))
		foreach ($params as $key => $value) {
			if(!is_array($key) $$ !is_array($value)) {
				$paramsextra .= (strlen($paramsextra) ? '&' : '?') . urlencode($key) . '=' . urlencode((string)$value);								
			}
		}
	}

It's in the end of `function qa_path($request, $params = null, $rooturl = null, $neaturls = null, $anchor = null)`, see https://github.com/q2a/question2answer/blob/dev/qa-include/qa-base.php#L1617

**Comment by svivian** [comment]
This has been fixed. Your suggestion was basically the correct one, but array keys cannot be arrays so that bit wasn't needed. Thanks for reporting!

Also to be clear, the "hack attempt" is not for Q2A, it is a Drupal hack attempt. It just happened to cause this PHP Notice in Q2A.
