### ISSUE TITLE
Add filetype to embedded file/image to make filetype "visible"

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#696]
I faced some scenarios, where it would be great to have the filetype in the embed link. So instead of:

`/?qa=blob&qa_blobid=6085357601918442960`

it could be:

`/?qa=blob&qa_blobid=6085357601918442960&type=png`

But for some jquery plugins we need a `.png`, `.jpg` etc. So even better:

`/?qa=blob&qa_blobid=6085357601918442960&type=file.png`

This way such plugins could pick up the correct graphic file.

The alternative of adding a `class` to the `<img src="..." alt="..." class="image-png">` does not work for me, because I filter all class and id attributes using HTMLawed.

This is very helpful for jquery parsing of links and transforming them, as well as changing the HTML content with PHP.

Why I stumbled over this issue again:

I want to make a GIF player http://rubentd.com/gifplayer/ but for this, I need to know the filetype GIF frontend.

**Comment by svivian** [comment]
Can you use some different attributes? Such as `data-type="png"` ?

Also, with your GIF example you need to have a static png file in the `src` attribute, so you will need to modify the links yourself anyway on the server-side (to change gif to png) so you can just add your parameter then. You can look up the filetype in the database (`qa_blobs` table).

**Comment by q2apro** [comment]
I actually realized that using the SCEditor plugin, I add the filename to the `alt` attribute. Which results in `alt="filename.gif"`. So now I am using Jquery and get all files accordingly:

`$('img[alt=*gif]')`

This can be used as a valid workaround.
