### ISSUE TITLE
Caching Gives 500 Internal Server Error + Schema.Org Errors

### ISSUE THREAD

**Issue by tosunkaya** [q2a/question2answer#700]
If you enable disk caching, cache setting page cant be loaded anymore and shows 500 internal server error. It was working on 1.8.0, i updated to 1.8.1 it has been broken. I deleted cache files. permission is 755.
Please fix the bug.

I saw someone updated schema.org code and fixed. but "mainentity" hasnt be added (include/pages/question.php).
Please help me with this.

Also can u change jquery local file to a cdn like google, code.jquery, cdnjs, jsdelivr

my q2a: https://tosunkaya.com/cevaplar/

**Comment by tosunkaya** [comment]
fixed by downloading bugfix (https://github.com/q2a/question2answer/tree/bugfix)
thanks to @svivian
https://www.question2answer.org/qa/70061/schema-org-errors?show=70110#c70110

**Comment by chongshengdz** [comment]
do you update to the latest version?
