### ISSUE TITLE
Turkish Characters Problem

### ISSUE THREAD

**Issue by tosunkaya** [q2a/question2answer#701]
Turkish characters on the question description shown on homepage as broken.
also if someone comments to any question, Turkish characters are shown as broken too in latest version. it was seamless. How can i fix?

`teşekkürler` is shown as `teşekk&uuml;rler`

You can see the comment problem on this page: https://tosunkaya.com/cevaplar/45/dalg%C4%B1%C3%A7-t%C3%BCplerinde-nitrojenin-yerine-hangi-gaz-kullan%C4%B1l%C4%B1r
see description problem on: https://tosunkaya.com/cevaplar/457/hangisi-frans%C4%B1z-yazar-jc-grangein-eseri-de%C4%9Fildir
homepage: https://tosunkaya.com/cevaplar/

utf-8 no bom turkish is already selected on mysql.

screenshot of q page: https://i.snag.gy/9CWYLu.jpg
homepage screenshot: https://i.snag.gy/s6kD8t.jpg

Please help me @svivian .

**Comment by svivian** [comment]
It works for me on Q2A 1.8.1. Which editor are you using? Does the problem still happen with the stock WYSIWYG editor or Basic Editor that comes with Q2A?

**Comment by tosunkaya** [comment]
> It works for me on Q2A 1.8.1. Which editor are you using? Does the problem still happen with the stock WYSIWYG editor or Basic Editor that comes with Q2A?

It's stock WYSIWYG. How can i fix, do you have any idea?
