### ISSUE TITLE
Schema.org error

### ISSUE THREAD

**Issue by tryazi** [q2a/question2answer#702]
I'm getting a Schema error. The name tag for Mainetity appears not attached. Can you help.

https://search.google.com/structured-data/testing-tool/u/0/?hl=tr#url=https%3A%2F%2Fwww.odevbul.org%2Fodev-sor%2F1451%2Fodevlerimizi-yapmadigimiz-zaman-sorunlarla-karsilasiriz

**Comment by svivian** [comment]
I've posted details on the Q2A site: https://www.question2answer.org/qa/70061/schema-org-errors-mainentity-missing
The latest code in the bugfix branch should fix this for most themes. I've sent a PR to the Donut theme with a potential fix.
