### ISSUE TITLE
PHPDoc updates - parameter types

### ISSUE THREAD

**Issue by svivian** [q2a/question2answer#705]
Running a PHPStan (a static analysis tool) on the Q2A codebase throws up a whole bunch of PHPDoc errors, as many of the 'DocBlocks' are missing a type for the parameter. For example:

```php
/**
 * Check if $post is by user $userid, or if post is anonymous and $userid not specified, then
 * check if $post is by the anonymous user identified by $cookieid
 * @param $post
 * @param $userid
 * @param $cookieid
 * @return bool
 */
function qa_post_is_by_user($post, $userid, $cookieid)
```

This should be replaced with:

```php
/**
 * Check if $post is by user $userid, or if post is anonymous and $userid not specified, then
 * check if $post is by the anonymous user identified by $cookieid
 * @param array $post
 * @param int $userid
 * @param string $cookieid
 * @return bool
 */
function qa_post_is_by_user($post, $userid, $cookieid)
```

Note the array/int/string after `@param`. Fixing these will help code analysers know what the types should be and can give warnings if incorrect types are passed into functions.

I'm opening this issue in case anyone wants to help out by sending a PR. A few tips:

- Please target any PRs to the `dev` branch.
- I suggest starting with just a few functions (e.g. one file) to get the hang of it. There's an example set of changes in 93bbf89.
- There is a [guide on DocBlock here](http://docs.phpdoc.org/guides/docblocks.html) and a [list of types here](http://docs.phpdoc.org/guides/types.html) for reference.
- Most of the functions requiring attention are in the files from the `qa-include/app/` and `qa-include/db/` folders.
- Usually, posts (`$post`, `$question` or `$answer` variables) are `array`; IDs (`$postid`, `$categoryid`) are usually `int` (`$userid` is `mixed` due to external user integration). Most other parameters will probably be strings.
- If a parameter can be multiple types you can use `mixed`.
- If you're not sure of a type, leave it out. Every little helps and the rest can be filled in later.

**Comment by svivian** [comment]
> Actually $userid is usually mixed

Yes that's true, external user IDs can be any type.

**Comment by pupi1985** [comment]
Finally #734
