### ISSUE TITLE
Change schema link from http://schema.org/ to https://schema.org/

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#709]
Three occurences:

\app\format.php
\app\users.php
\pages\question.php

`http://schema.org/` should be `https://schema.org/` 

See https://schema.org/docs/faq.html#19

> There is a general trend towards using 'https' more widely, and you can already write 'https://schema.org' in your structured data. Over time we will migrate the schema.org site itself towards using https: as the default version of the site and our preferred form in examples. However 'http://schema.org' -based URLs in structured data markup will remain widely understood for the forseeable future and there should be no urgency about migrating existing data. This is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine.

**Comment by svivian** [comment]
Thanks, fixed.
