### ISSUE TITLE
How to make question page as home page

### ISSUE THREAD

**Issue by abuzer-firdousi-confiz** [q2a/question2answer#711]
I want to make this page https://pucho.pk/questions as homage page.

**Comment by svivian** [comment]
This can be done by editing the `$QA_CONST_PATH_MAP` variable in config. See [this question](https://www.question2answer.org/qa/28676/how-do-i-change-the-default-homepage-to-activity-page) for details.

And in future please ask questions on the Q2A site, github issues is for bugs. Thanks :)
