### ISSUE TITLE
Please add hooks/ handles so we can add styling to messages at qa-lang*.php

### ISSUE THREAD

**Issue by amint** [q2a/question2answer#73]
For messages listed in qa-lang*.php files,  I wanna make part of a message bold. For instance this one:

Privacy: Your email address will only be used for sending these notifications.

something like:
```
Privacy: Your email address will <b>only be </b> used for sending these notifications.
```
but
```
...<b> only be used</b>... 
```
would not work as messages are HTML stripped 

Any tips please?

**Comment by svivian** [comment]
Sorry for the super late reply. Unfortunately we cannot allow HTML in the language strings for various reasons.

However, it would be possible to customise this message in an advanced theme by overriding the `form_field_rows` function. Check the variable `$this->context->field_key`, if that is 'email' then you can edit `$field['note']` to whatever you like. You can even use `$field['note'] = htmlspecialchars_decode($field['note']);` to output the language string as HTML.
