### ISSUE TITLE
where is mysql file

### ISSUE THREAD

**Issue by chandrabhanchaudhary** [q2a/question2answer#730]
i cannot file with .sql extension to set up database

**Comment by thopd88** [comment]
There is no sql file. You need to create a new database then create a qa-config file base on example file (on root folder).

**Comment by svivian** [comment]
[Check out the documentation](http://docs.question2answer.org/install/), there are full instructions on how to install Q2A. You need to create the (blank) database manually, but all the tables are installed when running the web setup.

If you have more questions please [ask on the Q2A Q&A](https://www.question2answer.org/qa/)

**Comment by chandrabhanchaudhary** [comment]
But Is Showing Error 
![image](https://user-images.githubusercontent.com/43430823/51423048-740a4d80-1bdf-11e9-80ba-08d579da0385.png)

See this Image
and my user name is root and password 123456

**Comment by svivian** [comment]
If you’re using MySQL 5.7 it may be that you can’t log in with root anymore. See https://www.question2answer.org/qa/71910/error-1698-28000-access-denied-for-user-root%40-localhost?show=71917#a71917

You can try setting up a different user to log into Q2A.
