### ISSUE TITLE
Timeout when opening the plugin options under admin

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#742]
Noticed here: https://www.question2answer.org/qa/72828/stop-spam-and-editor-plugin-not-working-and-down-whole-website

And can confirm that I run into the same problem, once in a while.

Opening admin/plugins then "options" (especially with [SCeditor](https://github.com/q2apro/q2apro-sceditor-premium)).

Empty error logs :(

**Comment by pupi1985** [comment]
1. What is exactly a _timeout_?
1. Does the _timeout_ happen if you remove all custom plugins but you leave only SCeditor in the plugin directory?
1. Does the _timeout_ happen if you remove the *Plugin Update Check URI* from the `qa-plugin.php` file?

**Comment by q2apro** [comment]
> 1. What is exactly a _timeout_?

I click on options, the loading of the page starts, and nothing happens. Loading forever...

I found a way to fix this: Opening my serverpilot admin panel, changing the PHP version, then the server restarts... and is back again.

<br>

> 2\. Does the _timeout_ happen if you remove all custom plugins but you leave only SCeditor in the plugin directory?

I cannot remove plugins because it is a production site! On localhost it never happened.
<br>

Maybe user Nico is right (q2a forum):

> Most likely this will become a problem for sites that actively use AJAX and make several simultaneous requests. The easiest way to solve this problem is to call the session_write_close () function as soon as all the required changes to the session have been made, preferably closer to the beginning of the script. You can also use another session mechanism that supports concurrent access.

> It follows: situations in which simultaneous access to a session is blocked always occurred with any hoster.

**Comment by pupi1985** [comment]
> 3. Does the _timeout_ happen if you **remove** the _Plugin Update Check URI_ from the `qa-plugin.php` file?

BTW, that includes all your plugins and also includes metadata.json files. Please, try that and report back.

**Comment by q2apro** [comment]
Removing the "Plugin Update Check URI" did not solve the problem. The server is still loading ~3 min until getting back to responsive.

I have added a metadata.json file (was missing before), same, no changes.

In the Chrome Console I found this message:

> Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details

**Comment by pupi1985** [comment]
That's interesting. You did a test I was about to suggest next. If you comment [this line](https://github.com/q2a/question2answer/blob/b5bb3f374dd9f62bd2a8723392e4473afa1e583f/qa-include/pages/admin/admin-plugins.php#L177) and retry the last test you did, do you get the same results as before?

**Comment by q2apro** [comment]
That seems to be the culprit! 👍 

Now it loads immediately!

**Comment by yerbol89** [comment]
@pupi1985 Yes. After comment this line plugins options open load fast. Thanks you!

**Comment by pupi1985** [comment]
I knew that was the issue from the beginning. The only thing that is hard for me to understand is why would that affect an instance on other browser.

Are you 200% sure that if you open the admin/plugins page in Chrome and then go to FireFox and access the All Activity section, the server doesn't immediately respond?

**Comment by q2apro** [comment]
> Are you 200% sure that if you open the admin/plugins page in Chrome and then go to FireFox and access the All Activity section, the server doesn't immediately respond?

My mistake. It only effects Chrome. The website in Firefox is still running.

**Comment by PELock** [comment]
> That's interesting. You did a test I was about to suggest next. If you comment [this line](https://github.com/q2a/question2answer/blob/b5bb3f374dd9f62bd2a8723392e4473afa1e583f/qa-include/pages/admin/admin-plugins.php#L177) and retry the last test you did, do you get the same results as before?

This lagging occurs in PHP 5.6, 7.2 and 7.3, works like a charm after commenting this line.

**Comment by pupi1985** [comment]
Probably, I wasn't clear. The lag is in your browser, not in your server :) It is just sending many requests to check for new version upgrades. Most likely this is aggravated by the q2apro.com domain timing out. Removing the version checks for each `metadata.json` and `qa-plugin.php` file with that domain should mitigate the issue.

**Comment by svivian** [comment]
I think it would make sense to do 1 AJAX request for checking all plugin versions, rather than 1 per plugin. And potentially cache the results for a while, e.g. only check for updates once a day.

**Comment by pupi1985** [comment]
Yes. Maybe even more than a day, for example a week or a couple of weeks (there aren't so many updates to plugins). But in addition to this, next to the "Save options" button at the bottom, there could be a "Check for udpates" button to manually fire this process.

**Comment by taufik7000** [comment]
Hello, i have same situation on here. How to fix it ?
