### ISSUE TITLE
PHP Question2Answer MySQL query error 42000: SQLSTATE[42000]

### ISSUE THREAD

**Issue by LeVeloute** [q2a/question2answer#744]
Hi, I got a little problem (Ubuntu 18.04). On a fresh install of : PHP7, MySQL 5.7 and quenstion2answer from git i got an error.

If i change the BONUS POINT of my admin user, it will display : 

```
A Question2Answer database query failed when generating this page.

A full description of the failure is available in the web server's error log file.
```

If after that i try to access the userlist page, the same error on the browser will appear. With this error on log : 

`PHP message: PHP Question2Answer MySQL query error 42000: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''30') y ON qa_users.userid=y.userid JOIN qa_userpoints ON qa_users.userid=qa_use' at line 1 - Query: SELECT qa_users.userid, handle, points, flags, qa_users.email, BINARY avatarblobid AS `avatarblobid`, avatarwidth, avatarheight FROM qa_users JOIN (SELECT userid FROM qa_userpoints ORDER BY points DESC LIMIT ?,?) y ON qa_users.userid=y.userid JOIN qa_userpoints ON qa_users.userid=qa_userpoints.userid
`
Is there any settings that i need to adjust ? ( i made 2 fresh install with the same problem).

Thank you by advance :)

Best regards,

LeVeloute

**Comment by svivian** [comment]
Which version are you using? If you're downloading from Github, make sure to use the Releases page, or switch to the master branch. The dev branch is unstable.

**Comment by LeVeloute** [comment]
Ow... Okay that was just that 👍 
Thanks for you quick answer 😄
