### ISSUE TITLE
Not GDPR compliant: users can't delete themselves

### ISSUE THREAD

**Issue by gturri** [q2a/question2answer#747]
Hi,

According to my attempts and to the lack of reply on https://www.question2answer.org/qa/66428/there-any-add-that-allows-the-user-from-profile-delete-account it looks like a user can't delete himself (an admin can delete a user, but a user can't do it himself).

It's a bit annoying because it means it's not really compatible with the European privacy rules GDPR (which require that a user can easily delete his private data. (Having to ping an admin is not really an easy way to delete his private data))

It would hence be awesome to add this feature so that European webmasters can keep using this tool!

**Comment by gturri** [comment]
BTW, I might add that I'd be willing to propose a pull request, but I'd appreciate some pointers to implement this feature properly (in particular I guess that to implement it without introducing a security flaw it should probably involve checking a session token at some point, and I would appreciate pointers to understand how it could be done)

**Comment by ProThoughts** [comment]
@gturri , agree with you. nice feature suggestion. Once user is deleted then all his posts should be by user "anonymous".

**Comment by arjunsuresh** [comment]
I was also trying same. The problem of making it anonymous is later on we may not be able to identify who posted those at least by a fake identity. What about giving the posts a pseudo name say anonymous1, anonymous2 etc. ?

**Comment by gturri** [comment]
Good question...
I think that the most important is to remove the private data, so in particular the ips and email. I'm not a GDPR expert but I think that as long as this is respected then any implementation would likely work.

**Comment by svivian** [comment]
The stuff I've seen on GDPR is incredibly vague and up for interpretation. I'd say emailing/PMing an admin to delete your account is pretty easy from the user perspective. That's not to say I'm against this request.

Deleting a user is quite a destructive action, so this needs to be done carefully. Typically how other sites do it is by "closing" an account for a set period (e.g. a month) to give the user time to undo it if they wanted. Then if the user doesn't come back it gets deleted.

As for usernames, we could take the original user ID and use that for the name, e.g. `user2845` or `anonymous2845`. But whatever name you choose there is always a possibility of conflict with a real username - anyone could come along and register the name you assigned to a deleted user.

**Comment by jairlopez** [comment]
Should administrators be able to hide all the posts in an account that has been closed like this?

**Comment by jairlopez** [comment]
It’s possible. I recently was able to implement this feature as described above as a plug-in but it overrides a lot the core functionality:
* 12 standard pages
* 30 standard functions, 10 of them by overrides
* 2 new database tables

I’m not sure whether this feature should be included in Q2A but I’m afraid it’ll mess up other plug-ins if it’s implemented as another plug-in itself.

**Comment by bertrandgorge** [comment]
I had a talk with a GDPR specialist, and apparently it's ok if there's a clear way to request the account deletion somewhere. Same as being able to download someone own data, you don't have to implement it, you have to fulfill the requests...

Now, as far as the posts are concerned, it appears that the right way to do it is to leave the posts as they are, but change the name of the deleted owner. Going further, it should be made possible to also anonymise the owner name/username in the posts content (if a platform uses @ stuff).

All in all, as Vivian says, GDPR is vague on purpose. The point is to be aware of user's privacy rights, and to act accordingly depending on the size of your platform and the impact it can have if something goes wrong. All platforms are not expected to be as strong as facebook (maybe not the best example :-)....
