### ISSUE TITLE
PHP Question2Answer MySQL query error 1175

### ISSUE THREAD

**Issue by rishabhcha** [q2a/question2answer#748]
I'm facing this error in update queries:

```PHP Question2Answer MySQL query error 1175: You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column - Query: UPDATE qa_words AS x, (SELECT qa_words.wordid, COUNT(qa_titlewords.wordid) AS titlecount FROM qa_words LEFT JOIN qa_titlewords ON qa_titlewords.wordid=qa_words.wordid WHERE qa_words.wordid IN (2,9) GROUP BY wordid) AS a SET x.titlecount=a.titlecount WHERE x.wordid=a.wordid, referer: http://172.16.1.158:10800/index.php/ask```

In database I can't set safe update to false(policy).
One way is to change in the application level and before every query I do:
```SET SQL_SAFE_UPDATES = 0;```

Is there a way to set SET SQL_SAFE_UPDATES = 0 for all query from a single file change.

Or is there any better solution to this?

**Comment by amangoyal22** [comment]
Add this line after making the connection with the db.

`$qa_db_connection->query("SET SQL_SAFE_UPDATES=0");`

**Comment by rishabhcha** [comment]
Thanks @amangoyal22 it worked.
