### ISSUE TITLE
Best answer select event twice or three times

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#749]
Once reported in the forum: https://www.question2answer.org/qa/22476/best-answer-select-event-twice-bug this bug still exists.

In the liveticker it looks like this:

![image](https://user-images.githubusercontent.com/6764548/57057820-4b045900-6cb4-11e9-939f-5003afbe1519.png)

In the database:

```
2019-04-30 13:03:31 | 80.243.57.124 | 24807 | Alpha99 | NULL | a_select | parentid=627898	parent=array(71)	postid=627915	answer=array(46)
-- | -- | -- | -- | -- | -- | --
2019-04-30 13:06:05 | 80.243.57.124 | 24807 | Alpha99 | NULL | a_unselect | parentid=627898	parent=array(72)	postid=627915	answer=array(72)
2019-04-30 13:06:06 | 80.243.57.124 | 24807 | Alpha99 | NULL | a_select | parentid=627898	parent=array(72)	postid=627915	answer=array(72)
2019-04-30 13:06:42 | 80.243.57.124 | 24807 | Alpha99 | NULL | a_unselect | parentid=627898	parent=array(72)	postid=627915	answer=array(72)
2019-04-30 13:06:43 | 80.243.57.124 | 24807 | Alpha99 | NULL | a_select | parentid=627898	parent=array(72)	postid=627915	answer=array(72)
```

Same problem with the votes sometimes, already reported here (without any reply): https://github.com/q2a/question2answer/issues/571

The question is how can we prevent **multiple ajax requests** of the same kind, so that multiple "best answer selected" events are avoided.

One way I see is to check if the "best answer" is already selected with this ID, then just skip the event.

Another way would be to have a time span of maybe 10 seconds to have only one event of this kind.

----

More info from the [q2a post](https://www.question2answer.org/qa/22476/best-answer-select-event-twice-bug):

> As I disabled best answer voting using Jquery. So after chosing best answer, the button gets disabled and hidden. Even when the user visits his question again, he cannot click on best answer anymore (hidden by JS).
> PS: The error does not happen every day, just once or twice a week. But why? ... :(
> Note: Couple of months ago I realized that users can still select another answer as best, which unselected the previous selected answer. I removed this as well but still the same double event.
> Here is an example of events in the same second that you might find in your eventlog table as well:

```
userX | in_a_select | parentid=18551    parent=array(66)    postid=18553    answe...
-- | -- | --
NULL | a_select | parentid=18551    parent=array(66)    postid=18553    answe...
userX | in_a_unselect | parentid=18551    parent=array(66)    postid=18553    answe...
NULL | a_unselect | parentid=18551    parent=array(66)    postid=18553    answe...
userX | in_a_select | parentid=18551    parent=array(65)    postid=18553    answe...
NULL | a_select | parentid=18551    parent=array(65)    postid=18553    answe...
```

![image](https://user-images.githubusercontent.com/6764548/57057908-e8f82380-6cb4-11e9-9cbd-03b95233132a.png)

> Extra note: When the user clicks on "best answer" the js function qa_answer_click() gets called. The first thing I am doing there is to hide "best answer" option using $(".qa-a-selection").hide(); However, even if the button is not displayed and thus not clickable by the user anymore, the bug above happens!

Gideon wrote: 

>I don't think it's likely to do with this, since I don't use jQuery to bind the events.

q2apro:

> I checked my server logs for the selection request (great tip btw), 4 requests within the same second: 

```
16:40:14 "POST / HTTP/1.1" 200 1914 "/30549/exponential-und-logarithmusfunktion"
16:40:14 "GET /qa-theme/customtheme/post-selected-bg.png HTTP/1.1" 200 471 "/30549/exponential-und-logarithmusfunktion"
16:40:14 "POST /30549/exponential-und-logarithmusfunktion HTTP/1.1" 302 586 "/30549/exponential-und-logarithmusfunktion"
16:40:14 "GET /30549/exponential-und-logarithmusfunktion?show=30582 HTTP/1.1" 200 9976 "/30549/exponential-und-logarithmusfunktion"
```

> As there are 2 POST events, I still guess that it is an Ajax problem. Maybe you can see the issue better than me?

Gideon:

> The Ajax request is POST / so there's only one. The most likely problem is that something in a plugin caused the Ajax response to be invalid, leading the click to be submitted again in a non-Ajax fashion. Check your server's error_log. Also you can confirm this if the page refreshes.

> Only "POST /" is the Ajax request - "POST /30549/exponential-und-logarithmusfunktion" is a non-Ajax submission.

q2apro:

>I checked my installation: "in_a_select" only appears in NoahY's history plugin: https://github.com/NoahY/q2a-history The event is probably set in qa-history-check.php line 55, $oevent = 'in_'.$event; where $event is 'a_select'.

**Comment by pupi1985** [comment]
As you can see the user is selecting and then unselecting the answer. I see no issue with that. The votes issue is 100% different because the user is firing the same event many times without coming back to the previous state (e.g.: 3 new upvotes without nil/down votes in between them).

**Comment by q2apro** [comment]
> selecting and then unselecting the answer

That is not true. I remove the select button with jquery after the first click.

**Comment by pupi1985** [comment]
The data is consistent in the database. You don't need HTML, CSS or JavaScript to fire web requests. That's not a bug

**Comment by q2apro** [comment]
I am not firing requests, I am preventing them by removing the buttons (best answer select) so that the user cannot click on them again. But still, three events are sent...

**Comment by pupi1985** [comment]
You can't *prevent* firing HTTP requests by hiding buttons. Furthermore, you can't prevent them at all. You just need to react properly to them. The server is reacting as it should.

Also, there are not 3 events sent but rather 5. You need to count the unselects as well. Everything is fine from that logs' perspective.

If you don't want to keep track events that happen in less than X seconds, then that's a new feature request, but is definitely not a bug.
