### ISSUE TITLE
Search don't work

### ISSUE THREAD

**Issue by jcubic** [q2a/question2answer#750]
I'm testing the app locally first I've just cloned the repo (had some errors like ask question was showing error but it succeed  an answering/commening was showing error about duplicate) but then I've checkout v1.8.3 and it's working (I'm posting just in case you're not aware)

My real issue is that in 1.8.3 search don't work. I've added few question with title "777777777" and I'm search 777 it don't show any questions.

Do I need to do something to enable search? I can't find any issue or question on website QA about this.

I'm using PHP Version 7.2.17 and 10.3.12-MariaDB MariaDB Server.

**Comment by pupi1985** [comment]
Can you explain clearly what the error is in your first paragraph? I didn't understand anything :)

Regarding the search, it happens on the exact search string (not taking into account substrings). If you added the word "abc" to a question, then you will need to search for "abc", not "ab" or "abcd".

What branch are you using?

**Comment by jcubic** [comment]
Oh, so it's not very good search then, in lot of cases useless.

That first issue what just clone and default branch (so I think it was dev) the error what just white page with two messages to look into error logs. (I had `Got error 'Primary script unknown\n'` but that was old and no new error message after each error). And that duplicate error was standard message for string `'duplicate_content'`

**Comment by pupi1985** [comment]
Regarding the search, you can always implement your own [search module](https://docs.question2answer.org/plugins/modules-search) and search in whatever way you want.

Regarding the other error, all I can tell you is the dev branch didn't result in a white page for me after accessing the home page (if that is the test you performed, which is still unclear). Try to provide steps to reproduce the error. Double check your web server is properly configured

**Comment by jcubic** [comment]
Sorry I've explained with in wrong way, the white page with red error to look into apache logs is after I've asked the answer. I've clicked button and got error page but when I've change the url the question was added.

Thanks about search module tip.

**Comment by svivian** [comment]
Why do you think the search is not good? If I search for `ion` I don't expect to see posts with `question` or `station` etc in them. It does miss some similar words like plurals and such, but getting into that is extremely complicated (there's a reason Google is a billion-dollar company!)

But there are various apps/services out there you can use. ElasticSearch, Sphinx, Apache Solr. I dob't know off hand what's open source and what's paid.

**Comment by jcubic** [comment]
The problem is with my language I have words with different ending for different forms in Polish that I will use as my main language we have them for very noun, example word "question" in polish it's "pytanie" but there is also "pytania" "pytań" "pytaniami" "pytaniach" so I want to search for "pyta" and I want to have all of them. So with custom search I'll just use raw sql: `like %pyta%`, if it will be slow (I don't expect lot of questions) then I will think about other solution, I don't think I will be able to use solr or Sphinx because I will use Q2A on shared hosting.
