### ISSUE TITLE
Confirmation e-mail cannot be sent

### ISSUE THREAD

**Issue by turacc** [q2a/question2answer#756]
Hello,

A few users tried to sign up to my website. However, they told me that they have received a message like this:

Question2Answer fatal error:
Could not send email confirmation

Stack trace:

require() in index.php:27
require() in qa-index.php:188
qa_get_request_content() in qa-page.php:47
require() in page.php:183
qa_send_new_confirm() in confirm.php:62

Thank you for your help in advance.
Mehmet

**Comment by svivian** [comment]
This usually means your email settings are incorrect, or the user's email address is not correctly formatted.
