### ISSUE TITLE
package for yunohost

### ISSUE THREAD

**Issue by jibe-b** [q2a/question2answer#757]
[http://yunohost.org/](http://yunohost.org/) enables to install software easily.

Packaging Q2A for Yunohost would help have more Q2A websites used.

cc @alexAubin

**Comment by jibe-b** [comment]
@svivian May I just ask for reasons you think Q2A should not be packaged?

**Comment by svivian** [comment]
Sorry, I wasn’t sure what the purpose of the issue was. Q2A is open source and can be installed on any host. Yunohost are free to add Q2A to their hosting, I don’t know what there is for us to do.

**Comment by jibe-b** [comment]
Ok, that's right, they can do it!
That's just a suggestion to make Q2A more visible by having it available on one more platform.

**Comment by hermann-san** [comment]
I would also love to see question2answer in Yunohost. I've added it to their wishlist, but everybody with some technical background could do the packaging. Detailed instructions on how to do the packaging is available here:  https://yunohost.org/#/packaging_apps
