### ISSUE TITLE
Plugin admin form checkbox cannot be cleared

### ISSUE THREAD

**Issue by counterpoint** [q2a/question2answer#759]
I created a plugin, and added an admin form. The text field works as expected. But two fields with type "checkbox" have a problem. The admin user can tick the boxes and save, and the ticks are recorded. But they cannot then be cleared. Clearing the box and saving has no effect. The message saying "saved" is given, but the checkboxes remain ticked. This may be connected with the fact that SFAIK HTML forms do not send anything if a checkbox is unticked and the form submitted - the server has to assume that if nothing is received from the checkbox, then it is clear.

**Comment by pupi1985** [comment]
It *can* be cleared. Following your own reasoning, if the form is submitted and the checkbox value is not present, then it should be unchecked. Or am I missing something here?

**Comment by counterpoint** [comment]
You are missing something. I have implemented the plugin and tested it, and the box does not get unchecked. The information about browser behaviour was added in the hopes of being of assistance; from past developer experience I know that if a program relies on getting a yes/no indication from the browser for a checkbox, then it will not clear. The browser sends nothing if the box is changed from checked to unchecked, it only sends a value if the box is checked. The software has to deliberately unset the checkbox and only set it if the browser returns a value. I suspect this is not being done.

**Comment by pupi1985** [comment]
> The software has to deliberately unset the checkbox and only set it if the browser returns a value

Q2A has nothing to do with that. _The software_ that you mention, is basically your plugin. I can advise you to go through GitHub repositories of other Q2A plugins to see how they do it.

If that still doesn't work, you can provide the relevant pieces of the code that are not working for you.

**Comment by counterpoint** [comment]
I don't have any code that receives the data for the admin form. I have a method called admin_form which returns an array with information about fields. I am not aware of receiving control when the form is filled in. The text field is stored without my code doing anything, and the checkboxes are stored if previously unset. I'm not aware of anything in my code that does that.

**Comment by counterpoint** [comment]
It's rather inefficient trawling through existing plugins trying to find one that has an admin form with a checkbox. It's not as if I can grep them without downloading first. Are you able to point me to a relevant plugin, if you think the problem is in my plugin?

**Comment by pupi1985** [comment]
> I don't have any code that receives the data for the admin form

That's clearly the issue. You need to handle the POST. This is how you do it: https://github.com/q2apro/q2apro-on-site-notifications/blob/master/q2apro-onsitenotifications-admin.php#L136

**Comment by counterpoint** [comment]
I have something very similar to that https://my.pcloud.com/publink/show?code=XZfcTA7ZSyCtrAHqb3fo9TcXAKPTeQ10mKMy

Is it wrong?

**Comment by counterpoint** [comment]
The problem is that everything is at arm's length through Q2A functions and documentation is sketchy. Me calling qa functions is quite different from me handing POST data. I understand POST data, I don't understand qa functions except to the extent they are documented. Given that the arrays of field data define the characteristics of the fields, I might reasonably have assumed that the qa functions would coerce data appropriately. Also, there is no example of a checkbox field in the plugins installed by default, nor any straightforward way to find a suitable example. Evidently my mistake is that the value returned from qa_post_text has to be coerced to bool. So you are right that this is not a bug, it is a misunderstanding.

**Comment by svivian** [comment]
Just wanted to say thanks for bringing up this issue - I can see how it's confusing. I'd welcome any suggestions to make this easier. If you didn't know, our documentation is open source so you can help improve it: https://github.com/q2a/q2a.github.io
