### ISSUE TITLE
Create an official docker image

### ISSUE THREAD

**Issue by dessalines** [q2a/question2answer#761]
I see this has no official docker installation method, but it'd be nice to have an official docker build. Here's a sample one someone made: https://github.com/Chrislevi/docker-q2a

**Comment by svivian** [comment]
Thanks for the suggestion. I don't use docker myself so I don't know how to create one and have no use for it. Q2A works on any standard PHP/MySQL hosting with Apache/Nginx so you can just take a docker with that and install Q2A on it.

**Comment by dessalines** [comment]
If I create the docker stuff will you re-open this issue?
