### ISSUE TITLE
XSS in Breadcrumbs Plugin

### ISSUE THREAD

**Issue by thierryzoller** [q2a/question2answer#763]
Are you sure about the answer given in "https://github.com/q2a/question2answer/issues/435"  - "And, of course user input is escaped when being added to the database" 

Breadcrumbs is vulnerable to XSS as it reads the title that isn't stripped at all.
https://github.com/amiyasahu/q2a-breadcrumbs/issues/24

**Comment by pupi1985** [comment]
Why is a bug from a third party plugin created as a Q2A core issue?

**Comment by thierryzoller** [comment]
The answer is above, it is claimed that input is escaped when being added to the database. From what we know that wasn't the case and that's part of why the Breadcrumbs plugin is vulnerable.

**Comment by svivian** [comment]
I answered in the other issue - I meant SQL injection. HTML should be escaped on output, not input. https://github.com/q2a/question2answer/issues/435#issuecomment-504973373
