### ISSUE TITLE
Error: Included file xxxx is deprecated

### ISSUE THREAD

**Issue by sama55** [q2a/question2answer#765]
The line below seems to be added to the wrapper source from V1.8.1.
For example: qa-app-updates.php
if (defined('QA_DEBUG_PERFORMANCE') && QA_DEBUG_PERFORMANCE) {
	trigger_error('Included file ' . basename(__FILE__) . ' is deprecated');
}
This line causes many plugins to fail in debug mode. I want to know why you added these lines. Also, I think that these lines should be removed.

**Comment by svivian** [comment]
This was answered on the Q2A site. The reason is those are the old files and were replaced by the ones in folders for better organisation. So instead of including `qa-app-updates.php` you should include `app/updates.php`
