### ISSUE TITLE
reCAPTCHA not working on default installation

### ISSUE THREAD

**Issue by SeanDolan** [q2a/question2answer#766]
Install as default on Apache, PHP server on Windows Server. Tested keys for v2, v2 invisible and v3. The reCAPTCHA box shows, the tick box is verified but when submitting new user registration it returns "Please complete the anti-spam verification" even though the verification appears to work. There are no warnings from Q2A script that there is any issue with the reCAPTCHA plugin.

**Comment by SeanDolan** [comment]
Inspecting the reCAPTCHA box code live does show the following verifying that the plugin is functional but the Q2A is denying it somewhere even though it's working.
`<div id="recaptcha-accessible-status" class="rc-anchor-aria-status" aria-hidden="true">You are verified</div>`

**Comment by SeanDolan** [comment]
I seem to be able to get this working with XAMPP install but not default settings for Apache/PHP. I am guessing the problem is compatibility. I can get reCAPTCHA working on Apache/PHP raw themselves too (just finished testing this) however when integrated with Q2A software it keeps repeating the issue as described. Is there a specific requirement for Q2A I have not seen that might fix this issue?

**Comment by svivian** [comment]
Hi, sorry for the late reply. I wasn't able to reproduce the issue and we've not had other similar reports as far as I know. So I'm not sure there's anything I can do. Double check that you have the correct keys - the plugin uses the regular v2. And see if it works on the default theme as perhaps a theme or other plugin is changing the HTML.
