### ISSUE TITLE
Usefulness of tables userevents and sharedevents?

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#768]
I have never used the tables:

- qa_sharedevents 
- qa_userevents

and would like to know if anyone ever had a usecase for that?

In my recent opinion, those are useless tables from application/usability perspective (but I hope I am wrong).

https://www.question2answer.org/qa/77098/usefulness-of-tables-userevents-and-sharedevents

---

Related: https://www.question2answer.org/qa/50039/needed-option-disable-the-question-user-event-updates-core

**Comment by svivian** [comment]
Answered on Q2A.
