### ISSUE TITLE
 problem with confirmation of mail, with mailing and password recovery....

### ISSUE THREAD

**Issue by AlexSokol97** [q2a/question2answer#770]
Mail confirmation does not come...

When recovering a password, an error occurs...

Question2Answer fatal error:
Could not send reset password email

Stack trace:

require() in index.php:27
require() in qa-index.php:188
qa_get_request_content() in qa-page.php:47
require() in page.php:183
qa_start_reset_user() in forgot.php:69

![2019-08-29_19-09-45](https://user-images.githubusercontent.com/54679334/63957176-96771a00-ca90-11e9-9a7a-25d2461fc229.png)

**Comment by svivian** [comment]
Check that your email settings (in Admin > Email) are all correct. See if there are any other errors in error logs and check with your host in case you need particular settings to send email.

If you find a specific cause then I'll be happy to reopen the issue.
