### ISSUE TITLE
Share users of an existing site

### ISSUE THREAD

**Issue by kksal55** [q2a/question2answer#771]
I have 3 q2a sites.
a.domain.com, b.domain.com, c.domain.com
These 3 sites also have a lot of users and thousands of content. I set up these three sites as normal.
When I first set up these sites, I didn't set up common user settings.

Can I merge users of these 3 sites now?
For example:
Can existing users of a.domain.com log in to c.domain.com?
Can QA_MYSQL_USERS_PREFIX be activated only on the first installer? Can it be subsequently activated in a previously installed db?

**Comment by svivian** [comment]
It's complicated but should be possible. First you need to make sure that no user IDs clash. If you have 100 users on each site they'll have a userid of 1-100. You need to change the other 2 sites to have userid from 101-200 and 201-300. That will automatically changed the userid referenced in other tables like qa_posts.

Also you'll need to ensure that no users are the same on both sites. If they have the same email or username you won't be able to copy them over. I guess you can detect two users with the same email and set their ID to the userid from site A.

Once that's done you should be able to copy them over. You need to copy the contents of the tables `qa_users`, `qa_userprofile` and `qa_usermeta`. Then set the appropriate values in `qa-config.php`.

If you have any further questions feel free to ask on [the Q2A site](https://www.question2answer.org/qa/).
