### ISSUE TITLE
external login with LDAP or Gitlab

### ISSUE THREAD

**Issue by port22** [q2a/question2answer#782]
Hi,
I am very new to Q2A, and I'm stuck how to integrate LDAP auth or, even better, Gitlab (which uses ldap-auth it's own).

Walking through the file `qa-external-users.php`, the examples are mostly regarding an own mysql users db but I can't imagine how to integrate gitlab/ldap. Login/Logout pages is no problem, but I don't see any possible way to access gitlab-database (postgres) or see valuable cookies to gather session information from.

I am surely not the only one who needed this; so may anyone can share his knowledge?

Many thanks!

**Comment by port22** [comment]
actually nobody using ldap ? I'm really stuck on this

**Comment by svivian** [comment]
There is an LDAP plugin listed on the Add-Ons page of the docs: https://github.com/zakkak/qa-ldap-login

Hopefully that works for you. If you have any further questions please ask on the [Question2Answer site](https://www.question2answer.org/qa/), thanks.
