### ISSUE TITLE
Parsing links within code blocks? Bug or Feature

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#785]
File `/qa-include/plugins/qa-viewer-basic.php` parses links in posts if the option `qa_opt('show_url_links')` is true.

The parsing is done with `function get_html($content, $format, $options)`. Starting with:

    if (@$options['showurllinks']) {

Problem is that also links within `<code>` blocks are parsed.

However, links in code blocks should be untouched, IMO. Otherwise it leads to, for instance:

![image](https://user-images.githubusercontent.com/6764548/69491958-d9d10100-0ea4-11ea-93f2-94bf93d30f83.png)

**Comment by svivian** [comment]
Yes I see the problem. Besides `<pre>` and `<code>` can you think of any other tags we'd want to prevent links inside?

**Comment by q2apro** [comment]
I think `<code>` is the most important one, thinking of the usage in programming forums.

`<pre>` I am not sure, but probably yes.
