### ISSUE TITLE
PHP 7.4RC: Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#786]
Just wanted to report that PHP 7.4RC throws the following errors:

> Function get_magic_quotes_gpc() is deprecated in /qa-include/qa-base.php on line 1211
> Function get_magic_quotes_gpc() is deprecated in /qa-include/qa-base.php on line 1224

```
function qa_gpc_to_string($string)
{
	if (qa_to_override(__FUNCTION__)) { $args=func_get_args(); return qa_call_override(__FUNCTION__, $args); }

	return get_magic_quotes_gpc() ? stripslashes($string) : $string;
}

function qa_string_to_gpc($string)
{
	if (qa_to_override(__FUNCTION__)) { $args=func_get_args(); return qa_call_override(__FUNCTION__, $args); }

	return get_magic_quotes_gpc() ? addslashes($string) : $string;
}
```

More info:

> Magic quotes functions ¶
> The get_magic_quotes_gpc() and get_magic_quotes_runtime() functions are deprecated. They always return FALSE.

https://www.php.net/manual/en/migration74.deprecated.php

**Comment by DanielRuf** [comment]
Thanks for reporting this. Do you want to provide a PR to fix this?

**Comment by PELock** [comment]
I set it to return $string;

This feature is deprecated so I would recommend to treat it as disabled by default
https://www.php.net/manual/en/info.configuration.php#ini.magic-quotes-gpc

**Comment by QROkes** [comment]
Is it safe to use Q2A right now with PHP 7.4?
Or is this issue a stop signal?

I'm worried because it seems there will be no update release any time soon.

**Comment by myfirstnameispaul** [comment]
In XAMPP there seem to be loads of problems.

**Comment by DanielRuf** [comment]
As we did not get any PR this may not be fixed yet.
Does anyone want to provide a PR to resolve this?
This would be very helpful. @QROkes

**Comment by codepaints** [comment]
Today we have PHP 7.4.*, and this script is still using PHP 5.2.* and syaing 5.2 or later but getting error in 7.4, It seems not reliable script anymore.

**Comment by DanielRuf** [comment]
@codepaints well, question2answer may have some parts which are still older PHP code - so there is no 100% perfect 7.4 support.

Do you want to provide a PR to fix this?

**Comment by DanielRuf** [comment]
The error appears in all versions of PHP because this is deprecated as the title says it.

**Comment by svivian** [comment]
Thanks for the report, and sorry for the delay in getting to this. Firstly, you should not be showing notices on a live website, they should be logged instead.

The deprecation itself isn't a problem as the function still exists (since PHP 5.4 it just returns false). So yes @QROkes it's perfectly safe. The next Q2A will require a higher minimum PHP so they can be removed in that version.

For Q2A 1.8 it should be possible to add a simple PHP version check and skip the function for PHP7+, but the gpc functions are called from some high impact functions so I'll need to check that it doesn't affect performance.

**Comment by svivian** [comment]
Turns out the functions are not called much so I've fixed this. Will be part of 1.8.4 releasing soon.
