### ISSUE TITLE
Question2Answer fatal error: Missing 1 in language string 

### ISSUE THREAD

**Issue by a840** [q2a/question2answer#787]
From last update 1.7.3, when I answer for questions, I get this error 
Question2Answer fatal error:
Missing 1 in language string question/1_answer_title

Stack trace:

require() in index.php:27
require() in qa-index.php:188
qa_get_request_content() in qa-page.php:47
require() in page.php:191
qa_lang_html_sub_split() in question.php:428

**Comment by svivian** [comment]
Check your language files. In `qa-lang-question.php` you should have a line like this

`'1_answer_title' => '1 Answer',`

The latter part requires the number 1 being in there.
