### ISSUE TITLE
Avatar issue on special user tab

### ISSUE THREAD

**Issue by nioya** [q2a/question2answer#789]
On special user tab of users page, avatars are missing

**Comment by nioya** [comment]
to solve this: 
`function qa_db_users_from_level_selectspec($level)
{
	return array(
		'columns' => array('userid', 'handle', 'flags', 'email', 'created' => 'UNIX_TIMESTAMP(created)', 'avatarblobid' => 'BINARY avatarblobid', 'avatarwidth', 'avatarheight'),
		'source' => '^users WHERE level>=# ORDER BY level DESC',
		'arguments' => array($level),
		'sortdesc' => 'level',
	);
}`



```
$avatarHtml = qa_get_user_avatar_html($user['flags'], $user['email'], $user['handle'],
			$user['avatarblobid'], $user['avatarwidth'], $user['avatarheight'], qa_opt('avatar_users_size'), true);
	$qa_content['ranking']['items'][] = array(
	    'avatar' => $avatarHtml,
		'label' => $usershtml[$user['userid']],
		'score' => qa_html(qa_user_level_string($user['level'])),
		'raw' => $user,
	);
```

**Comment by DanielRuf** [comment]
@nioya thanks for reporting this. Do you want to provide a PR which fixes this?

**Comment by svivian** [comment]
Turns out this was already fixed with the Controller refactoring on the dev branch (will be in v1.9).
