### ISSUE TITLE
Logical delete (hide or flag) of an answer previously selected as the best

### ISSUE THREAD

**Issue by MaxjTechno** [q2a/question2answer#79]
I have 1 question Q with an answer A (1.6.3 , snow theme).
The answer A has been selected as the best.
If the answer A is "logically" deleted (hidden or flagged 2 times), **in the question list** I can see that the question Q's counter (no. of answers) is 0 (correct).
But the colour of the box **in the question list** is still "green" as it was a question with a selected answer (wrong in my opinion, it does not have anymore an associated answer selected as the best).

**Comment by svivian** [comment]
Decided to go with deselecting hidden answers. It would require an extra JOIN to detect whether the selected answer for each question is actually visible (which is why I didn't fix this months ago), plus the situation above (User B removing points from User A) is not really likely to happen.
