### ISSUE TITLE
Add handle and userid to [loggedin] data

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#790]
Currently there is no way (PHP serverside) to get the handle from the loggedin user from the $content.

Under $this->content['navigation'] we have (example data):

```
["loggedin"]=>
  array(3) {
  ["prefix"]=>
  string(6) "Hello "
  ["data"]=>
  string(58) "<a href="../user/testing" class="qa-user-link">testing</a>"
  ["suffix"]=>
  string(0) ""
}
```

It would be very helpful/useful to have the `handle` and the `userid` here as well.

Then the workaround in each plugin using:

```
$userid = qa_get_logged_in_userid();
$handle = qa_userid_to_handle($userid);
```
would not be necessary anymore. And would save one DB request per plugin ...

---

Or if not into the "navigation" then we should probably add a field `[userdata]` next to it.

---

Ah, I just see that we can use `qa_get_logged_in_handle()` as alternative. Still, having those fields in the content might facilitate the programming.

**Comment by svivian** [comment]
I understand the issue but I think the `$content` variable is the wrong place for it. That's intended for content to be displayed on the page, hence it includes a bunch of HTML and so on.

If you need the user ID that suggests you're trying to do something in the theme that should be elsewhere, e.g. a plugin. Anyway as you've discovered you can get the username with that function. It doesn't run extra database queries, the user information is only fetched once per page load. If you want easier access try this in the theme constructor:

    $this->loggedinhandle = qa_get_logged_in_handle();

Then you can use `$this->loggedinhandle` instead.

**Comment by q2apro** [comment]
I still think it would be helpful to have it "somewhere", and the `["loggedin"]` array would be the best place IMHO.
