### ISSUE TITLE
How to debug AJAX requests in question2answer? Especially slow MySQL queries.

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#794]
I noticed that the flag-reasons plugin takes a lot of time when flagging a post via Ajax.

Now I would like to debug it, but since it's Ajax I cannot debug so nicely like with q2a directly (bottom of page).

What would be the ajax debugging way?

<br>

Found one idea from SO: "On the server side, find the db query log and see how long the query itself is actually taking." ... But maybe there is another way, without the logs.

**Comment by svivian** [comment]
Yes debugging the AJAX requests is not easy. You can use Developer Tools in your browser and look at the Network tab. When an AJAX request occurs a new line will appear. Click that to see what comes back from the server. If there are errors they should be shown there.

For performance timing, try adding this to the bottom of `qa-include/qa-page.php`

```
global $qa_usage;
$qa_usage->output();
```

Depending on what type of AJAX request is being done it should output the usual timing block on the page (might get a bit messy!)
