### ISSUE TITLE
Padding should not be added with inline CSS: qa_get_avatar_blob_html()

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#796]
In /app/format.php you find: `qa_get_avatar_blob_html() `. There the padding is programmatically calculated and added as inline-style.

IMO, any CSS should be done using a CSS file.

**Comment by svivian** [comment]
The padding is there to ensure every avatar takes up the same space. If you upload a tall thin avatar it messes up the alignment on the users page when there is no padding. That's why it's programmatically calculated.

**Comment by arjunsuresh1987** [comment]
Hi Scott, just wondering if this can be handled in CSS. Do we really need inline CSS?

**Comment by svivian** [comment]
Yes, the inline CSS is necessary because every avatar needs different padding depending on its size. There is no harm to it.

I think it’s only used on the users list page, other places like questions/answers don’t use it as they don’t need to line up.
