### ISSUE TITLE
qa_blob_exists does not check for the file system when QA_BLOBS_DIRECTORY is true

### ISSUE THREAD

**Issue by bertrandgorge** [q2a/question2answer#799]
qa_blob_exists currently only checks for DB, not for the existence of the file

**Comment by svivian** [comment]
This is by design. All uploads add a record to the database. And all links to file go via the database, whether the file is stored on disk or in the db. So from a Q2A perspective, if the db record doesn't exist, the file does not exist.

**Comment by bertrandgorge** [comment]
Fair enough - I got the issue after playing a little heavily with my different dev installs...!
