### ISSUE TITLE
Few words in the title and description are getting changed to star

### ISSUE THREAD

**Issue by madhavabk** [q2a/question2answer#805]
Whenever i am copy-pasting the content from notepad etc automatically after submission the content gets changed to * symbols for few words.

Its random words through which i am not able to find out why only those are getting changed.

also i get error message - Trying to access array offset on value of type null in d:\nginx1.17.9\nginx-1.17.9\faqs\qa-include\pages\question-view.php on line 1131

**Comment by arjunsuresh1987** [comment]
Do you have any blacklisted words?
