### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() is deprecated in C:\xampp\htdocs\question2answer-dev\qa-include\qa-base.php on line 1177

### ISSUE THREAD

**Issue by sakthivelj** [q2a/question2answer#806]
I keep getting this issue I don't know why it is?

Deprecated: Function get_magic_quotes_gpc() is deprecated in C:\xampp\htdocs\question2answer-dev\qa-include\qa-base.php on line 1177
![image](https://user-images.githubusercontent.com/37198254/79069094-16cd5100-7ce9-11ea-8e6a-8fe26f140a56.png)

**Comment by sakthivelj** [comment]
help me to fix this issue

**Comment by phy25** [comment]
Have you searched the issues board? #786

**Comment by sakthivelj** [comment]
please can you provide a PR to fix this issue?
