### ISSUE TITLE
Category dropdown in wrong place after related questions box appears

### ISSUE THREAD

**Issue by heidongwang** [q2a/question2answer#808]
After writing the title, the first action is to click on the category, do not try to click elsewhere. In this way, there will be the same error as the picture.

![1](https://user-images.githubusercontent.com/59247295/81360666-02754c00-910f-11ea-9a7c-2f8aa7957f0c.PNG)

This happens because the browser detects the first point of reference when the options will open, but at the same time a change in height happens and it outputs the position for that Select List as that first point of reference.

**Comment by heidongwang** [comment]
Is it designed this way, or is it the wrong way to work？

**Comment by phy25** [comment]
This is definitely a browser/OS issue. What browser/OS do you use?

Well a workaround would be to move the dynamic suggestion list to elsewhere, but I am not sure if it's worth fixing.

**Comment by heidongwang** [comment]
I use Chrome browsers and Windows10. This error has nothing to do with the browser and OS, you could try to reproduce it.


1. After writing the title, the first action is to click on the category, do not try to click elsewhere. In this way, there will be the same error as the picture.

2. After writing the title, click on the blank space, and then click on the category. In this way, everything is normal.

1 and 2 are different click order.


This happens because the browser detects the first point of reference when the options will open, but at the same time a change in height happens and it outputs the position for that Select List as that first point of reference.

**Comment by arjunsuresh** [comment]
Is it happening for a particular theme?

**Comment by heidongwang** [comment]
It occurs on all question2answer websites, including the official website. It has nothing to do with the theme.

**Comment by heidongwang** [comment]
Is it possible to consider adjusting the classification position near the label, which is a relatively simple solution.

**Comment by Joanne02** [comment]
I tested it and found that my question2answer site had the same problem. Hope to fix it.

**Comment by arjunsuresh** [comment]
Thanks. I always used to click outside after typing in the title and hence never encountered this. This should be fixable.

**Comment by heidongwang** [comment]
Does anyone care about this problem?

**Comment by svivian** [comment]
It is definitely a browser issue, not specific to Q2A. Seems to happen in most browsers but not all (e.g. Edge). I've seen similar behaviour in browsers before, for example the auto-complete dropdown in a text field not scrolling as you scroll the page.

I don't know if there is any easy solution. We could move the category dropdown above the duplicate question box, but you still might have the same problem if a site added other dropdowns.

**Comment by Joanne02** [comment]
Most users now use Firefox or chrome. So I think question2answer should be adapted to the environment, rather than waiting for the environment to adapt to question2answer.
