### ISSUE TITLE
No working plugin ckeditor youtube

### ISSUE THREAD

**Issue by destinyyousoul** [q2a/question2answer#809]
By removing the option + embed

		'elements' => '*+embed+object-form',
		'elements' => '*-form',

My ckeditor external youtube plugin stopped working.

Is there any way I can post videos like I used to

This happened with the new update 1.8.4

Thanks for your help!

**Comment by svivian** [comment]
Do you have a link to the plugin? The standard way to add YouTube videos is using `<iframe>` (it has been that way for many years actually) so maybe your plugin is out of date.

One alternative would be a [this plugin](https://github.com/NoahY/q2a-embed) replaces a YouTube link with the correct HTML.

Embed/object tags supplied by user input are a security risk so I hesitate to suggest an alternative, but it’s possible to change the `qa_sanitize_html` function using an [override plugin](https://docs.question2answer.org/plugins/overrides/).

**Comment by destinyyousoul** [comment]
Indeed.
I already checked the plugin and use embed instead of iframe

I'll see how I achieve the update

Thanks for your time Scott.
