### ISSUE TITLE
PHP Fatal error: Cannot redeclare qa_db_user_events_truncate()

### ISSUE THREAD

**Issue by mzch** [q2a/question2answer#810]
After upgrading from 1.8.3 to 1.8.4, When I tried to login, the following error occurred.
Any idea?
```
[Fri May 08 11:29:24.504697 2020] [proxy_fcgi:error] [pid 12564:tid 140215137793792] [client 118.243.18.144:55748] AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare qa_db_user_events_truncate() (previously declared in /srv/question2answer-1.8.4/qa-include/db/events.php:148) in /srv/question2answer-1.8.4/qa-include/db/events.php on line 148', referer: https://chiemono.com/
```

**Comment by svivian** [comment]
It sounds like something is including the `db/events.php` file without using `require_once`. Can’t see anything in Q2A doing that.

Please try disabling all plugins one by one to see if one of those is causing it.

Your error also suggests that you put the new version in a separate folder (`question2answer-1.8.4`) - are you somehow loading multiple versions of the code?

**Comment by mzch** [comment]
Once I disabled all plugins and tried enabling one by one... Q2A works!
What's the cause...?

I don't load multiple versions, switching a version by using symbolic link (`question2answer-1.8.4 → question2answer`)

**Comment by svivian** [comment]
Can you find which plugin is causing the issue? It’s probably that one of the plugins uses `require` instead of `require_once`.

**Comment by mzch** [comment]
Strange to say, all plugins don't have a issue and `require` directive (all use only `require_once`).

- basic-adsense
- event-logger
- example-page
- facebook-login
- mouseover-layer
- opensearch-support
- recaptcha-captcha
- tag-cloud-widget
- wysiwyg-editor
- xml-sitemap

**Comment by svivian** [comment]
That's strange. So is the site working fine now?

**Comment by mzch** [comment]
Yes, fine! :)

**Comment by svivian** [comment]
OK will close this then.
