### ISSUE TITLE
Localization of the site in different languages

### ISSUE THREAD

**Issue by Evgenivich** [q2a/question2answer#819]
Interested in multilingual site. There are many translations, it would be possible to use them all on one site, so that users can read and ask questions in their native language.
For example, a user can choose which native language they should use on the site. If the visitor chooses English, then he sees questions and answers only in his native language. If he chooses another language, for example Russian, the same thing, he sees questions and answers only in his native language.
This can be implemented by the subfolder / en /, / ru /, and so on, so that the system, depending on the choice of language, displays only the site in its native language. I think here it is necessary to use a database to store questions and answers in selected languages ​​separately. Although there may be another way, with a simple language switch. I would like to see this in future platform updates. It will be the best solution for multilingual users who speak different languages. Maybe someone has ideas on how this can be implemented better?

**Comment by svivian** [comment]
Hi, Q2A does not have core support for that, however two options spring to mind:

- Use categories. Add a category for each language you will allow, and the URLs for each category page will be like subfolders (see for example https://www.question2answer.org/qa/core).
- Set up multiple copies of Q2A in either subfolders or subdomains, with a shared user base. Use the same database for each one but a different table prefix. Then after you've installed the first one, use the `QA_MYSQL_USERS_PREFIX` option in `qa-config.php` for the other sites.

If you have further queries then please ask on the [Q2A site](https://www.question2answer.org/qa/).
