### ISSUE TITLE
start page not coming-showing a PHP comment when i put my local ip-Please help

### ISSUE THREAD

**Issue by vraghavans** [q2a/question2answer#821]
#<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: index.php
	Description: A stub that only sets up the Q2A root and includes qa-index.php

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

// Set base path here so this works with symbolic links for multiple installations

define('QA_BASE_DIR', dirname(empty($_SERVER['SCRIPT_FILENAME']) ? __FILE__ : $_SERVER['SCRIPT_FILENAME']) . '/');

require 'qa-include/qa-index.php';

**Comment by vraghavans** [comment]
today when i started the server again ,its only showing the apache2 default page,please help

**Comment by svivian** [comment]
I don't know what you mean by "put my local ip", it has nothing to do with the code your posted. FYI you have a # in front of your code there, maybe that's causing issues? You should probably check with your host.

This is not a help forum; if you have any further issues please ask on [the Q2A site](https://www.question2answer.org/qa/). Thanks.
