### ISSUE TITLE
reCAPTCHA v2.0 doesn´t work

### ISSUE THREAD

**Issue by franzpc** [q2a/question2answer#822]
I have 1.8.4 but reCAPTCHA v2.0 doesn´t work? any solution?
Is there a plugin for reCAPTCHA v3?

**Comment by svivian** [comment]
Please provide more info. What exactly doesn't work? Have you set up the correct keys for v2 on https://www.google.com/recaptcha/ ?

**Comment by franzpc** [comment]
I pass the reCAPTCHA, but when I click the register button, I request to do the reCAPTCHA again.

**Comment by svivian** [comment]
Sorry, I'm unable to reproduce this. Make sure you have the correct keys for v2, and your domain is added on https://www.google.com/recaptcha/
