### ISSUE TITLE
Updated Danish lang-files

### ISSUE THREAD

**Issue by ejvindh** [q2a/question2answer#823]
Hi,
Great work done here! Please find attached updated Danish translations. Created on a newly installed Q2A -- so I guess that must be 1.8.4.

Best wishes,
Ejvind
[da.zip](https://github.com/q2a/question2answer/files/4785699/da.zip)

**Comment by gidgreen** [comment]
Thanks, would it be possible for you to put these into a Github repo? We can then link to the repo directly and and updates could be easily made available by you (or others) there.

**Comment by ejvindh** [comment]
No problem: https://github.com/ejvindh/q2a-da

**Comment by gidgreen** [comment]
Added - thanks! http://docs.question2answer.org/addons/
