### ISSUE TITLE
Question2Answer fatal error for sending user verification

### ISSUE THREAD

**Issue by deveshruttala** [q2a/question2answer#826]
hi, @svivian I am facing a using the conform email function. both the local and the stmp method are not working please show me a way.  I am using the master branch with the latest version of MySQL and PHP please give me a solution. here is the error 

Question2Answer fatal error:
Could not send email confirmation
Stack trace:

require() in index.php:18
require() in qa-index.php:178
qa_get_request_content() in qa-page.php:47
require() in page.php:183
qa_send_new_confirm() in confirm.php:62

**Comment by deveshruttala** [comment]
i have tried the method for the previous issues but it did not work

**Comment by svivian** [comment]
Please check your error logs for an error starting "PHP Question2Answer email send error..."

**Comment by deveshruttala** [comment]
hi @svivian , thanks for your response and sorry for the delay.

I have managed to check the error logs for this  error and it showed up this :-  




[Fri Jul 10 07:50:07.347899 2020] [ssl:warn] [pid 7684:tid 564] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jul 10 07:50:07.426849 2020] [core:warn] [pid 7684:tid 564] AH00098: pid file F:/Devesh new/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jul 10 07:50:07.428848 2020] [ssl:warn] [pid 7684:tid 564] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jul 10 07:50:07.463829 2020] [mpm_winnt:notice] [pid 7684:tid 564] AH00455: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.2.30 configured -- resuming normal operations
[Fri Jul 10 07:50:07.463829 2020] [mpm_winnt:notice] [pid 7684:tid 564] AH00456: Apache Lounge VC15 Server built: Apr 22 2020 11:11:00
[Fri Jul 10 07:50:07.463829 2020] [core:notice] [pid 7684:tid 564] AH00094: Command line: 'f:\\devesh new\\xampp\\apache\\bin\\httpd.exe -d F:/Devesh new/xampp/apache'
[Fri Jul 10 07:50:07.466828 2020] [mpm_winnt:notice] [pid 7684:tid 564] AH00418: Parent: Created child process 12308
[Fri Jul 10 07:50:08.323383 2020] [ssl:warn] [pid 12308:tid 640] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jul 10 07:50:08.412322 2020] [ssl:warn] [pid 12308:tid 640] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jul 10 07:50:08.449300 2020] [mpm_winnt:notice] [pid 12308:tid 640] AH00354: Child: Starting 150 worker threads.
[Fri Jul 10 07:52:16.503761 2020] [php7:notice] [pid 12308:tid 1904] [client ::1:55354] PHP Question2Answer email send error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, referer: http://localhost/index.php?qa=confirm
[Fri Jul 10 07:52:16.503761 2020] [php7:notice] [pid 12308:tid 1904] [client ::1:55354] PHP Question2Answer fatal error: Could not send email confirmation, referer: http://localhost/index.php?qa=confirm


**please tell me what to  d o next to resolve this problem**

**Comment by deveshruttala** [comment]
@svivian  here I have used your  local mailer

**Comment by phy25** [comment]
Have you read the logs that direct you to https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting for troubleshooting? Looks like there's a SSL certification problem.

**Comment by deveshruttala** [comment]
hi @phy25  and  @svivian I have gone through the troubleshooting but still, there is  no resolve in the problem

**Comment by deveshruttala** [comment]
Hi @svivian  and @phy25  please review and give me a response asap for the above problem. I really need the solution for this issue . is there any procedure for local mail setup , if there please notify me asap

**Comment by svivian** [comment]
I don't really know anything about local mail setup, but it's an SMTP error and you probably don't have SMTP set up locally. Do you really need to send mail locally? Once the website is live it should work fine, your host should give you SMTP details to use for that.

Going to close this as I don't think it's a bug in Q2A.

**Comment by deveshruttala** [comment]
@svivian and @phy25  thanks for your response. I have a doubt where can I find the mailer class/function to edit the mailer app  password

**Comment by deveshruttala** [comment]
please give me the response for the above question where can I find the mailer function so that I can add my app password and details. (for local mailer ) . I also mentioned that I have a problem with both the methods

**Comment by svivian** [comment]
The mailer functions are in the `qa-include/vendor/PHPMailer` folder. But you don't set the password there, you set it in the admin section under Emails.
