### ISSUE TITLE
I created an AMP theme but can't convert the image to AMP. How to convert <img> to <amp-img>?

### ISSUE THREAD

**Issue by ansbangla** [q2a/question2answer#827]
https://ansbangla.com/12

**Comment by svivian** [comment]
The simplest way would be a string replace. At the point where you output the post content - `q_view_content`, or `a_item_content` - try

    $content = str_replace('<img ', '<amp-img ', $content);

If you need more help please ask on the [Q2A site](https://www.question2answer.org/qa/) as the Github repo is for bug reporting, not support.

**Comment by ansbangla** [comment]
I want to change the width and height, and do not understand how or how to add the code to the number line. This is my first project so having a little trouble understanding.
