### ISSUE TITLE
I want to convert from <img> to <amp-img> with width and height, this is my first project so I don't understand how to do it. Please explain in a little detail

### ISSUE THREAD

**Issue by ansbangla** [q2a/question2answer#828]
https://validator.ampproject.org/#url=https%3A%2F%2Fansbangla.com%2F12

**Comment by ansbangla** [comment]
please help me

**Comment by thopd88** [comment]
Please do not use GitHub to ask those questions.
Ask here: https://www.question2answer.org/qa/

**Comment by ansbangla** [comment]
I've tried a lot, I'm forced to post here, please don't mind.
https://www.question2answer.org/qa/86002/how-to-change-img-tag-to-amp-img?show=86002#q86002
