### ISSUE TITLE
users can't change avatar

### ISSUE THREAD

**Issue by PCcloob** [q2a/question2answer#835]
users that not confirmed email, can't change avatar.
i want this users (not confirmed email) can change avatar.
how....?
thanks

**Comment by svivian** [comment]
I wouldn't recommend this as it's a big target for spam. But it can be done by changing lines 362 & 373 in `qa-include/pages/account.php` and removing this page: ` && !$pending_confirmation`

I'm looking to add more permissions options in future for various things so may add it in core then.
