### ISSUE TITLE
Please unblock my Q2A Q&A account!

### ISSUE THREAD

**Issue by ghost** [q2a/question2answer#837]
Hello! I am Jamil Ahmad. I have a website of Q2A. I love and work in question2answer. I have a account in q2a qa forum. Unfortunately my account has blocked for an unknown mistake. I request you (Q2A Admins) to unblock my account in Q2A QA Forum. This is the link- Question2Answer.org/qa/user/Jamil+Ahmad
please unblock my account as soon as possible!
Waiting for your message... Thank you!

**Comment by phy25** [comment]
I don't think this is the right place to contact. Please try https://www.question2answer.org/feedback.php

**Comment by svivian** [comment]
Not sure why you were banned (maybe because of duplicate accounts) but are not not banned any more. As phy25 said GitHub isn’t the place for this  kind of post.
