### ISSUE TITLE
Please separate "post creation" event and "post update" event

### ISSUE THREAD

**Issue by teddydoors** [q2a/question2answer#840]
All these two events are reported as q_post.

However if I wanted to create a plugin that will trigger when a new question is asked, this can't be done properly, because when old questions is updated (for example to correct grammatical errors), it is also reported as q_post.

Or maybe I'm wrong, "post update" is somewhat post moderation process.

What if a very old question goes under moderation process somehow, what happens if it's re-shown.

**Comment by thopd88** [comment]
We have q_edit when the question is modified. See https://docs.question2answer.org/plugins/modules-event/

**Comment by svivian** [comment]
thopd88 is correct, editing a post reports a `q_edit` event. If that is not happening for you, please give the exact steps to reproduce. Try disabling all plugins to double check something else is not interfering.
