### ISSUE TITLE
Cyrillic in links

### ISSUE THREAD

**Issue by Evgenivich** [q2a/question2answer#845]
If you ask questions in Russian, then the link is formed in Cyrillic, perhaps this is good for SEO, but it is not convenient for users and search engines, it gets a very long link of such a parameter:
`site.ru/5371/%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D1%8F%D0%B7%D1%8B%D0%BA-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D1%83%D1%8E-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D1%83.`
It is inconvenient to copy, sharing links is also difficult, they are very long. When the question is small, the link is also small - this is good for SEO, and search engines love it if there are keywords in the link. But if the question is long, the link is also very long and very inconvenient to use it. The system still does not accept Cyrillic links, which is just as bad for placement.

I suggest making settings in the administrative part, a checkbox where you can enable (switch) the use of links, for example, in Cyrillic or Latin. To make it convenient for everyone. Whoever wants, let him use the Cyrillic alphabet in links, and whoever does not want, let him use the lithin alphabet in links. It will be convenient for all such switching from the administrative part.

Please do this in future updates, I will be very grateful to you.

Thanks.

**Comment by svivian** [comment]
Most (if not all) browsers don't show the encoded URL (with percents), they show the Cyrillic characters like `5371/сделать-перевод-русский-язык-через-командную-строку`. But it appears to come up with the encoded version after copy-pasting the link. Unfortunately this is the browsers' doing and there's no way to prevent that as far as I know.

If you don't want Cyrillic in the URL at all then you can use the option "Remove accents from question URLs" in Admin > Viewing.

**Comment by Evgenivich** [comment]
I'm wildly sorry, of course, but I didn't find the "Remove diacritics from question urls" option in Admin> View. Perhaps you meant the option "Remove accents from URL questions" I used it and links now look like numbers only.
