### ISSUE TITLE
Show Tags in Question Edit when question is hidden

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#846]
Reproduce:

1. Hide question
2. Click on Edit question
3. Tag field is not visible anymore

Due to: File qa-include/pages/question-view.php

Line: `&& !$post['hidden'] && ($rules['isbyuser'] || !in_array($permiterror_retagcat, $button_errors));`

Should be: `&& && ($rules['isbyuser'] || !in_array($permiterror_retagcat, $button_errors));`

**Comment by svivian** [comment]
You can't edit a question when it's hidden. Is there a plugin that enables that? If so I think it would be the job of the plugin to allow the fields to be edited.

**Comment by q2apro** [comment]
Not sure. Not finding the plugin (yet).
