### ISSUE TITLE
Using Postgres instead of Mysql in question2answer

### ISSUE THREAD

**Issue by Ephra** [q2a/question2answer#848]
Hello team

How to change the database from Mysql to Postgres Database or other databases as I wish?

**Comment by svivian** [comment]
We don't officially support Postgres but it should be possible by making function overrides for everything in `qa-include/qa-db.php`. See [the docs](https://docs.question2answer.org/plugins/overrides/) and [here](https://www.question2answer.org/qa/33088/support-for-other-databases-that-are-not-mysql).

**Comment by Ephra** [comment]
I got a simple solution for this. I have done the upgrade but I know this might help someone else to get started easily
These are steps to follow
(Install the script first and login with credentials before you start to do this, it will help you test more easily)

1. Change PDO connection in qa-src/Database/DbConnection.php, make sure you put a connection string required by Postgres

2. Upgrade error log function ( **failError** ), add this line to help you see clearly all errors recorded
  
```
         $filename = '_' . str_replace('-', '_', date('Y-M-d')) . '.html';
        @error_log('Database Error ' . $type . ' error ' . $errno . ': ' . $error . (isset($query) ? (' - Query: ' . print_r($query)) : ''),**3, dirname(__FILE__) . "/../../storage/logs/" . $filename**);
```
  The bolded areas are the ones to be added

3. Download Navicat or any tool of your choice and transfer the database from Mysql to Postgres. Remember to create sequences for basic table imported in Postgres

4. Open your scripts, use your default text editor (for my case, Netbeans ) that will allow you to search in the whole project. 
 Start Changing the followings (You can open file by file in your DB folder (qa-include/db) to edit or you can go straight to my findings)

a)  Search for **LIMIT #,#** and replace this with **OFFSET # LIMIT #**

b) Search and remove a word **BINARY** operator in all SQL 

c) Open your Postgres database and Rewrite these Mysql functions into Postgres equivalent: **hex, unix_timestamp, strt, unhex, to_days, time_to_sec, to_seconds,** and **if** 
Use this link to get a comparison, [Postgres Similar functions with Mysql](https://github.com/kornelski/mysqlcompat/blob/577fe48c6aa03d81f3d5102dc3b479ff6ce608bd/string.sql#L316-L346)

d) Remove <=> operator and replace it with =
 
e) remove the   `    operator in all SQL 

f) Work on some other few SQL syntaxes to match Postgres style. Your error log will just give you clear details of what needs to be changed (I cannot go one by one, the rest are just simple and straight forward)


I hope this might help someone..
