### ISSUE TITLE
array offset on value of type null in app/users.php

### ISSUE THREAD

**Issue by rklec** [q2a/question2answer#850]
If I access `/admin/userfields` (i.e. go to users in the admin settings and click "Add new user field), I do get this error

> Notice: Trying to access array offset on value of type null in [...]/qa-include/app/users.php on line 1257

This seems to be this line:
https://github.com/q2a/question2answer/blob/v1.8.5/qa-include/app/users.php#L1257

Happens both with the [German language](https://github.com/fulgor/q2a-lang-de-formal) and the default English one.

I have no titles set yet and this is a fresh installation.

v1.8.5

**Comment by svivian** [comment]
Fixed in v1.8.6. Thanks for reporting!
