### ISSUE TITLE
Please grant the next Q2A version the ability to allow emojis

### ISSUE THREAD

**Issue by teddydoors** [q2a/question2answer#854]
Please grant the next Q2A version the ability to allow emojis, or in another words 4-byte unicode characters. Currently, there is a big nuisance to achieve it. You can do it by changing the databases settings with uft8mb4 char-set (along with uft8mb4 connection etc...), or doing some tricks to convert emojis into their ALT codes. In either case, you still have to stop Q2A system from removing emojis.

_qa_get_post_content_ function removes emojis from posts.
_qa_get_tags_field_value_ function removes emojis from tags
_qa_handle_email_filter_ removes emojis from handle (ie username)
_qa_get_post_title_ removes emojis from question titles

All 4 functions are done by another function named _qa_remove_utf8mb4_ in _qa-include/util/string.php_

Of course, we still want to remove emoji from titles, tags, and usernames. But to stop removing emojis from posts, we need to override qa_get_post_content function. Unfortunately, this function is not overridable. (qa_remove_utf8mb4 in qa-include/util/string.php is not either). We have no choice but to edit the core file.

Back in 2013, there might be some faint reasons that MySQL needs to be at least 5.5. But now, it's 2020, and MySQL version is usually 2 times bigger.

**Comment by phy25** [comment]
> We have no choice but to edit the core file.

I guess then a pull request would be appreciated here.

**Comment by arjunsuresh** [comment]
There's already a pull request. 
https://github.com/q2a/question2answer/pull/798

**Comment by q2apro** [comment]
Does it have performance issues? I. e. will q2a be slower with this charset?

**Comment by arjunsuresh** [comment]
I don't think so. Switching overt to it didn't cause any noticeable issue on our sites.
