### ISSUE TITLE
Image with First letter for users avatar

### ISSUE THREAD

**Issue by PCcloob** [q2a/question2answer#858]
I want, if the user does not upload an image for their avatar, an image with the first letter of the name or username as the default avatar. 
default avatar with a letter and random color in background:
![Untitled](https://user-images.githubusercontent.com/68686217/96858613-5c738f00-146d-11eb-9fce-b53b0e336a4b.png)

**Comment by PCcloob** [comment]
@svivian  where are you!!??
I really need this...

**Comment by svivian** [comment]
Interesting idea. Not sure if it's right for core Q2A but it should be possible with a plugin. Try asking on the [Q2A Q&A](https://www.question2answer.org/qa/) if you're unable to develop a plugin yourself.
