### ISSUE TITLE
Try to find variables $rules['xxxxx']

### ISSUE THREAD

**Issue by Allread** [q2a/question2answer#862]
Hello :)
I am trying to create a plugin _(on a fork of https://github.com/kfuchs/permission2categories)_ to allow the creation of questions of a category from a rank.

I saw the variable **$rules ['viewable'] = 0;** which allows to hide the category.

But I can't find the variable to prevent opening a new question ...

$rules ['writable'] ?
$rules ['openable'] ?
.... 

I don't know if I am precise !

Thx <3

**Comment by q2aprick** [comment]
You can try with print_r($rules) to see all the keys.

Or have a look at the function qa_page_q_post_rule https://github.com/q2a/question2answer/blob/78b969da37468e8668559e3ffe23687ae5587129/qa-include/pages/question-view.php#L102

I can see viewable, commentable, editable, retagcatable, moderatable....  It seems that it's applicable to already-created questions.

If you are trying to create a special section of your site for your staffs or Devs, you can install a separated Q2A installation but with the same user database. For example, you create a fold name /dev , and then download the Q2A package, upload to that folder and install normally but with the same database, and the same user table.

In your new Q2A installation, you can do whatever to select who can view, or who can post.

**Comment by svivian** [comment]
[Answered on Q2A](https://www.question2answer.org/qa/89132/i-try-to-find-variables-%24rules-xxxxx-writable)
