### ISSUE TITLE
Publicize required PHP extensions

### ISSUE THREAD

**Issue by q2aprick** [q2a/question2answer#863]
Is there any benefit of publicizing required PHP extensions so that Q2A sites can work functionally?

I've seen various reports that when someone upgraded PHP version to 7.x and then his site didn't load properly. All these reports didn't seem to have an answer.

I think

Default PHP extension package is not the same for every hosting provider or Cpanel or similar dashboards.
When someone upgrades to a higher PHP version, some required PHP extensions for Q2A are not automatically selected.
Some required PHP extensions for Q2A may not work, may cause malfunction, is depreciated, or is no longer maintained.... in a newer PHP version.
Some required PHP extensions for Q2A may not work in some particular systems or environments. For example. PHP 7.3 in combination with macOS 10.13.6 may cause some errors like errors with pcre.

So, should we let everybody know the required PHP extensions for Q2A (or keep them as a secret)?

**Comment by svivian** [comment]
The only extension that's required is `mysqli` and this is listed on the Q2A home page. There are some others which are optional like GD and MBString, I guess these could be mentioned somewhere.

PCRE is [always enabled according to the PHP manual](https://www.php.net/manual/en/pcre.installation.php )so I don't know how there could be a problem with that.

**Comment by q2aprick** [comment]
https://docs.typo3.org/m/typo3/guide-installation/master/en-us/In-depth/SystemRequirements/Index.html#php-required-extensions
The example link says it all.

**Comment by svivian** [comment]
OK I see. Macs aren’t used for hosting live websites so that’s a very niche case in a dev environment, and not really anything to do with Q2A itself.
