### ISSUE TITLE
Suggestion: Ask a question to a specific user

### ISSUE THREAD

**Issue by Evgenivich** [q2a/question2answer#872]
I propose to make it possible to ask a question to a specific user, in the opinion of the site owner, who answers questions more often and faster. In the users section, you can add a "Ask a question" button to each user. Also add statistics - answers questions for the N-th period of time. So the questioner can choose the user who is the fastest to answer the questions. This will generate interest in asking questions more often and to specific users. In this case, the user who is asked the question should receive notifications, for example by email.

**Comment by svivian** [comment]
Please keep features requests to the [Q2A site](https://www.question2answer.org/qa/), thanks :) Seems like it would make a good plugin if you're able to develop it.
