### ISSUE TITLE
Modularize current user registration

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#88]
Q2A has built-in user registration and login features. It also allows you to use a plugin to support other registration and authentication methods, e.g. https://github.com/alixandru/q2a-open-login

However, you cannot disable the built-in user registration/login.

I am using q2a-open-login and would like to disable the built-in user registration and login system and not have it shown on the page.

**Comment by fulldecent** [comment]
Closing, I don't think this is going to happen.

**Comment by svivian** [comment]
Yes sorry, this has been low-priority. There should be ways to achieve this using function overrides, for example overriding `qa_create_new_user` to block registrations. And a layer or custom theme to remove registration/login forms from their respective pages.
