### ISSUE TITLE
Error: Trying to access array offset on value of type null in /qa-include/pages/confirm.php on line 75

### ISSUE THREAD

**Issue by AnthonyVO** [q2a/question2answer#880]
I upgraded to PHP 7.4 and Q&A 1.8.5 and when I reviewed the error_log I still find the following errors.

I resolved the issue by changing

`if (strtolower(trim($userInfo['emailcode'])) == strtolower($code)) {`

to 

`if (!is_null($userInfo) && strtolower(trim($userInfo['emailcode'])) == strtolower($code)) {`

**Comment by pupi1985** [comment]
I can confirm this issue. It happens in the unlikely scenario in which the user clicks on the the confirm link after their user has already been removed from Q2A
