### ISSUE TITLE
Unable to add category as superadmin

### ISSUE THREAD

**Issue by mthan160** [q2a/question2answer#882]
To replicate:

1. Fresh install of Q2A
2. Access as superadmin
3. Go to Admin > Categories > Add Category
4. Receive HTTP ERROR 500

Error log:
`[php:notice] [pid 19172] [client 127.0.0.1:39388] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /home/x/lampstack-8.0.1-0/apache2/htdocs/qa/qa-include/pages/unanswered.php:39\nStack trace:\n#0 /home/x/lampstack-8.0.1-0/apache2/htdocs/qa/qa-include/app/page.php(187): require()\n#1 /home/x/lampstack-8.0.1-0/apache2/htdocs/qa/qa-include/qa-page.php(47): qa_get_request_content()\n#2 /home/x/lampstack-8.0.1-0/apache2/htdocs/qa/qa-include/qa-index.php(188): require('...')\n#3 /home/x/lampstack-8.0.1-0/apache2/htdocs/qa/index.php(27): require('...')\n#4 {main}\n  thrown in /home/x/lampstack-8.0.1-0/apache2/htdocs/qa/qa-include/pages/unanswered.php on line 39, referer: http://127.0.0.1:8080/qa/index.php?qa=admin&qa_1=lists`

**Comment by pupi1985** [comment]
Please, check if these changes fix the issue. Thanks.

**Comment by svivian** [comment]
It fixed the issue for me, merged into the bugfix branch.

**Comment by mucahitozel55** [comment]
Thank you so much @pupi1985 it fixed my issue.

**Comment by update20221** [comment]
how to find this option??my ask[ask](https://ask.updatelike.com) face this problem
