### ISSUE TITLE
Disable downvotes

### ISSUE THREAD

**Issue by eupraxis1981** [q2a/question2answer#885]
Can this be a core configuration feature (vs CSS hacking)?

**Comment by pupi1985** [comment]
You can change the permissions in the **admin/permissions** section

**Comment by eupraxis1981** [comment]
> You can change the permissions in the **admin/permissions** section

Ah, so this is a runtime config using interface. Is there a code-level config?

**Comment by pupi1985** [comment]
Strictly speaking, you can change whatever you want from the code. However, if you want some `DOWNVOTING_ENABLED = false` setting, then no, it doesn't exist
