### ISSUE TITLE
Memory Optimization for Q2A - more details from Debug?

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#886]
According to https://tideways.com/profiler/blog/testing-a-new-approach-to-memory-profiling-in-php-with-xhprof:

> With PHP 7 there is a new hook into the Zend memory allocator that allows us to count the number of memory allocations, memory frees and the size of all memory allocations.

My q2a instance needs about **1589 kB** of RAM in total. 

![image](https://user-images.githubusercontent.com/6764548/111744091-50acbd00-8893-11eb-8c8f-b238b9df40dc.png)

I would like to optimize this value as I expect several thousands of concurrent users.

Is there any way (with q2a, in PHP) to get more details of which plugin/function is allocating the memory? That would be extremely helpful.

**Comment by svivian** [comment]
Are you specifically having problems with low memory? 1500kb of RAM is not that much. I just tested a Wordpress site I'm working on and its memory usage its over 9700kb on a homepage with not much content. And another site (using Laravel) varied between 3700kb and 6900kb.

I don't think there is an easy way to determine exactly what uses the most memory, but it looks like the theme has the most. You could try outputting `memory_get_usage()` at various places and see where it jumps up the highest.

**Comment by q2apro** [comment]
Thanks a lot, Scott. 

I did disable plugin by plugin and compared the values, this way I could see that most of the active plugins (on the question view page) are about 15K - 20K.

Only one plugin that improves the design of the user profile page eats 127 KB on each question view page. That is strange.

In the plugin I extend the function main_parts like this:

```
	function main_parts($content)
	{
		// custom user profile page - NOT for admin (to see all options and fields)

		// check if user profile template and if not clicked on edit and not admin
		if($this->template=='user' && !qa_clicked('doaccount'))
		{
			require_once QA_INCLUDE_DIR.'db/metas.php';

			$duration = $content['form_profile']['fields']['duration']['value'];
			$duration_label = $content['form_profile']['fields']['duration']['label'];
			$level = $content['form_profile']['fields']['level']['value'];
			// ...

```

Even though I do not process the code (different template), it seems that the code/content is still loaded into the memory.

I don't know yet how to prevent this.

**Comment by q2apro** [comment]
I think I understand now. With the plugin I `unset` some values and assign a new value.

By doing so, the `$content` is not referenced anymore, but a copy is created.

Thus the memory affected.

**Comment by svivian** [comment]
If there is a lot of code inside that if clause then it still has to be parsed - but not executed. I don't think it would cause that much trouble but you could try moving it to another PHP file then just putting `include 'custom.php';`

That way the code is only parsed when that if clause executes. Closing this as it doesn't seem to be an issue with Q2A.
