### ISSUE TITLE
how to get 'Extra fields'  input value ?

### ISSUE THREAD

**Issue by asfarmed** [q2a/question2answer#893]
HI 
I added an additional input in the registration form for the phone number (https://prnt.sc/112ja0x ) , and I want to use this element on the user's question page
how to get this input value ?

thanks you

**Comment by svivian** [comment]
The simplest way would be this PHP code:

    $userprofile = qa_db_single_select(qa_db_user_profile_selectspec($userid, true));

Then you'll find the field in one of the array keys, e.g. `$userprofile['phone']`. That's assuming you have the user ID. Not sure where you're planning to use this but in a theme layer you should have access to `$this->content['q_view']['raw']['userid']`

If you have any more questions feel free to ask on the [Q2A site](https://www.question2answer.org/qa/), thanks.
