### ISSUE TITLE
Avatar can only be loaded with 50px and cannot be changed

### ISSUE THREAD

**Issue by rklec** [q2a/question2answer#895]
After I upgraded to v1.8.6 I have the problem that avatars can only be loaded with a size of 50 pixel and no one can upload a new avatar.

52px are e.g. used in the top right as an avatar image and 50 px are used in questions.

```
http://.../?qa=image&qa_blobid=150...&qa_size=50 # works

http://.../?qa=image&qa_blobid=150...&qa_size=52 # does not work
```

Also the failing requests (i.e. both requests) return a 200 HTTP Code, however. IMHO, this should not happen.

---

When I try to upload an avatar as a PNG image, I get this error:
> Das Bild konnte nicht gelesen werden. Bitte laden Sie eines hoch von: GIF, JPG, PNG

In English:
> The image could not be read. Please upload one of: GIF, JPG, PNG

I.e. it wrongly claims the file format is wrong.

Q2A v1.8.6
PHP 8.0.1

**Comment by QROkes** [comment]
Yes, I can confirm this issue. In my case, size=200 is correctly loaded and 50 and 20 are failing. I'm also using PHP 8.

**Comment by pupi1985** [comment]
@QROkes Can you check the pull request I've just linked and test that branch? Bare in mind you should clear the browser's cache before testing. Thanks.

**Comment by QROkes** [comment]
Thanks a lot @pupi1985 it works like a charm!

**Comment by rklec** [comment]
The PR is https://github.com/q2a/question2answer/pull/906 - BTW you can link it at the right side or by [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in the PR/commit _body_ (not title).

**Comment by rklec** [comment]
It was just a helpful tip for the text time, it is only linke dhere, because the _commit_ is linked, the _PR_ was not linked. I did not test the PR yet.
