### ISSUE TITLE
Pb to ask a question with chrome

### ISSUE THREAD

**Issue by Ljbouere** [q2a/question2answer#899]
Hi
We have noticed that it is impossible to ask a question on this forum https://rudi.datarennes.fr/yeswiki/?LeForum using Chrome. It works well on firefox.
When you write a question it says "click to confirm" and it is stopped.
Any idea ? Thanks (and sorry for my english)

**Comment by pupi1985** [comment]
The _forum_ you're linking in that URL is so significantly different from what the Q2A core provides out of the box that it probably doesn't make any sense to ask for support for Q2A in this repository. You should get in touch with the developer that made those changes or start using a standard Q2A version.

**Comment by Ljbouere** [comment]
It comes from here. https://www.question2answer.org/ I thought it was the right repository. It is the web adress that is mentioned on github. What do I have done wrong ?

**Comment by Ljbouere** [comment]
my version is 1.8.5

**Comment by pupi1985** [comment]
If that's the case, then replace all files from the repository and make sure it looks like this page: https://www.question2answer.org/qa . Then, check again if you see the error
