### ISSUE TITLE
$silentproblems[] - A non-numeric value encountered

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#903]
Someone used a "punkspider" bot against my website. That triggered this error:

> Error : A non-numeric value encountered

`$silentproblems[] = 'timeout after ' . ($timenow - $timestamp) . 's';`

In `qa-include/app/users.php`. https://github.com/q2a/question2answer/blob/dev/qa-include/app/users.php#L1357

> User Agent: Punkspider/5.0 (opt-out to support@hyperiongray.com)
> IP: 3.23.208.80

How can "non-numeric value" happen at that line of code? – I guess it was an injection/hack attempt.

How to fix it?

**Comment by q2apro** [comment]
```
function qa_check_form_security_code($action, $value)
{
			//...
			$loggedin = $parts[0];
			$timestamp = $parts[1];
			$hash = $parts[2];
```

The evaluation of the incoming data is missing. 

`$parts[0]` should be int?
`$parts[1]` should be checked for timestamp format.
`$parts[2]` should be filtered to allow only alphanumeric (I guess).

**Comment by q2apro** [comment]
Can somebody confirm that those changes are correct and implement them in `users.php`?

**Comment by svivian** [comment]
Thanks for reporting! It's an edge case since someone needs to manually tamper with the CSRF code, but it's good to make sure variables are the correct types :)
