### ISSUE TITLE
I want to remove Facebook login plugin inline css

### ISSUE THREAD

**Issue by engrmdbelal** [q2a/question2answer#916]
I found a new problem with the Facebook plugin. This is the problem with inline CSS. This problem exists in 2 lines. Exists in lines 61 and 83. I hope you will solve it. Take a look at the two pictures I am giving.
Directory: qa-plugin/facebook-login/qa-facebook-login.php
![IMG_20211019_174128](https://user-images.githubusercontent.com/92283722/137903362-9f75df5d-b561-4835-a67a-4341c3b03cb0.jpg)
![Screenshot_2021-10-19-17-41-00-14](https://user-images.githubusercontent.com/92283722/137903395-5554e43b-e038-4bbb-8469-ac1fff28612d.jpg)

**Comment by svivian** [comment]
There's no problem with this. But if you want to change it, make it `class="example"` and add the style to a `.example{}` rule in your CSS.
