### ISSUE TITLE
Telegram bridge

### ISSUE THREAD

**Issue by mcollica** [q2a/question2answer#918]
Is it possible to automate the sending of a message in a Telegram channel (with stuff like IFTTT, Automate.io) each time a new post is created in a specific course of Q2A? Thanks in advance.

**Comment by svivian** [comment]
Yes it should be possible using plugins, [check the docs](https://docs.question2answer.org/plugins/). You'd want an event plugin to took into 'q_post' or 'a_post' and then use whatever code you have to send that to Telegram.
