### ISSUE TITLE
PHP warning when using CAPTCHA

### ISSUE THREAD

**Issue by GarfieldsPipe** [q2a/question2answer#930]
`PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /question2answer/qa-include/app/captcha.php on line 85`

Using https://github.com/ChrisNeedSpace/q2a-captcha-antibot for the captcha on my site.

**Comment by pupi1985** [comment]
This is odd. What version/branch are you using exactly?

Can copy/paste the content of the first 90 lines of your `qa-include/pages/register.php` file?

**Comment by GarfieldsPipe** [comment]
> This is odd. What version/branch are you using exactly?

Using the bugfix branch with the latest commit.

> Can copy/paste the content of the first 90 lines of your `qa-include/pages/register.php` file?

It's exactly the same [as in the repo](https://raw.githubusercontent.com/q2a/question2answer/bugfix/qa-include/pages/register.php), no changes.

Using PHP 7.3 btw.

**Comment by pupi1985** [comment]
I haven't been able to replicate the warning in those conditions. Can you provide step by step instructions to do so?
