### ISSUE TITLE
Can't open registrations

### ISSUE THREAD

**Issue by stemy2** [q2a/question2answer#931]
Hello,

The button "register" is absent from the login box and i don't understand how to make it appear. The option for suspending inscription is already unchecked and i didn't found any other parameters about allowing new registrations.

**Comment by pupi1985** [comment]
Which of the 3 installation methods have you followed?

1. Basic Install
2. WordPress
3. Single Sign-On

**Comment by stemy2** [comment]
none of these three, just this one: https://github.com/YunoHost-Apps/question2answer_ynh

**Comment by pupi1985** [comment]
If you are using the code from repository A, then why would you ask for support to repository B? Please, follow the instructions from the official Q2A repository/site or ask for support in the other repository. Thanks.

**Comment by stemy2** [comment]
The repository maintainer explicitely asked to ask him questions about installation or updates only, other types of questions must be asked to the main application maintainer (in this case, you). This is why i though i had to ask it here.
