### ISSUE TITLE
Login page and forgot pw page are not checking if a user or IP is blocked

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#940]
> Register and Login page are not checking if a user or IP is blocked

Should be implemented.

/qa-include/pages/login.php
/qa-include/pages/forgot.php

```
if (qa_is_ip_blocked())
{
	$errors['password'] = 'IP blocked';
}
```

and 

```
// check if account is blocked (login page)
$userdata = qa_db_read_one_assoc(qa_db_query_sub('
				SELECT flags 
				FROM `^users`
				WHERE userid = #
				', $inuserid), true);

if ($userdata['flags'] & QA_USER_FLAGS_USER_BLOCKED)
{
	$errors['password'] = 'Account blocked'; // qa_lang()
}
```

**Comment by svivian** [comment]
Blocked users are allowed to log in, but they cannot post anything. I think that's fair, maybe there's something in their account they want to see. They might only be temporarily banned depending on the site's rules.
