### ISSUE TITLE
qa_update_counts_for_q  cost much time when we have large num of posts

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [q2a/question2answer#943]
When create / hide / delete quesions , we will call funtion qa_update_counts_for_q to recout numbers . I found when the db have large numbers of posts ,this founction will cost much time. I think we should optimize this fouction

**Comment by svivian** [comment]
Several performance improvements have been made recently which should make that function much faster. If you're able to test with the latest version of the 'bugfix' branch that would be great. If it's still slow I can reopen this issue.
