### ISSUE TITLE
No install process at setup 

### ISSUE THREAD

**Issue by frankeymen** [q2a/question2answer#958]
Just placed all files in my root, setup the qa-config.php and .htaccess.

Now when I visit the root domain I get the following error:

Fatal error: Uncaught mysqli_sql_exception: Table 'q2a_db.qa_options' doesn't exist

I expected to be shown a setup proces, how can get into that process?

**Comment by pupi1985** [comment]
Check [this answer](https://www.question2answer.org/qa/102210/q2a-not-create-table-when-first-running?show=102285#a102285).
