### ISSUE TITLE
Can we finally show user's full name instead of username on q2a

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#96]
This tweak is demanded from a long time in q2a. There is no sense in using username when user has provided his/her full name. So can we finally have this in q2a v1.7??

**Comment by Schoaf** [comment]
I don't see why it is a reason to close the issue that the field "Full Name" is not present in each installation.

It should definitely be possible to change the displayed name to a specified field from a list of defined (and required) fields of your installation. And it seems that a lot of people would like to have that.

To me that definitely seems to be core functionality, looking at the parts of code that have to be changed to make this work. Also it should definitely be able for other plug-ins to take advantage of a "display_name" that it can use.
