### ISSUE TITLE
Sitemap.xml issues

### ISSUE THREAD

**Issue by PELock** [q2a/question2answer#965]
Some validators says you put invalid tags in XML sitemap

https://www.mysitemapgenerator.com/service/check.html

Error:

"All values in a Sitemap must be entity-escaped. Please check to make sure that your URLs follow the RFC-3986 standard for URIs, the RFC-3987 standard for IRIs, and the XML standard."

https://odzyskiwaniedanych.net.pl/tag/odzyskiwanie+danych

I also think you should trim out the priority to 2-3 places after period

```xml
<url>
<loc>https://odzyskiwaniedanych.net.pl/tag/arkusz+kalkulacyjny</loc>
<priority>0.33333333333333</priority>
</url>
```

**Comment by pupi1985** [comment]
Regarding the plus sign, it shouldn't be there. It's a bit picky, IMO, but it is true that's a bug. This PR should fix it: https://github.com/q2a/question2answer/pull/966

Regarding the priority length, there is nothing in the [protocol definition](https://www.sitemaps.org/protocol.html) that states any length. I've forced the length to 10 digits just to have some controlled limit.

Regarding priority `1` being invalid (I'm getting that error from that validator) that's a bug in the validator. Some reference links:
- http://books.xmlschemata.org/relaxng/ch19-77057.html
- https://www.w3.org/TR/xmlschema-2/#decimal:~:text=decimal%20has%20a,100000.00%2C%20210.

I also took the example sitemap from the [official page](https://www.sitemaps.org/protocol.html):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://www.example.com/</loc>
      <lastmod>2005-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
</urlset> 
```

And I got this error from the validator:
```
XML Sitemap must begin with an opening <urlset> tag which includes the namespace (protocol standard) declaration, and end with a closing </urlset> tag.

>
```

So the validator **is buggy**. I advise you to use other validators.

**Comment by PELock** [comment]
Thank you :)
