### ISSUE TITLE
the basic install should mention you need to switch to the master branch

### ISSUE THREAD

**Issue by tooPhatJones** [q2a/question2answer#967]
I recently walked through the basic install https://docs.question2answer.org/install/
And it says you can find the latest version of the code on github. However, the default branch is dev, not master. 

It would probably be good to mention the person installing needs to switch to the master branch because there are bugs in the dev branch. 
Or just make master the default branch?
Either way...

**Comment by svivian** [comment]
Good point. I've updated the docs.
