### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by marksikaundi** [q2a/question2answer#970]
`i have installed the scrept in the subdomain and now am getting this response`
This page isn’t workingforum.leefcode.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by pupi1985** [comment]
What is the exact error from the web server's log?

**Comment by marksikaundi** [comment]
> What is the exact error from the web server's log?

am just getting this error from the site
https://forum.leefcode.com/

**Comment by marksikaundi** [comment]
> What is the exact error from the web server's log?

hope to get help from you. Thanks

**Comment by pupi1985** [comment]
> The config file could not be found. Please read the instructions in qa-config-example.php

I think it is a bit redundant to tell you the `qa-config.php` file is not being accessible by your web server. Please, follow the installation instructions properly
