### ISSUE TITLE
I can't comment with picture

### ISSUE THREAD

**Issue by juanmaocxy** [q2a/question2answer#973]
I can't comment with picture and I can't questions with picture

**Comment by Ajinkgupta** [comment]
Can you provide some more details about this error 

-- maybe you haven't enabled the uploading images option in admin panel 

go to admin -> plugins -> editor -> enable image uploading


![image](https://user-images.githubusercontent.com/76146259/210054917-e4841ebe-95b5-4572-a22d-59bd24157ad5.png)
