### ISSUE TITLE
about new version 1.8.8

### ISSUE THREAD

**Issue by PCcloob** [q2a/question2answer#984]
Thanks for releasing the new version
  But the new version did not have many changes; We expected many changes to be made.
  The changes I am considering are as follows:
1- User's profile photo: If the user uploads a photo, his photo will be displayed, otherwise, the letter avatar will created.
2- user sends a post and waits for the administrator's approval, the administrator checks the post. If there is no problem, it will be published, and if it needs editing, it will not be published. It will be referred to the user and a message should be inserted below the post stating why your post was rejected and this edit must be applied to publish your post. In other words, each user can see their posts on their own page, whether they are published posts or unpublished posts, and the reason why the post was rejected below it.
3- It is possible for users to register and log in to the site using their mobile number and one-time password. Because some users don't have Gmail or email, especially beginners.
4- SEO of the site is not very interesting, it is expected to work on its SEO.
5- The default format is duplicated, it is necessary to make changes in the format.
6- To improve the site search. For example, specify whether we want to search in the titles or in the text of the posts?
7-And...

**Comment by svivian** [comment]
1.8.8 is a “patch” version, for bug fixes, so you shouldn’t expect new features. We fixed many issues occurring in PHP 8 and it took a lot of effort and testing.

The GitHub isn’t for feature requests but I’ll keep your comments in mind, thanks.
