### ISSUE TITLE
Using Transifex easier? Is it possible to add quotes to source file qa-lang-main.php? "In the file qa-lang-main.php, you need to put quote symbols around the numbers 1 and 4 in lines 65 and 80."

### ISSUE THREAD

**Issue by markosu** [q2a/question2answer#987]
I like to use Transifex service to manage translations. Is it possible to add quotes to source file qa-lang-main.php?
Is there any good reason why these lines don't have quotes?

" In the file qa-lang-main.php, you need to put quote symbols around the numbers 1 and 4 in lines 65 and 80."
https://community.transifex.com/t/transifex-github-integration-question2answer-error-there-were-some-errors-in-your-configuration-file-at-least-one-filter-is-required/3593

**Comment by svivian** [comment]
Hi, sorry for the late reply. This is fine, I've gone ahead and updated the file.
