### ISSUE TITLE
Spam posts and comment and user registration, captcha not working, please provide dedicated function in this cms for handling bots and spamy links

### ISSUE THREAD

**Issue by Pooja-Ydv** [q2a/question2answer#988]
bots are bypassing google captcha... they puts links automatically... and do registration with email confirmed... please add a robust script or function for handling spam.

**Comment by svivian** [comment]
Related discussion here: https://github.com/q2a/question2answer/issues/793

Q2A also has many tools to send posts for moderation so you have to approve them yourself.
