### ISSUE TITLE
Not support and Many Warning for windows 8.2 ...

### ISSUE THREAD

**Issue by wnunezc** [q2a/question2answer#999]
**Describe the bug**
Not support and Many Warning for windows 8.2 ...

**To Reproduce**
Please enter the steps to reproduce the behavior:
install and use on 8.2 php environment

**Comment by svivian** [comment]
Can you provide some specific examples? It's hard to know how to solve an issue when I don't know what the issue is...

**Comment by luckybhumkar** [comment]
@arcanisgk just try to run your Q2A sites by renaming _**qa-plugin**_ directory.

⚠ Please Note: It will disable all plugins including wysiwyg-editor. So, better to try with staging site.

If the site runs without any error, move plugins one by one to a new directory named **_qa-plugin_**

_The solution works as long as you haven't modified the core files and are using the theme bundled with Q2A._
